"""Modelo generado por tools/xl2py.py — NO editar a mano (regenerar desde la hoja de Excel)."""

NCOMBO = 10

DERIVED = [  # (fila, nombre, etiqueta, unidad, expresión)  — fórmulas de la hoja DISEÑO
    (18, 'vg_d_mm', 'Peralte d', 'mm', "((DIS_E18) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (19, 'vg_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E19) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (20, 'vg_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E20) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (21, 'vg_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E21) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (23, 'vg_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(vg_acero,_cat('M',5,'M',10),0))"),
    (23, 'vg_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(vg_acero,_cat('M',5,'M',10),0))"),
    (28, 'co_d_mm', 'Peralte d', 'mm', "((DIS_E28) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('H',5,'H',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (29, 'co_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E29) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('I',5,'I',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (30, 'co_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E30) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('J',5,'J',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (31, 'co_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E31) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('K',5,'K',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (33, 'co_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(co_acero,_cat('M',5,'M',10),0))"),
    (33, 'co_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(co_acero,_cat('M',5,'M',10),0))"),
    (43, 'pl_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(pl_acero,_cat('M',5,'M',10),0))"),
    (43, 'pl_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(pl_acero,_cat('M',5,'M',10),0))"),
    (53, 'pn_Fnt', 'Fnt / Fnv', 'kgf/cm²', "_index(_cat('R',5,'R',8),_match(pn_grado,_cat('Q',5,'Q',8),0))"),
    (53, 'pn_Fnv', 'Fnt / Fnv', 'kgf/cm²', "_index(_cat('S',5,'S',8),_match(pn_grado,_cat('Q',5,'Q',8),0))"),
]

GLOBAL = [  # (fila, sección, símbolo, descripción, unidad, nombre, expresión)  — hoja CALCULO
    (5, '0. GEOMETRÍA Y MATERIALES', 'rodilla', '1 = rodilla ; 0 = cumbrera', '-', 't_rod', "((1) if (_eq(_s(tipo)[:int(3)],'Rod')) else (0))"),
    (6, '0. GEOMETRÍA Y MATERIALES', 'E', 'Módulo de elasticidad', 'kgf/cm²', 'k_E', '2040000'),
    (7, '0. GEOMETRÍA Y MATERIALES', 'cos θ', 'Pendiente de la viga', '-', 'k_cos', 'math.cos(math.radians(theta))'),
    (8, '0. GEOMETRÍA Y MATERIALES', 'sen θ', 'Pendiente de la viga', '-', 'k_sin', 'math.sin(math.radians(theta))'),
    (9, '0. GEOMETRÍA Y MATERIALES', 'd', 'Peralte en la conexión (con cartela si existe), perpendicular al eje', 'cm', 'b_d', '(((vg_dh) if ((vg_dh>0)) else (vg_d_mm))/10)'),
    (10, '0. GEOMETRÍA Y MATERIALES', 'bf', 'Ancho de ala', 'cm', 'b_bf', '(vg_bf_mm/10)'),
    (11, '0. GEOMETRÍA Y MATERIALES', 'tw', 'Alma', 'cm', 'b_tw', '(vg_tw_mm/10)'),
    (12, '0. GEOMETRÍA Y MATERIALES', 'tf', 'Ala', 'cm', 'b_tf', '(vg_tf_mm/10)'),
    (13, '0. GEOMETRÍA Y MATERIALES', 'dp', 'Peralte a lo largo de la placa = d/cos θ', 'cm', 'b_dp', '(b_d/k_cos)'),
    (14, '0. GEOMETRÍA Y MATERIALES', 'tfp', 'Ala proyectada = tf/cos θ', 'cm', 'b_tfp', '(b_tf/k_cos)'),
    (15, '0. GEOMETRÍA Y MATERIALES', 'dc', 'Columna', 'cm', 'c_d', '(co_d_mm/10)'),
    (16, '0. GEOMETRÍA Y MATERIALES', 'bcf', 'Columna', 'cm', 'c_bf', '(co_bf_mm/10)'),
    (17, '0. GEOMETRÍA Y MATERIALES', 'tcw', 'Columna', 'cm', 'c_tw', '(co_tw_mm/10)'),
    (18, '0. GEOMETRÍA Y MATERIALES', 'tcf', 'Columna', 'cm', 'c_tf', '(co_tf_mm/10)'),
    (19, '0. GEOMETRÍA Y MATERIALES', 'Ac', 'Área de columna', 'cm²', 'c_A', '(((2*c_bf)*c_tf)+(((c_d-(2*c_tf)))*c_tw))'),
    (20, '0. GEOMETRÍA Y MATERIALES', 'kc', 'tcf + filete', 'cm', 'c_k', '(c_tf+(co_kw/10))'),
    (21, '0. GEOMETRÍA Y MATERIALES', 'bp', 'Ancho de placa', 'cm', 'p_bp', '(pl_bp/10)'),
    (22, '0. GEOMETRÍA Y MATERIALES', 'bp,ef', 'mín(bp ; bf + 2.54)', 'cm', 'p_bpe', '_min(p_bp,(b_bf+2.54))'),
    (23, '0. GEOMETRÍA Y MATERIALES', 'tp', 'Espesor', 'cm', 'p_tp', '(pl_tp/10)'),
    (24, '0. GEOMETRÍA Y MATERIALES', 'g', 'Gramil', 'cm', 'p_g', '(pl_g/10)'),
    (25, '0. GEOMETRÍA Y MATERIALES', 'pfo', 'Ala a fila exterior', 'cm', 'p_pfo', '(pl_pfo/10)'),
    (26, '0. GEOMETRÍA Y MATERIALES', 'pfi', 'Ala a primera fila interior', 'cm', 'p_pfi', '(pl_pfi/10)'),
    (27, '0. GEOMETRÍA Y MATERIALES', 'pb', 'Entre filas interiores', 'cm', 'p_pb', '(pl_pb/10)'),
    (28, '0. GEOMETRÍA Y MATERIALES', 'de', 'Fila exterior a borde', 'cm', 'p_de', '(pl_de/10)'),
    (29, '0. GEOMETRÍA Y MATERIALES', 's', '½·√(bp,ef·g)', 'cm', 'p_s', '(0.5*_sqrt((p_bpe*p_g)))'),
    (30, '0. GEOMETRÍA Y MATERIALES', 'pf,ef', 'pfi ≤ s', 'cm', 'p_pfe', '_min(p_pfi,p_s)'),
    (31, '0. GEOMETRÍA Y MATERIALES', 'h0', 'Fila exterior: dp − tfp/2 + pfo', 'cm', 'h_out', '((b_dp-(b_tfp/2))+p_pfo)'),
    (32, '0. GEOMETRÍA Y MATERIALES', 'h1', 'Primera fila interior: dp − 1.5·tfp − pfi', 'cm', 'h_i1', '((b_dp-(1.5*b_tfp))-p_pfi)'),
    (33, '0. GEOMETRÍA Y MATERIALES', 'h2', 'Segunda fila interior: h1 − pb', 'cm', 'h_i2', '(h_i1-p_pb)'),
    (34, '0. GEOMETRÍA Y MATERIALES', 'db', 'Diámetro', 'in', 'a_dbi', "_index(_cat('V',5,'V',10),_match(pn_diam,_cat('U',5,'U',10),0))"),
    (35, '0. GEOMETRÍA Y MATERIALES', 'db', 'Diámetro', 'cm', 'a_db', '(a_dbi*2.54)'),
    (36, '0. GEOMETRÍA Y MATERIALES', 'Ab', 'π·db²/4', 'cm²', 'a_Ab', '((math.pi*(a_db**2))/4)'),
    (37, '0. GEOMETRÍA Y MATERIALES', 'dh', 'Agujero estándar', 'cm', 'a_dh', '((((a_dbi+(1/16))) if ((a_dbi<1)) else ((a_dbi+(1/8))))*2.54)'),
    (38, '0. GEOMETRÍA Y MATERIALES', 'Le,min', 'Borde mínimo (J3.4)', 'cm', 'a_emin', "(_index(_cat('W',5,'W',10),_match(pn_diam,_cat('U',5,'U',10),0))*2.54)"),
    (39, '0. GEOMETRÍA Y MATERIALES', 'Pt', 'Fnt·Ab', 'kgf', 'a_Pt', '(pn_Fnt*a_Ab)'),
    (40, '0. GEOMETRÍA Y MATERIALES', 'FEXX', 'Electrodo', 'kgf/cm²', 'w_FEXX', "_index(_cat('Z',5,'Z',6),_match(sd_elec,_cat('Y',5,'Y',6),0))"),
    (42, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'ext.', '1 si el lado en tracción es extendido', '-', 'xu_E', "((1) if (_eq(cfg_u,'Extendida — 1+1 (4E)')) else (0))"),
    (43, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'γr', '1.25 al ras ; 1.00 extendida (DG16)', '-', 'xu_gr', '((1) if (_eq(xu_E,1)) else (1.25))'),
    (44, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'Σhi', 'Suma de brazos de las filas en tracción', 'cm', 'xu_Sh', "((h_i1) if (_eq(cfg_u,'Al ras — 1 fila (2 pernos)')) else ((((h_i1+h_i2)) if (_eq(cfg_u,'Al ras — 2 filas (4 pernos)')) else ((h_out+h_i1)))))"),
    (45, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φMnp', '0.75·2·Pt·Σhi (pernos sin palanca)', 'kgf·cm', 'xu_Mnp', '(((0.75*2)*a_Pt)*xu_Sh)'),
    (46, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'Yp', 'Línea de fluencia de la placa (DG16 / Tabla 6.2 para 4E)', 'cm', 'xu_Yp', "(((((p_bpe/2)*(((h_i1*(((1/p_pfe)+(1/p_s))))-0.5)))+((2/p_g)*((h_i1*((p_pfe+p_s))))))) if (_eq(cfg_u,'Al ras — 1 fila (2 pernos)')) else (((((((p_bpe/2)*((((h_i1/p_pfe)+(h_i2/p_s))-0.5)))+((2/p_g)*(((h_i1*((p_pfe+(0.75*p_pb))))+(h_i2*((p_s+(0.25*p_pb))))))))+(p_g/2))) if (_eq(cfg_u,'Al ras — 2 filas (4 pernos)')) else ((((p_bpe/2)*((((h_i1*(((1/p_pfe)+(1/p_s))))+(h_out/p_pfo))-0.5)))+((2/p_g)*((h_i1*((p_pfe+p_s))))))))))"),
    (47, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φMpl', '0.90·Fyp·Yp·tp²', 'kgf·cm', 'xu_Mpl', '(((0.9*pl_Fy)*xu_Yp)*(p_tp**2))'),
    (48, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'nb,c', 'Pernos del lado en compresión (resisten el corte)', '-', 'xu_nbc', "((2) if (_eq(cfg_d,'Al ras — 1 fila (2 pernos)')) else (((4) if (_eq(cfg_d,'Al ras — 2 filas (4 pernos)')) else (4))))"),
    (49, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'Lc,mín', 'Menor Lc de los pernos en compresión (bordes de placa y entre filas)', 'cm', 'xu_Lc', "_min(((_min((p_de-(a_dh/2)),(((p_pfo+b_tfp)+p_pfi)-a_dh))) if (_eq(cfg_d,'Extendida — 1+1 (4E)')) else (((p_pfi+b_tfp)-(a_dh/2)))),(((p_pb-a_dh)) if (_eq(cfg_d,'Al ras — 2 filas (4 pernos)')) else (1000)))"),
    (50, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Corte: 0.75·nb,c·Fnv·Ab', 'kgf', 'xu_Rv', '(((0.75*xu_nbc)*pn_Fnv)*a_Ab)'),
    (51, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Aplastamiento en placa: 0.75·nb,c·mín(1.2Lc ; 2.4db)·tp·Fu', 'kgf', 'xu_Rbp', '((((0.75*xu_nbc)*_min((1.2*xu_Lc),(2.4*a_db)))*p_tp)*pl_Fu)'),
    (52, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 's,c', '½·√(bcf·g)', 'cm', 'xu_sc', '(0.5*_sqrt((c_bf*p_g)))'),
    (53, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'c', 'pfo + tfp + pfi', 'cm', 'xu_c', '((p_pfo+b_tfp)+p_pfi)'),
    (54, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'Yc', '4E: Tabla 6.5 (sin rigidizar) / 6.6 (rigidizada)', 'cm', 'xu_Yc', "(((((c_bf/2)*(((h_i1*(((1/xu_sc)+(1/_min(xu_sc,(p_pfi+(((b_tfp-(cp_t/10)))/2)))))))+(h_out*(((1/xu_sc)+(1/_min(xu_sc,(p_pfo+(((b_tfp-(cp_t/10)))/2))))))))))+((2/p_g)*(((h_i1*((xu_sc+_min(xu_sc,(p_pfi+(((b_tfp-(cp_t/10)))/2))))))+(h_out*((xu_sc+_min(xu_sc,(p_pfo+(((b_tfp-(cp_t/10)))/2))))))))))) if (_eq(cp_usar,'Sí')) else (((((c_bf/2)*(((h_i1/xu_sc)+(h_out/xu_sc))))+((2/p_g)*((((h_i1*((xu_sc+((3*xu_c)/4))))+(h_out*((xu_sc+(xu_c/4)))))+((xu_c**2)/2)))))+(p_g/2))))"),
    (55, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φMcf', 'Ala de columna (4E): 0.90·Fyc·Yc·tcf²', 'kgf·cm', 'xu_Mcf', '(((0.9*co_Fy)*xu_Yc)*(c_tf**2))'),
    (56, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Ala de columna al ras: J10.1, 0.90·6.25·Fyc·tcf² (×0.5 si a < 10tcf del tope)', 'kgf', 'xu_Rfb', '((((0.9*6.25)*co_Fy)*(c_tf**2))*((0.5) if (((co_dtop/10)<(10*c_tf))) else (1)))'),
    (57, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Fluencia local del alma en el ala en tracción (J10.2): 1.00·(5k|2.5k + tfp + 2tp)·Fyc·tcw', 'kgf', 'xu_Rwy', '(((1*((((((5) if (((co_dtop/10)>c_d)) else (2.5))*c_k)+b_tfp)+(2*p_tp))))*co_Fy)*c_tw)'),
    (58, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'lb', 'Crippling: tfp + 2w + 2tp', 'cm', 'xu_Nc', "((b_tfp+(2*((0) if (_eq(sd_tipo,'CJP')) else ((sd_wf/10)))))+(2*p_tp))"),
    (59, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Crippling en el ala en compresión (J10.3)', 'kgf', 'xu_Rwc', '(((0.75*(((0.8*((1+((3*((xu_Nc/c_d)))*(((c_tw/c_tf))**1.5)))))) if ((((co_dtop/10)+b_dp)>=(c_d/2))) else ((0.4*(((1+((3*((xu_Nc/c_d)))*(((c_tw/c_tf))**1.5)))) if (((xu_Nc/c_d)<=0.2)) else ((1+(((((4*xu_Nc)/c_d)-0.2))*(((c_tw/c_tf))**1.5)))))))))*(c_tw**2))*_sqrt((((k_E*co_Fy)*c_tf)/c_tw)))'),
    (60, '1U. TRACCIÓN EN EL ALA SUPERIOR (Mu < 0) — configuración del lado superior', 'φRn', 'Ala de columna como fuerza equivalente (4E: φMcf,sin rigid./(dp − tfp) ; al ras: J10.1)', 'kgf', 'xu_Rcfe', '((((((0.9*co_Fy)*(((((c_bf/2)*(((h_i1/xu_sc)+(h_out/xu_sc))))+((2/p_g)*((((h_i1*((xu_sc+((3*xu_c)/4))))+(h_out*((xu_sc+(xu_c/4)))))+((xu_c**2)/2)))))+(p_g/2))))*(c_tf**2))/((b_dp-b_tfp)))) if (_eq(xu_E,1)) else (xu_Rfb))'),
    (62, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'ext.', '1 si el lado en tracción es extendido', '-', 'xd_E', "((1) if (_eq(cfg_d,'Extendida — 1+1 (4E)')) else (0))"),
    (63, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'γr', '1.25 al ras ; 1.00 extendida (DG16)', '-', 'xd_gr', '((1) if (_eq(xd_E,1)) else (1.25))'),
    (64, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'Σhi', 'Suma de brazos de las filas en tracción', 'cm', 'xd_Sh', "((h_i1) if (_eq(cfg_d,'Al ras — 1 fila (2 pernos)')) else ((((h_i1+h_i2)) if (_eq(cfg_d,'Al ras — 2 filas (4 pernos)')) else ((h_out+h_i1)))))"),
    (65, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φMnp', '0.75·2·Pt·Σhi (pernos sin palanca)', 'kgf·cm', 'xd_Mnp', '(((0.75*2)*a_Pt)*xd_Sh)'),
    (66, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'Yp', 'Línea de fluencia de la placa (DG16 / Tabla 6.2 para 4E)', 'cm', 'xd_Yp', "(((((p_bpe/2)*(((h_i1*(((1/p_pfe)+(1/p_s))))-0.5)))+((2/p_g)*((h_i1*((p_pfe+p_s))))))) if (_eq(cfg_d,'Al ras — 1 fila (2 pernos)')) else (((((((p_bpe/2)*((((h_i1/p_pfe)+(h_i2/p_s))-0.5)))+((2/p_g)*(((h_i1*((p_pfe+(0.75*p_pb))))+(h_i2*((p_s+(0.25*p_pb))))))))+(p_g/2))) if (_eq(cfg_d,'Al ras — 2 filas (4 pernos)')) else ((((p_bpe/2)*((((h_i1*(((1/p_pfe)+(1/p_s))))+(h_out/p_pfo))-0.5)))+((2/p_g)*((h_i1*((p_pfe+p_s))))))))))"),
    (67, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φMpl', '0.90·Fyp·Yp·tp²', 'kgf·cm', 'xd_Mpl', '(((0.9*pl_Fy)*xd_Yp)*(p_tp**2))'),
    (68, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'nb,c', 'Pernos del lado en compresión (resisten el corte)', '-', 'xd_nbc', "((2) if (_eq(cfg_u,'Al ras — 1 fila (2 pernos)')) else (((4) if (_eq(cfg_u,'Al ras — 2 filas (4 pernos)')) else (4))))"),
    (69, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'Lc,mín', 'Menor Lc de los pernos en compresión (bordes de placa y entre filas)', 'cm', 'xd_Lc', "_min(((_min((p_de-(a_dh/2)),(((p_pfo+b_tfp)+p_pfi)-a_dh))) if (_eq(cfg_u,'Extendida — 1+1 (4E)')) else (((p_pfi+b_tfp)-(a_dh/2)))),(((p_pb-a_dh)) if (_eq(cfg_u,'Al ras — 2 filas (4 pernos)')) else (1000)))"),
    (70, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Corte: 0.75·nb,c·Fnv·Ab', 'kgf', 'xd_Rv', '(((0.75*xd_nbc)*pn_Fnv)*a_Ab)'),
    (71, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Aplastamiento en placa: 0.75·nb,c·mín(1.2Lc ; 2.4db)·tp·Fu', 'kgf', 'xd_Rbp', '((((0.75*xd_nbc)*_min((1.2*xd_Lc),(2.4*a_db)))*p_tp)*pl_Fu)'),
    (72, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 's,c', '½·√(bcf·g)', 'cm', 'xd_sc', '(0.5*_sqrt((c_bf*p_g)))'),
    (73, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'c', 'pfo + tfp + pfi', 'cm', 'xd_c', '((p_pfo+b_tfp)+p_pfi)'),
    (74, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'Yc', '4E: Tabla 6.5 (sin rigidizar) / 6.6 (rigidizada)', 'cm', 'xd_Yc', "(((((c_bf/2)*(((h_i1*(((1/xd_sc)+(1/_min(xd_sc,(p_pfi+(((b_tfp-(cp_t/10)))/2)))))))+(h_out*(((1/xd_sc)+(1/_min(xd_sc,(p_pfo+(((b_tfp-(cp_t/10)))/2))))))))))+((2/p_g)*(((h_i1*((xd_sc+_min(xd_sc,(p_pfi+(((b_tfp-(cp_t/10)))/2))))))+(h_out*((xd_sc+_min(xd_sc,(p_pfo+(((b_tfp-(cp_t/10)))/2))))))))))) if (_eq(cp_usar,'Sí')) else (((((c_bf/2)*(((h_i1/xd_sc)+(h_out/xd_sc))))+((2/p_g)*((((h_i1*((xd_sc+((3*xd_c)/4))))+(h_out*((xd_sc+(xd_c/4)))))+((xd_c**2)/2)))))+(p_g/2))))"),
    (75, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φMcf', 'Ala de columna (4E): 0.90·Fyc·Yc·tcf²', 'kgf·cm', 'xd_Mcf', '(((0.9*co_Fy)*xd_Yc)*(c_tf**2))'),
    (76, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Ala de columna al ras: J10.1, 0.90·6.25·Fyc·tcf² (×0.5 si a < 10tcf del tope)', 'kgf', 'xd_Rfb', '((((0.9*6.25)*co_Fy)*(c_tf**2))*((0.5) if ((((co_dtop/10)+b_dp)<(10*c_tf))) else (1)))'),
    (77, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Fluencia local del alma en el ala en tracción (J10.2): 1.00·(5k|2.5k + tfp + 2tp)·Fyc·tcw', 'kgf', 'xd_Rwy', '(((1*((((((5) if ((((co_dtop/10)+b_dp)>c_d)) else (2.5))*c_k)+b_tfp)+(2*p_tp))))*co_Fy)*c_tw)'),
    (78, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'lb', 'Crippling: tfp + 2w + 2tp', 'cm', 'xd_Nc', "((b_tfp+(2*((0) if (_eq(sd_tipo,'CJP')) else ((sd_wf/10)))))+(2*p_tp))"),
    (79, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Crippling en el ala en compresión (J10.3)', 'kgf', 'xd_Rwc', '(((0.75*(((0.8*((1+((3*((xd_Nc/c_d)))*(((c_tw/c_tf))**1.5)))))) if (((co_dtop/10)>=(c_d/2))) else ((0.4*(((1+((3*((xd_Nc/c_d)))*(((c_tw/c_tf))**1.5)))) if (((xd_Nc/c_d)<=0.2)) else ((1+(((((4*xd_Nc)/c_d)-0.2))*(((c_tw/c_tf))**1.5)))))))))*(c_tw**2))*_sqrt((((k_E*co_Fy)*c_tf)/c_tw)))'),
    (80, '1D. TRACCIÓN EN EL ALA INFERIOR (Mu > 0) — configuración del lado inferior', 'φRn', 'Ala de columna como fuerza equivalente (4E: φMcf,sin rigid./(dp − tfp) ; al ras: J10.1)', 'kgf', 'xd_Rcfe', '((((((0.9*co_Fy)*(((((c_bf/2)*(((h_i1/xd_sc)+(h_out/xd_sc))))+((2/p_g)*((((h_i1*((xd_sc+((3*xd_c)/4))))+(h_out*((xd_sc+(xd_c/4)))))+((xd_c**2)/2)))))+(p_g/2))))*(c_tf**2))/((b_dp-b_tfp)))) if (_eq(xd_E,1)) else (xd_Rfb))'),
    (82, '2. RESISTENCIAS COMUNES', 'φRn', 'Extensión 4E, fluencia por corte: 1.00·0.6·Fyp·bp·tp', 'kgf', 'r_Rsy', '(((0.6*pl_Fy)*p_bp)*p_tp)'),
    (83, '2. RESISTENCIAS COMUNES', 'φRn', 'Extensión 4E, ruptura por corte: 0.75·0.6·Fup·[bp − 2(dh + 1/16 in)]·tp', 'kgf', 'r_Rsr', '((((0.75*0.6)*pl_Fu)*((p_bp-(2*((a_dh+0.15875))))))*p_tp)'),
    (84, '2. RESISTENCIAS COMUNES', 'φRn', 'Filete ala (2 lados): 0.75·0.6·FEXX·0.707w·(2bf − tw)·1.5 ; CJP: 0.90·Fy·bf·tf', 'kgf', 'r_Rwf', "(((((0.9*_min(vg_Fy,pl_Fy))*b_bf)*b_tf)) if (_eq(sd_tipo,'CJP')) else ((((((((0.75*0.6)*w_FEXX)*0.707)*sd_wf)/10)*(((2*b_bf)-b_tw)))*1.5)))"),
    (85, '2. RESISTENCIAS COMUNES', 'req.', 'Alma en zona de tracción: 0.9·Fy·tw por unidad de longitud (DG16/DG4)', 'kgf/cm', 'r_wtD', '((0.9*vg_Fy)*b_tw)'),
    (86, '2. RESISTENCIAS COMUNES', 'φRn', 'Filete alma 2 lados por unidad de longitud (θ = 90°)', 'kgf/cm', 'r_wtC', '(((((((0.75*0.6)*w_FEXX)*0.707)*sd_ww)/10)*2)*1.5)'),
    (87, '2. RESISTENCIAS COMUNES', 'φRn', 'Alma a corte: Lw = dp/2 − tfp (2 lados)', 'kgf', 'r_Rwv', '(((((((0.75*0.6)*w_FEXX)*0.707)*sd_ww)/10)*2)*(((b_dp/2)-b_tfp)))'),
    (88, '2. RESISTENCIAS COMUNES', 'φRn', 'Aplastamiento en ala de columna por perno: 0.75·2.4·db·tcf·Fuc', 'kgf', 'r_Rbc', '((((0.75*2.4)*a_db)*c_tf)*co_Fu)'),
    (89, '2. RESISTENCIAS COMUNES', 'φRn', 'Rigidizadores de continuidad: 0.90·Fyc·2·b·t', 'kgf', 'r_Rcp', '((((((0.9*co_Fy)*2)*cp_b)/10)*cp_t)/10)'),
    (90, '2. RESISTENCIAS COMUNES', 'Py', 'Fyc·Ac', 'kgf', 'r_Py', '(co_Fy*c_A)'),
    (91, '2. RESISTENCIAS COMUNES', 'φRv', 'Zona de panel J10.6(a): 0.90·0.6·Fyc·dc·(tcw + doubler)·(1 ó 1.4 − Pr/Py)', 'kgf', 'r_Rpz', '(((((0.9*0.6)*co_Fy)*c_d)*((c_tw+(dp_t/10))))*((1) if (((Pu_col*1000)<=(0.4*r_Py))) else ((1.4-((Pu_col*1000)/r_Py)))))'),
    (94, '3. VERIFICACIÓN POR COMBINACIÓN', 'Símbolo', 'Descripción', 'Unidad', 'g94', '1'),
]

COMBO = [  # (fila, sección, símbolo, descripción, unidad, expresión); IDX_ = nº de combinación
    (95, '3. VERIFICACIÓN POR COMBINACIÓN', 'Combo', 'Nombre', '', "(('') if (_eq(_index(cb_nom,IDX_),'')) else (_index(cb_nom,IDX_)))"),
    (96, '3. VERIFICACIÓN POR COMBINACIÓN', 'Mu', 'Momento (con signo)', 'kgf·cm', '(_n(_index(cb_M,IDX_))*100000)'),
    (97, '3. VERIFICACIÓN POR COMBINACIÓN', 'Vu', '|Cortante|', 'kgf', '(abs(_n(_index(cb_V,IDX_)))*1000)'),
    (98, '3. VERIFICACIÓN POR COMBINACIÓN', 'Pu', 'Axial (+ tracción)', 'kgf', '(_n(_index(cb_P,IDX_))*1000)'),
    (99, '3. VERIFICACIÓN POR COMBINACIÓN', 'activo', 'Combinación con cargas', '-', '((1) if ((((abs(r96)+r97)+abs(r98))>0)) else (0))'),
    (100, '3. VERIFICACIÓN POR COMBINACIÓN', 'arriba', '1 = tracción en el ala superior (Mu < 0)', '-', '((1) if ((r96<0)) else (0))'),
    (101, '3. VERIFICACIÓN POR COMBINACIÓN', 'Nt', 'Tracción normal a la placa (conservador): máx(0,Pu)·cosθ + |Vu|·senθ', 'kgf', '((_max(0,r98)*k_cos)+(r97*k_sin))'),
    (102, '3. VERIFICACIÓN POR COMBINACIÓN', 'Vp', 'Corte en el plano de la placa: |Vu|·cosθ + |Pu|·senθ', 'kgf', '((r97*k_cos)+(abs(r98)*k_sin))'),
    (103, '3. VERIFICACIÓN POR COMBINACIÓN', 'Meq', '|Mu| + Nt·(dp − tfp)/2 (compresión axial despreciada)', 'kgf·cm', '(abs(r96)+((r101*((b_dp-b_tfp)))/2))'),
    (104, '3. VERIFICACIÓN POR COMBINACIÓN', 'Ffu', 'Meq/(dp − tfp)', 'kgf', '(r103/((b_dp-b_tfp)))'),
    (105, '3. VERIFICACIÓN POR COMBINACIÓN', 'db,req', '√(2Meq/(π·0.75·Fnt·Σhi))', 'mm', '(_sqrt(((2*r103)/((((math.pi*0.75)*pn_Fnt)*((xu_Sh) if (_eq(r100,1)) else (xd_Sh))))))*10)'),
    (106, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'φMnp del lado en tracción', 'Tonf·m', '(((xu_Mnp) if (_eq(r100,1)) else (xd_Mnp))/100000)'),
    (107, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos a tracción: Meq/φMnp', '-', '(r103/((xu_Mnp) if (_eq(r100,1)) else (xd_Mnp)))'),
    (108, '3. VERIFICACIÓN POR COMBINACIÓN', 'Dem.', 'Placa gruesa: 1.11·γr·φMnp', 'Tonf·m', '((((1.11*((xu_gr) if (_eq(r100,1)) else (xd_gr)))*((xu_Mnp) if (_eq(r100,1)) else (xd_Mnp)))*r99)/100000)'),
    (109, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'φMpl de la placa', 'Tonf·m', '(((xu_Mpl) if (_eq(r100,1)) else (xd_Mpl))/100000)'),
    (110, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Flexión de placa', '-', '(r108/r109)'),
    (111, '3. VERIFICACIÓN POR COMBINACIÓN', 'tp,req', '√(1.11γrφMnp/(0.9·Fyp·Yp))', 'mm', '(_sqrt(((r108*100000)/(((0.9*pl_Fy)*((xu_Yp) if (_eq(r100,1)) else (xd_Yp))))))*10)'),
    (112, '3. VERIFICACIÓN POR COMBINACIÓN', 'ext.', 'Lado en tracción extendido', '-', '((xu_E) if (_eq(r100,1)) else (xd_E))'),
    (113, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Extensión: fluencia por corte (Ffu/2)', '-', '((((r104/2)/r_Rsy)) if (_eq(r112,1)) else (0))'),
    (114, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Extensión: ruptura por corte (Ffu/2)', '-', '((((r104/2)/r_Rsr)) if (_eq(r112,1)) else (0))'),
    (115, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'Corte en pernos', 'Tonf', '(((xu_Rv) if (_eq(r100,1)) else (xd_Rv))/1000)'),
    (116, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Corte en pernos del lado en compresión', '-', '((r102/1000)/r115)'),
    (117, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'Aplastamiento placa', 'Tonf', '(((xu_Rbp) if (_eq(r100,1)) else (xd_Rbp))/1000)'),
    (118, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Aplastamiento en placa', '-', '((r102/1000)/r117)'),
    (119, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'Aplastamiento ala de columna (rodilla) o placa gemela (cumbrera)', 'Tonf', '((((((xu_nbc) if (_eq(r100,1)) else (xd_nbc))*r_Rbc)) if (_eq(t_rod,1)) else (((xu_Rbp) if (_eq(r100,1)) else (xd_Rbp))))/1000)'),
    (120, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Aplastamiento en el elemento de soporte', '-', '((r102/1000)/r119)'),
    (121, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Soldadura ala – placa', '-', '(r104/r_Rwf)'),
    (122, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Soldadura alma, zona de tracción', '-', '((r99*r_wtD)/r_wtC)'),
    (123, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Soldadura alma a corte', '-', '(r102/r_Rwv)'),
    (124, '3. VERIFICACIÓN POR COMBINACIÓN', 'Dem.', 'Ala de columna: 4E → 1.11·φMnp (Tonf·m) ; al ras → Ffu (Tonf)', '', '(((((1.11*((xu_Mnp) if (_eq(r100,1)) else (xd_Mnp)))*r99)/100000)) if (_eq(r112,1)) else ((r104/1000)))'),
    (125, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'Ala de columna: 4E → φMcf ; al ras → φRn J10.1', '', '(((((xu_Mcf) if (_eq(r100,1)) else (xd_Mcf))/100000)) if (_eq(r112,1)) else ((((xu_Rfb) if (_eq(r100,1)) else (xd_Rfb))/1000)))'),
    (126, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Flexión del ala de columna (solo rodilla)', '-', "((0) if (_eq(t_rod,0)) else (((0) if (_and(_eq(r112,0),_eq(cp_usar,'Sí'))) else ((r124/r125)))))"),
    (127, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'φRn fluencia local del alma', 'Tonf', '(((xu_Rwy) if (_eq(r100,1)) else (xd_Rwy))/1000)'),
    (128, '3. VERIFICACIÓN POR COMBINACIÓN', 'Cap.', 'φRn crippling', 'Tonf', '(((xu_Rwc) if (_eq(r100,1)) else (xd_Rwc))/1000)'),
    (129, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Fluencia local del alma (rodilla, sin rigidizadores)', '-', "((0) if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((r104/((xu_Rwy) if (_eq(r100,1)) else (xd_Rwy)))))"),
    (130, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Crippling del alma (rodilla, sin rigidizadores)', '-', "((0) if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((r104/((xu_Rwc) if (_eq(r100,1)) else (xd_Rwc)))))"),
    (131, '3. VERIFICACIÓN POR COMBINACIÓN', 'Fsu', 'Ffu − mín(ala, fluencia, crippling)', 'kgf', '_max(0,(r104-_min(((xu_Rcfe) if (_eq(r100,1)) else (xd_Rcfe)),((xu_Rwy) if (_eq(r100,1)) else (xd_Rwy)),((xu_Rwc) if (_eq(r100,1)) else (xd_Rwc)))))'),
    (132, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Rigidizadores de continuidad', '-', "(((r131/r_Rcp)) if (_and(_eq(t_rod,1),_eq(cp_usar,'Sí'))) else (0))"),
    (133, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Zona de panel (rodilla)', '-', '(((r104/r_Rpz)) if (_eq(t_rod,1)) else (0))'),
    (134, '3. VERIFICACIÓN POR COMBINACIÓN', 'máx.', 'Ratio máximo', '-', '_max(r107,r110,r113,r114,r116,r118,r120,r121,r122,r123,r126,r129,r130,r132,r133)'),
]

RATIO_COL = 'S'  # columna de ratio de la tabla de verificaciones
DEM_COL, CAP_COL = 'P', 'Q'
CHECKS = [  # (fila, tipo, nombre, referencia, unidad, demanda, capacidad, ratio, combo)
    (11, 'GRUPO', 'PLACA EXTREMA Y PERNOS', '', '', None, None, None, None),
    (12, 'CHEQUEO', 'Pernos a tracción (sin efecto palanca)', 'DG16 / DG4', 'Tonf·m', '(_index(_row(103),_match(_max(_row(107)),_row(107),0))/100000)', '(_index(_row(106),_match(_max(_row(107)),_row(107),0))/1)', '_max(_row(107))', "((_index(_row(95),_match(_max(_row(107)),_row(107),0))) if (_isnum(DIS_S12)) else ('—'))"),
    (13, 'CHEQUEO', 'Flexión de placa (placa gruesa, γr)', 'DG16 / DG4 · Yp', 'Tonf·m', '(_index(_row(108),_match(_max(_row(110)),_row(110),0))/1)', '(_index(_row(109),_match(_max(_row(110)),_row(110),0))/1)', '_max(_row(110))', "((_index(_row(95),_match(_max(_row(110)),_row(110),0))) if (_isnum(DIS_S13)) else ('—'))"),
    (14, 'CHEQUEO', 'Extensión — fluencia por corte', 'DG4 · J4.2(a)', 'Tonf', "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((_index(_row(104),_match(_max(_row(113)),_row(113),0))/2000)))", "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((r_Rsy/1000)))", "(('N/A') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (_max(_row(113))))", "((_index(_row(95),_match(_max(_row(113)),_row(113),0))) if (_isnum(DIS_S14)) else ('—'))"),
    (15, 'CHEQUEO', 'Extensión — ruptura por corte', 'DG4 · J4.2(b)', 'Tonf', "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((_index(_row(104),_match(_max(_row(114)),_row(114),0))/2000)))", "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((r_Rsr/1000)))", "(('N/A') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (_max(_row(114))))", "((_index(_row(95),_match(_max(_row(114)),_row(114),0))) if (_isnum(DIS_S15)) else ('—'))"),
    (16, 'CHEQUEO', 'Corte en pernos (lado en compresión)', 'J3.6', 'Tonf', '(_index(_row(102),_match(_max(_row(116)),_row(116),0))/1000)', '(_index(_row(115),_match(_max(_row(116)),_row(116),0))/1)', '_max(_row(116))', "((_index(_row(95),_match(_max(_row(116)),_row(116),0))) if (_isnum(DIS_S16)) else ('—'))"),
    (17, 'CHEQUEO', 'Aplastamiento / desgarre — placa', 'J3.10', 'Tonf', '(_index(_row(102),_match(_max(_row(118)),_row(118),0))/1000)', '(_index(_row(117),_match(_max(_row(118)),_row(118),0))/1)', '_max(_row(118))', "((_index(_row(95),_match(_max(_row(118)),_row(118),0))) if (_isnum(DIS_S17)) else ('—'))"),
    (18, 'CHEQUEO', 'Aplastamiento — ala de columna / placa gemela', 'J3.10', 'Tonf', '(_index(_row(102),_match(_max(_row(120)),_row(120),0))/1000)', '(_index(_row(119),_match(_max(_row(120)),_row(120),0))/1)', '_max(_row(120))', "((_index(_row(95),_match(_max(_row(120)),_row(120),0))) if (_isnum(DIS_S18)) else ('—'))"),
    (19, 'GRUPO', 'SOLDADURAS VIGA – PLACA', '', '', None, None, None, None),
    (20, 'CHEQUEO', 'Ala – placa (filete o CJP)', 'J2.4 / J2.1', 'Tonf', '(_index(_row(104),_match(_max(_row(121)),_row(121),0))/1000)', '(r_Rwf/1000)', '_max(_row(121))', "((_index(_row(95),_match(_max(_row(121)),_row(121),0))) if (_isnum(DIS_S20)) else ('—'))"),
    (21, 'CHEQUEO', 'Alma – zona de tracción (desarrollar Fy)', 'DG16 / DG4', 'kgf/cm', 'r_wtD', 'r_wtC', '_max(_row(122))', "((_index(_row(95),_match(_max(_row(122)),_row(122),0))) if (_isnum(DIS_S21)) else ('—'))"),
    (22, 'CHEQUEO', 'Alma – corte', 'J2.4', 'Tonf', '(_index(_row(102),_match(_max(_row(123)),_row(123),0))/1000)', '(r_Rwv/1000)', '_max(_row(123))', "((_index(_row(95),_match(_max(_row(123)),_row(123),0))) if (_isnum(DIS_S22)) else ('—'))"),
    (23, 'GRUPO', 'COLUMNA (solo rodilla)', '', '', None, None, None, None),
    (24, 'CHEQUEO', 'Flexión del ala de columna', '4E: Tabla 6.5/6.6 · al ras: J10.1', 'T·m | T', "(('—') if (_or(_eq(t_rod,0),_and(_eq(cp_usar,'Sí'),(not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)'))))) else ((_index(_row(124),_match(_max(_row(126)),_row(126),0))/1)))", "(('—') if (_or(_eq(t_rod,0),_and(_eq(cp_usar,'Sí'),(not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)'))))) else ((_index(_row(125),_match(_max(_row(126)),_row(126),0))/1)))", "(('N/A') if (_or(_eq(t_rod,0),_and(_eq(cp_usar,'Sí'),(not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)'))))) else (_max(_row(126))))", "((_index(_row(95),_match(_max(_row(126)),_row(126),0))) if (_isnum(DIS_S24)) else ('—'))"),
    (25, 'CHEQUEO', 'Fluencia local del alma', 'J10.2', 'Tonf', "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((_index(_row(104),_match(_max(_row(129)),_row(129),0))/1000)))", "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((_index(_row(127),_match(_max(_row(129)),_row(129),0))/1)))", "(('N/A') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else (_max(_row(129))))", "((_index(_row(95),_match(_max(_row(129)),_row(129),0))) if (_isnum(DIS_S25)) else ('—'))"),
    (26, 'CHEQUEO', 'Aplastamiento del alma (crippling)', 'J10.3', 'Tonf', "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((_index(_row(104),_match(_max(_row(130)),_row(130),0))/1000)))", "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else ((_index(_row(128),_match(_max(_row(130)),_row(130),0))/1)))", "(('N/A') if (_or(_eq(t_rod,0),_eq(cp_usar,'Sí'))) else (_max(_row(130))))", "((_index(_row(95),_match(_max(_row(130)),_row(130),0))) if (_isnum(DIS_S26)) else ('—'))"),
    (27, 'CHEQUEO', 'Rigidizadores de continuidad', 'J10.8', 'Tonf', "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((_index(_row(131),_match(_max(_row(132)),_row(132),0))/1000)))", "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((r_Rcp/1000)))", "(('N/A') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else (_max(_row(132))))", "((_index(_row(95),_match(_max(_row(132)),_row(132),0))) if (_isnum(DIS_S27)) else ('—'))"),
    (28, 'CHEQUEO', 'Zona de panel (corte)', 'J10.6(a)', 'Tonf', "(('—') if (_eq(t_rod,0)) else ((_index(_row(104),_match(_max(_row(133)),_row(133),0))/1000)))", "(('—') if (_eq(t_rod,0)) else ((r_Rpz/1000)))", "(('N/A') if (_eq(t_rod,0)) else (_max(_row(133))))", "((_index(_row(95),_match(_max(_row(133)),_row(133),0))) if (_isnum(DIS_S28)) else ('—'))"),
    (29, 'GRUPO', 'GEOMETRÍA Y DETALLES (requerido / provisto)', '', '', None, None, None, None),
    (30, 'CHEQUEO', 'Ancho de placa bp ≥ bf', 'DG4 / DG16', 'cm', 'b_bf', 'p_bp', '((b_bf)/_max(p_bp,1e-09))', "'—'"),
    (31, 'CHEQUEO', 'Holgura de llave pfi ≥ db + 12.7 mm', 'DG16', 'cm', '(a_db+1.27)', 'p_pfi', '(((a_db+1.27))/_max(p_pfi,1e-09))', "'—'"),
    (32, 'CHEQUEO', 'Holgura de llave pfo ≥ db + 12.7 mm', 'DG16', 'cm', "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((a_db+1.27)))", "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (p_pfo))", "(('N/A') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else ((((a_db+1.27))/_max(p_pfo,1e-09))))", "'—'"),
    (33, 'CHEQUEO', 'Borde de ≥ mínimo', 'J3.4', 'cm', "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (a_emin))", "(('—') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (p_de))", "(('N/A') if (_and((not _eq(cfg_u,'Extendida — 1+1 (4E)')),(not _eq(cfg_d,'Extendida — 1+1 (4E)')))) else (((a_emin)/_max(p_de,1e-09))))", "'—'"),
    (34, 'CHEQUEO', 'Borde lateral (bp − g)/2 ≥ mínimo', 'J3.4', 'cm', 'a_emin', '(((p_bp-p_g))/2)', '((a_emin)/_max((((p_bp-p_g))/2),1e-09))', "'—'"),
    (35, 'CHEQUEO', 'Gramil g ≥ 2⅔·db', 'J3.3', 'cm', '((8/3)*a_db)', 'p_g', '((((8/3)*a_db))/_max(p_g,1e-09))', "'—'"),
    (36, 'CHEQUEO', 'Paso pb ≥ 2⅔·db', 'J3.3', 'cm', "(('—') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else (((8/3)*a_db)))", "(('—') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else (p_pb))", "(('N/A') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else (((((8/3)*a_db))/_max(p_pb,1e-09))))", "'—'"),
    (37, 'CHEQUEO', 'Segunda fila interior dentro del alma (h2 > dp/2)', 'Geometría', 'cm', "(('—') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else ((b_dp/2)))", "(('—') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else (h_i2))", "(('N/A') if (_and((not _eq(cfg_u,'Al ras — 2 filas (4 pernos)')),(not _eq(cfg_d,'Al ras — 2 filas (4 pernos)')))) else ((((b_dp/2))/_max(h_i2,1e-09))))", "'—'"),
    (38, 'CHEQUEO', 'Filete mínimo ala', 'Tabla J2.4', 'mm', "(('—') if (_eq(sd_tipo,'CJP')) else (((3) if ((_min(vg_tf_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tf_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tf_mm,pl_tp)<=19)) else (8))))))))", "(('—') if (_eq(sd_tipo,'CJP')) else (sd_wf))", "(('N/A') if (_eq(sd_tipo,'CJP')) else (((((3) if ((_min(vg_tf_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tf_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tf_mm,pl_tp)<=19)) else (8)))))))/_max(sd_wf,1e-09))))", "'—'"),
    (39, 'CHEQUEO', 'Filete mínimo alma', 'Tabla J2.4', 'mm', '((3) if ((_min(vg_tw_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tw_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tw_mm,pl_tp)<=19)) else (8))))))', 'sd_ww', '((((3) if ((_min(vg_tw_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tw_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tw_mm,pl_tp)<=19)) else (8)))))))/_max(sd_ww,1e-09))', "'—'"),
    (40, 'CHEQUEO', 'Rigid. continuidad: b + tcw/2 ≥ bf/3', 'J10.8', 'cm', "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else (((b_bf/3)-(c_tw/2))))", "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((cp_b/10)))", "(('N/A') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else (((((b_bf/3)-(c_tw/2)))/_max((cp_b/10),1e-09))))", "'—'"),
    (41, 'CHEQUEO', 'Rigid. continuidad: t ≥ tf/2', 'J10.8', 'cm', "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((b_tf/2)))", "(('—') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((cp_t/10)))", "(('N/A') if (_or(_eq(t_rod,0),_eq(cp_usar,'No'))) else ((((b_tf/2))/_max((cp_t/10),1e-09))))", "'—'"),
    (42, 'CHEQUEO', 'Placa dentro del ala de columna: bp ≤ bcf', 'Geometría', 'cm', "(('—') if (_eq(t_rod,0)) else (p_bp))", "(('—') if (_eq(t_rod,0)) else (c_bf))", "(('N/A') if (_eq(t_rod,0)) else (((p_bp)/_max(c_bf,1e-09))))", "'—'"),
    (43, 'CHEQUEO', 'Pendiente θ ≤ 30° (validez de la proyección)', 'Criterio', '°', 'theta', '30', '((theta)/_max(30,1e-09))', "'—'"),
    (44, 'CHEQUEO', 'Alma de viga: tw ≥ tmín para el filete del alma', 'Manual Ec. 9-2', 'cm', '((((0.707*sd_ww)/10)*w_FEXX)/vg_Fu)', 'b_tw', '((((((0.707*sd_ww)/10)*w_FEXX)/vg_Fu))/_max(b_tw,1e-09))', "'—'"),
]
