"""Modelo generado por tools/xl2py.py — NO editar a mano (regenerar desde la hoja de Excel)."""

NCOMBO = 10

DERIVED = [  # (fila, nombre, etiqueta, unidad, expresión)  — fórmulas de la hoja DISEÑO
    (15, 'vg_d_mm', 'Peralte d', 'mm', "((DIS_E15) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (16, 'vg_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E16) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (17, 'vg_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E17) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (18, 'vg_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E18) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (20, 'vg_Fy', 'Fy', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(vg_acero,_cat('M',5,'M',10),0))"),
    (21, 'vg_Fu', 'Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(vg_acero,_cat('M',5,'M',10),0))"),
    (22, 'vg_Ry', 'Ry (AISC 341)', '', "_index(_cat('P',5,'P',10),_match(vg_acero,_cat('M',5,'M',10),0))"),
    (25, 'co_d_mm', 'Peralte d', 'mm', "((DIS_E25) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('H',5,'H',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (26, 'co_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E26) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('I',5,'I',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (27, 'co_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E27) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('J',5,'J',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (28, 'co_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E28) if (_eq(co_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('K',5,'K',40),_match(co_perfil,_cat('G',5,'G',40),0))))"),
    (30, 'co_Fy', 'Fy', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(co_acero,_cat('M',5,'M',10),0))"),
    (31, 'co_Fu', 'Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(co_acero,_cat('M',5,'M',10),0))"),
    (42, 'pl_Fy', 'Fy', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(pl_acero,_cat('M',5,'M',10),0))"),
    (43, 'pl_Fu', 'Fu', 'kgf/cm²', "_index(_cat('O',5,'O',10),_match(pl_acero,_cat('M',5,'M',10),0))"),
    (53, 'pn_Fnt', 'Fnt', 'kgf/cm²', "_index(_cat('S',5,'S',8),_match(pn_grado,_cat('R',5,'R',8),0))"),
    (54, 'pn_Fnv', 'Fnv', 'kgf/cm²', "_index(_cat('T',5,'T',8),_match(pn_grado,_cat('R',5,'R',8),0))"),
    (59, 'st_Fy', 'Fys', 'kgf/cm²', "_index(_cat('N',5,'N',10),_match(st_acero,_cat('M',5,'M',10),0))"),
]

GLOBAL = [  # (fila, sección, símbolo, descripción, unidad, nombre, expresión)  — hoja CALCULO
    (5, '1. GEOMETRÍA Y MATERIALES', 'sísmico', '1 = procedimiento sísmico AISC 358-16', '-', 'k_seis', "((1) if (_eq(_s(modo)[:int(3)],'Sís')) else (0))"),
    (6, '1. GEOMETRÍA Y MATERIALES', '8ES', '1 = configuración de 8 pernos', '-', 'k_is8', "((1) if (_eq(cfg,'8ES')) else (0))"),
    (7, '1. GEOMETRÍA Y MATERIALES', '4E', '1 = 4E sin rigidizar', '-', 'k_is4E', "((1) if (_eq(cfg,'4E')) else (0))"),
    (8, '1. GEOMETRÍA Y MATERIALES', 'E', 'Módulo de elasticidad', 'kgf/cm²', 'k_E', '2040000'),
    (9, '1. GEOMETRÍA Y MATERIALES', 'd', 'Peralte de viga', 'cm', 'k_d', '(vg_d_mm/10)'),
    (10, '1. GEOMETRÍA Y MATERIALES', 'bbf', 'Ancho de ala de viga', 'cm', 'k_bf', '(vg_bf_mm/10)'),
    (11, '1. GEOMETRÍA Y MATERIALES', 'tbw', 'Alma de viga', 'cm', 'k_tw', '(vg_tw_mm/10)'),
    (12, '1. GEOMETRÍA Y MATERIALES', 'tbf', 'Ala de viga', 'cm', 'k_tf', '(vg_tf_mm/10)'),
    (13, '1. GEOMETRÍA Y MATERIALES', 'Zx', 'bf·tf·(d−tf) + tw·(d−2tf)²/4', 'cm³', 'k_Zx', '(((k_bf*k_tf)*((k_d-k_tf)))+((k_tw*(((k_d-(2*k_tf)))**2))/4))'),
    (14, '1. GEOMETRÍA Y MATERIALES', 'dc', 'Peralte de columna', 'cm', 'k_cd', '(co_d_mm/10)'),
    (15, '1. GEOMETRÍA Y MATERIALES', 'bcf', 'Ancho de ala de columna', 'cm', 'k_cbf', '(co_bf_mm/10)'),
    (16, '1. GEOMETRÍA Y MATERIALES', 'tcw', 'Alma de columna', 'cm', 'k_ctw', '(co_tw_mm/10)'),
    (17, '1. GEOMETRÍA Y MATERIALES', 'tcf', 'Ala de columna', 'cm', 'k_ctf', '(co_tf_mm/10)'),
    (18, '1. GEOMETRÍA Y MATERIALES', 'Ac', 'Área de columna', 'cm²', 'k_cA', '(((2*k_cbf)*k_ctf)+(((k_cd-(2*k_ctf)))*k_ctw))'),
    (19, '1. GEOMETRÍA Y MATERIALES', 'kc', 'tcf + filete', 'cm', 'k_ck', '(k_ctf+(co_kw/10))'),
    (20, '1. GEOMETRÍA Y MATERIALES', 'h', 'dc − 2kc (alma libre)', 'cm', 'k_ch', '(k_cd-(2*k_ck))'),
    (21, '1. GEOMETRÍA Y MATERIALES', 'bp', 'Ancho de placa', 'cm', 'k_bp', '(pl_bp/10)'),
    (22, '1. GEOMETRÍA Y MATERIALES', 'bp,ef', 'mín(bp ; bbf + 2.54) para líneas de fluencia', 'cm', 'k_bpe', '_min(k_bp,(k_bf+2.54))'),
    (23, '1. GEOMETRÍA Y MATERIALES', 'tp', 'Espesor de placa', 'cm', 'k_tp', '(pl_tp/10)'),
    (24, '1. GEOMETRÍA Y MATERIALES', 'g', 'Gramil', 'cm', 'k_g', '(pl_g/10)'),
    (25, '1. GEOMETRÍA Y MATERIALES', 'pfo', 'Ala a fila exterior', 'cm', 'k_pfo', '(pl_pfo/10)'),
    (26, '1. GEOMETRÍA Y MATERIALES', 'pfi', 'Ala a fila interior', 'cm', 'k_pfi', '(pl_pfi/10)'),
    (27, '1. GEOMETRÍA Y MATERIALES', 'pb', 'Entre filas (8ES; 0 en 4E/4ES)', 'cm', 'k_pb', '(((pl_pb/10)) if (_eq(k_is8,1)) else (0))'),
    (28, '1. GEOMETRÍA Y MATERIALES', 'de', 'Fila exterior a borde', 'cm', 'k_de', '(pl_de/10)'),
    (29, '1. GEOMETRÍA Y MATERIALES', 'Hp', 'Alto de placa: d + 2(pfo + pb + de)', 'cm', 'k_Hp', '(k_d+(2*(((k_pfo+k_pb)+k_de))))'),
    (30, '1. GEOMETRÍA Y MATERIALES', 'db', 'Diámetro de perno', 'in', 'k_dbi', "_index(_cat('W',5,'W',12),_match(pn_diam,_cat('V',5,'V',12),0))"),
    (31, '1. GEOMETRÍA Y MATERIALES', 'db', 'Diámetro de perno', 'cm', 'k_db', '(k_dbi*2.54)'),
    (32, '1. GEOMETRÍA Y MATERIALES', 'Ab', 'π·db²/4', 'cm²', 'k_Ab', '((math.pi*(k_db**2))/4)'),
    (33, '1. GEOMETRÍA Y MATERIALES', 'dh', 'Agujero estándar (Tabla J3.3): db + 1/16 in (db < 1 in) ; db + 1/8 in', 'cm', 'k_dh', '((((k_dbi+(1/16))) if ((k_dbi<1)) else ((k_dbi+(1/8))))*2.54)'),
    (34, '1. GEOMETRÍA Y MATERIALES', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'k_emin', "(_index(_cat('X',5,'X',12),_match(pn_diam,_cat('V',5,'V',12),0))*2.54)"),
    (35, '1. GEOMETRÍA Y MATERIALES', 'nb', 'Pernos en el lado de compresión (resisten corte)', '-', 'k_nb', '((8) if (_eq(k_is8,1)) else (4))'),
    (37, '2. DISTANCIAS DESDE EL CENTRO DEL ALA EN COMPRESIÓN (DG4 / AISC 358 Fig. 6.2)', 'h0 | h1', '4E/4ES: h0 = d − tbf/2 + pfo ; 8ES: h1 = d − tbf/2 + pfo + pb', 'cm', 'k_r1', '(((k_d-(k_tf/2))+k_pfo)+k_pb)'),
    (38, '2. DISTANCIAS DESDE EL CENTRO DEL ALA EN COMPRESIÓN (DG4 / AISC 358 Fig. 6.2)', 'h1 | h2', '4E/4ES: h1 = d − 1.5tbf − pfi ; 8ES: h2 = d − tbf/2 + pfo', 'cm', 'k_r2', '((((k_d-(k_tf/2))+k_pfo)) if (_eq(k_is8,1)) else (((k_d-(1.5*k_tf))-k_pfi)))'),
    (39, '2. DISTANCIAS DESDE EL CENTRO DEL ALA EN COMPRESIÓN (DG4 / AISC 358 Fig. 6.2)', '— | h3', '8ES: h3 = d − 1.5tbf − pfi', 'cm', 'k_r3', '((((k_d-(1.5*k_tf))-k_pfi)) if (_eq(k_is8,1)) else (0))'),
    (40, '2. DISTANCIAS DESDE EL CENTRO DEL ALA EN COMPRESIÓN (DG4 / AISC 358 Fig. 6.2)', '— | h4', '8ES: h4 = h3 − pb', 'cm', 'k_r4', '(((k_r3-k_pb)) if (_eq(k_is8,1)) else (0))'),
    (41, '2. DISTANCIAS DESDE EL CENTRO DEL ALA EN COMPRESIÓN (DG4 / AISC 358 Fig. 6.2)', 'Σhi', 'Suma de brazos de las filas en tracción', 'cm', 'k_sh', '(((k_r1+k_r2)+k_r3)+k_r4)'),
    (43, '3. PERNOS Y PLACA EXTREMA', 'Pt', 'Fnt·Ab (tracción nominal por perno)', 'kgf', 'k_Pt', '(pn_Fnt*k_Ab)'),
    (44, '3. PERNOS Y PLACA EXTREMA', 'Mnp', '2·Pt·Σhi (sin palanca)', 'kgf·cm', 'k_Mnp', '((2*k_Pt)*k_sh)'),
    (45, '3. PERNOS Y PLACA EXTREMA', 'φn', 'Pernos, ruptura: 0.75 (AISC 360) | 0.90 (AISC 358)', '-', 'k_phin', '((0.9) if (_eq(k_seis,1)) else (0.75))'),
    (46, '3. PERNOS Y PLACA EXTREMA', 'φ fluencia', 'Flexión de placa/ala: 0.90 (AISC 360) | 1.00 (AISC 358)', '-', 'k_phiy', '((1) if (_eq(k_seis,1)) else (0.9))'),
    (47, '3. PERNOS Y PLACA EXTREMA', 's', '½·√(bp,ef·g)', 'cm', 'k_s', '(0.5*_sqrt((k_bpe*k_g)))'),
    (48, '3. PERNOS Y PLACA EXTREMA', 'pfi,ef', 'pfi ≤ s (nota de Tabla 6.2)', 'cm', 'k_pfie', '_min(k_pfi,k_s)'),
    (49, '3. PERNOS Y PLACA EXTREMA', 'Yp', 'Línea de fluencia de la placa (Tabla 6.2; casos de ≤ s / de > s en 4ES y 8ES)', 'cm', 'k_Yp', "(((((k_bpe/2)*((((k_r2*(((1/k_pfie)+(1/k_s))))+(k_r1*((1/k_pfo))))-0.5)))+((2/k_g)*((k_r2*((k_pfie+k_s))))))) if (_eq(cfg,'4E')) else ((((((((k_bpe/2)*(((k_r2*(((1/k_pfie)+(1/k_s))))+(k_r1*(((1/k_pfo)+(1/((2*k_de)))))))))+((2/k_g)*(((k_r2*((k_pfie+k_s)))+(k_r1*((k_de+k_pfo)))))))) if ((k_de<=k_s)) else ((((k_bpe/2)*(((k_r2*(((1/k_pfie)+(1/k_s))))+(k_r1*(((1/k_s)+(1/k_pfo)))))))+((2/k_g)*(((k_r2*((k_pfie+k_s)))+(k_r1*((k_s+k_pfo)))))))))) if (_eq(cfg,'4ES')) else (((((((k_bpe/2)*(((((k_r1/((2*k_de)))+(k_r2/k_pfo))+(k_r3/k_pfie))+(k_r4/k_s))))+((2/k_g)*((((((k_r1*((k_de+(k_pb/4))))+(k_r2*((k_pfo+((3*k_pb)/4)))))+(k_r3*((k_pfie+(k_pb/4)))))+(k_r4*((k_s+((3*k_pb)/4)))))+(k_pb**2)))))+k_g)) if ((k_de<=k_s)) else (((((k_bpe/2)*(((((k_r1/k_s)+(k_r2/k_pfo))+(k_r3/k_pfie))+(k_r4/k_s))))+((2/k_g)*((((((k_r1*((k_s+(k_pb/4))))+(k_r2*((k_pfo+((3*k_pb)/4)))))+(k_r3*((k_pfie+(k_pb/4)))))+(k_r4*((k_s+((3*k_pb)/4)))))+(k_pb**2)))))+k_g)))))))"),
    (50, '3. PERNOS Y PLACA EXTREMA', 'φMpl', 'φ·Fyp·Yp·tp²', 'kgf·cm', 'k_phiMpl', '(((k_phiy*pl_Fy)*k_Yp)*(k_tp**2))'),
    (51, '3. PERNOS Y PLACA EXTREMA', 'An', 'Extensión 4E: [bp − 2(dh + 1/16 in)]·tp', 'cm²', 'k_An', '(((k_bp-(2*((k_dh+0.15875)))))*k_tp)'),
    (52, '3. PERNOS Y PLACA EXTREMA', 'φRn', 'Extensión 4E, fluencia por corte: 1.00·0.6·Fyp·bp·tp (J4.2a)', 'kgf', 'k_Rsy', '((((1*0.6)*pl_Fy)*k_bp)*k_tp)'),
    (53, '3. PERNOS Y PLACA EXTREMA', 'φRn', 'Extensión 4E, ruptura por corte: φn·0.6·Fup·An (J4.2b)', 'kgf', 'k_Rsr', '(((k_phin*0.6)*pl_Fu)*k_An)'),
    (54, '3. PERNOS Y PLACA EXTREMA', 'φRn', 'Corte en pernos del lado de compresión: φn·nb·Fnv·Ab (J3.6)', 'kgf', 'k_Rvb', '(((k_phin*k_nb)*pn_Fnv)*k_Ab)'),
    (55, '3. PERNOS Y PLACA EXTREMA', 'Lc,o', 'Pernos exteriores: mín(de − dh/2 ; pb − dh)', 'cm', 'k_Lco', '_min((k_de-(k_dh/2)),(((k_pb-k_dh)) if (_eq(k_is8,1)) else (1000)))'),
    (56, '3. PERNOS Y PLACA EXTREMA', 'Lc,i', 'Pernos interiores: mín(pfo + tbf + pfi − dh ; pb − dh)', 'cm', 'k_Lci', '_min((((k_pfo+k_tf)+k_pfi)-k_dh),(((k_pb-k_dh)) if (_eq(k_is8,1)) else (1000)))'),
    (57, '3. PERNOS Y PLACA EXTREMA', 'φRn', 'Aplastamiento/desgarre en placa: φn·nb/2·(rn,i + rn,o), rn = mín(1.2Lc·t·Fu ; 2.4db·t·Fu)', 'kgf', 'k_Rbp', '(((((k_phin*k_nb)/2)*((_min((1.2*k_Lci),(2.4*k_db))+_min((1.2*k_Lco),(2.4*k_db)))))*k_tp)*pl_Fu)'),
    (58, '3. PERNOS Y PLACA EXTREMA', 'φRn', 'Aplastamiento/desgarre en ala de columna (sin borde libre exterior)', 'kgf', 'k_Rbc', '(((((k_phin*k_nb)/2)*((_min((1.2*k_Lci),(2.4*k_db))+_min((1.2*(((k_pb-k_dh)) if (_eq(k_is8,1)) else (1000))),(2.4*k_db)))))*k_ctf)*co_Fu)'),
    (59, '3. PERNOS Y PLACA EXTREMA', 'hst', 'Altura del rigidizador de placa = pfo + pb + de', 'cm', 'k_hst', '((k_pfo+k_pb)+k_de)'),
    (60, '3. PERNOS Y PLACA EXTREMA', 'Lst', 'Largo del rigidizador = hst/tan30°', 'cm', 'k_Lst', '(k_hst/math.tan(math.radians(30)))'),
    (61, '3. PERNOS Y PLACA EXTREMA', 'ts,req', 'tbw·Fyb/Fys (AISC 358 §6.8)', 'cm', 'k_tsr', '((k_tw*vg_Fy)/st_Fy)'),
    (62, '3. PERNOS Y PLACA EXTREMA', 'λ', 'hst/ts', '-', 'k_hts', '(k_hst/((st_t/10)))'),
    (63, '3. PERNOS Y PLACA EXTREMA', 'λlím', '0.56·√(E/Fys)', '-', 'k_htsl', '(0.56*_sqrt((k_E/st_Fy)))'),
    (65, '4. SOLDADURAS — AISC 360-16 J2.4', 'FEXX', 'Electrodo', 'kgf/cm²', 'k_FEXX', "_index(_cat('AA',5,'AA',6),_match(sd_elec,_cat('Z',5,'Z',6),0))"),
    (66, '4. SOLDADURAS — AISC 360-16 J2.4', 'φRn', 'Filete ala (2 lados): 0.75·0.6·FEXX·0.707w·(2bbf − tbw)·1.5', 'kgf', 'k_Rwf', '(((((((0.75*0.6)*k_FEXX)*0.707)*sd_wf)/10)*(((2*k_bf)-k_tw)))*1.5)'),
    (67, '4. SOLDADURAS — AISC 360-16 J2.4', 'req.', 'Alma zona de tracción: desarrollar 0.9·Fyb·tbw por unidad de longitud (DG4)', 'kgf/cm', 'k_wtD', '((0.9*vg_Fy)*k_tw)'),
    (68, '4. SOLDADURAS — AISC 360-16 J2.4', 'φRn', 'Filete alma 2 lados por unidad de longitud: 0.75·0.6·FEXX·0.707w·2·1.5', 'kgf/cm', 'k_wtC', '(((((((0.75*0.6)*k_FEXX)*0.707)*sd_ww)/10)*2)*1.5)'),
    (69, '4. SOLDADURAS — AISC 360-16 J2.4', 'φRn', 'Alma a corte, Lw = d/2 − tbf (2 lados), θ = 0°', 'kgf', 'k_Rwv', '(((((((0.75*0.6)*k_FEXX)*0.707)*sd_ww)/10)*2)*(((k_d/2)-k_tf)))'),
    (71, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 's', '½·√(bcf·g)', 'cm', 'k_sc', '(0.5*_sqrt((k_cbf*k_g)))'),
    (72, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'c', 'pfo + tbf + pfi', 'cm', 'k_c', '((k_pfo+k_tf)+k_pfi)'),
    (73, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'pso', 'Rigidizador centrado en el ala: pfo + (tbf − ts)/2 ; ≤ s', 'cm', 'k_pso', '_min(k_sc,(k_pfo+(((k_tf-(cp_t/10)))/2)))'),
    (74, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'psi', 'pfi + (tbf − ts)/2 ; ≤ s', 'cm', 'k_psi', '_min(k_sc,(k_pfi+(((k_tf-(cp_t/10)))/2)))'),
    (75, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'Yc,u', 'Ala de columna sin rigidizar (Tabla 6.5)', 'cm', 'k_Ycu', '((((((k_cbf/2)*(((k_r1/k_sc)+(k_r4/k_sc))))+((2/k_g)*(((((k_r1*(((k_pb+(k_c/2))+k_sc)))+(k_r2*(((k_pb/2)+(k_c/4)))))+(k_r3*(((k_pb/2)+(k_c/2)))))+(k_r4*k_sc)))))+(k_g/2))) if (_eq(k_is8,1)) else (((((k_cbf/2)*(((k_r2/k_sc)+(k_r1/k_sc))))+((2/k_g)*((((k_r2*((k_sc+((3*k_c)/4))))+(k_r1*((k_sc+(k_c/4)))))+((k_c**2)/2)))))+(k_g/2))))'),
    (76, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'Yc,s', 'Ala de columna rigidizada (Tabla 6.6)', 'cm', 'k_Ycs', '((((((k_cbf/2)*(((((k_r1/k_sc)+(k_r2/k_pso))+(k_r3/k_psi))+(k_r4/k_sc))))+((2/k_g)*((((((k_r1*((k_sc+(k_pb/4))))+(k_r2*((k_pso+((3*k_pb)/4)))))+(k_r3*((k_psi+(k_pb/4)))))+(k_r4*((k_sc+((3*k_pb)/4)))))+(k_pb**2)))))+k_g)) if (_eq(k_is8,1)) else ((((k_cbf/2)*(((k_r2*(((1/k_sc)+(1/k_psi))))+(k_r1*(((1/k_sc)+(1/k_pso)))))))+((2/k_g)*(((k_r2*((k_sc+k_psi)))+(k_r1*((k_sc+k_pso)))))))))'),
    (77, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'Yc', "Usado según 'Rigidizadores de continuidad'", 'cm', 'k_Yc', "((k_Ycs) if (_eq(cp_usar,'Sí')) else (k_Ycu))"),
    (78, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φMcf', 'φ·Fyc·Yc·tcf²', 'kgf·cm', 'k_phiMcf', '(((k_phiy*co_Fy)*k_Yc)*(k_ctf**2))'),
    (79, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRn', 'Ala sin rigidizar como fuerza equivalente: φ·Fyc·Yc,u·tcf²/(d − tbf)', 'kgf', 'k_Rcfe', '((((k_phiy*co_Fy)*k_Ycu)*(k_ctf**2))/((k_d-k_tf)))'),
    (80, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'Ct', '0.5 si tope de columna < dc; si no 1.0', '-', 'k_Ct', '((0.5) if (((co_dtop/10)<k_cd)) else (1))'),
    (81, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRn', 'Fluencia local del alma: 1.0·Ct·(6kc + tbf + 2tp)·Fyc·tcw (DG4 / J10.2)', 'kgf', 'k_Rwy', '((((1*k_Ct)*((((6*k_ck)+k_tf)+(2*k_tp))))*co_Fy)*k_ctw)'),
    (82, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'N', 'tbf + 2w + 2tp', 'cm', 'k_Nc', '((k_tf+((2*sd_wf)/10))+(2*k_tp))'),
    (83, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRn', 'Crippling: 0.75·(0.80 | 0.40)·tcw²·[1 + …(tcw/tcf)^1.5]·√(E·Fyc·tcf/tcw) (J10.3)', 'kgf', 'k_Rwc', '(((0.75*(((0.8*((1+((3*((k_Nc/k_cd)))*(((k_ctw/k_ctf))**1.5)))))) if (((co_dtop/10)>=(k_cd/2))) else ((0.4*(((1+((3*((k_Nc/k_cd)))*(((k_ctw/k_ctf))**1.5)))) if (((k_Nc/k_cd)<=0.2)) else ((1+(((((4*k_Nc)/k_cd)-0.2))*(((k_ctw/k_ctf))**1.5)))))))))*(k_ctw**2))*_sqrt((((k_E*co_Fy)*k_ctf)/k_ctw)))'),
    (84, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRn', 'Pandeo del alma (J10.5): 0.90·24·tcw³·√(E·Fyc)/h (×0.5 cerca del tope)', 'kgf', 'k_Rwb', '(((((0.9*24)*(k_ctw**3))*_sqrt((k_E*co_Fy)))/k_ch)*((0.5) if (((co_dtop/10)<(k_cd/2))) else (1)))'),
    (85, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRn', 'Rigidizadores de continuidad: 0.90·Fyc·2·b·t (J10.8)', 'kgf', 'k_Rcp', '((((((0.9*co_Fy)*2)*cp_b)/10)*cp_t)/10)'),
    (86, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'Py', 'Fyc·Ac', 'kgf', 'k_Py', '(co_Fy*k_cA)'),
    (87, '5. COLUMNA — ALA (Tablas 6.5 / 6.6) Y ALMA (J10)', 'φRv', 'Zona de panel (J10.6a): 0.90·0.6·Fyc·dc·tcw·(1 ó 1.4 − Pr/Py)', 'kgf', 'k_Rpz', '(((((0.9*0.6)*co_Fy)*k_cd)*k_ctw)*((1) if (((Pu_col*1000)<=(0.4*k_Py))) else ((1.4-((Pu_col*1000)/k_Py)))))'),
    (89, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Cpr', '(Fy + Fu)/(2Fy) ≤ 1.2', '-', 'k_Cpr', '_min(1.2,(((vg_Fy+vg_Fu))/((2*vg_Fy))))'),
    (90, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Mpe', 'Cpr·Ry·Fyb·Zx', 'kgf·cm', 'k_Mpe', '(((k_Cpr*vg_Ry)*vg_Fy)*k_Zx)'),
    (91, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Sh', '4E: mín(d/2 ; 3bbf) ; 4ES/8ES: Lst + tp', 'cm', 'k_Shr', '((_min((k_d/2),(3*k_bf))) if (_eq(k_is4E,1)) else ((k_Lst+k_tp)))'),
    (92, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Lh', 'L − dc − 2Sh (entre rótulas)', 'cm', 'k_Lh', '(((sis_L*100)-k_cd)-(2*k_Shr))'),
    (93, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Vu', '2Mpe/Lh + Vgrav', 'kgf', 'k_Vus', '(((2*k_Mpe)/k_Lh)+(sis_Vg*1000))'),
    (94, '6. DEMANDA SÍSMICA POR CAPACIDAD — AISC 358-16 §6.8 (solo modo sísmico)', 'Mf', 'Mpe + Vu·Sh (en la cara de la columna)', 'kgf·cm', 'k_Mf', '(k_Mpe+(k_Vus*k_Shr))'),
    (96, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'col', 'Columna de la tabla según la configuración', '-', 'k_rc', "(_match(cfg,_cat('AE',5,'AE',7),0)*2)"),
    (97, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'tbf', 'Fuera de rango tbf (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg0', "((((1) if (_or((((k_tf)/2.54)<(_index(_cat('AL',5,'AQ',5),(k_rc-1))-0.001)),(((k_tf)/2.54)>(_index(_cat('AL',5,'AQ',5),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',5,'AQ',5),(k_rc-1)))) else (0))"),
    (98, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'bbf', 'Fuera de rango bbf (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg1', "((((1) if (_or((((k_bf)/2.54)<(_index(_cat('AL',6,'AQ',6),(k_rc-1))-0.001)),(((k_bf)/2.54)>(_index(_cat('AL',6,'AQ',6),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',6,'AQ',6),(k_rc-1)))) else (0))"),
    (99, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'd', 'Fuera de rango d (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg2', "((((1) if (_or((((k_d)/2.54)<(_index(_cat('AL',7,'AQ',7),(k_rc-1))-0.001)),(((k_d)/2.54)>(_index(_cat('AL',7,'AQ',7),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',7,'AQ',7),(k_rc-1)))) else (0))"),
    (100, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'tp', 'Fuera de rango tp (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg3', "((((1) if (_or((((k_tp)/2.54)<(_index(_cat('AL',8,'AQ',8),(k_rc-1))-0.001)),(((k_tp)/2.54)>(_index(_cat('AL',8,'AQ',8),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',8,'AQ',8),(k_rc-1)))) else (0))"),
    (101, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'bp', 'Fuera de rango bp (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg4', "((((1) if (_or((((k_bp)/2.54)<(_index(_cat('AL',9,'AQ',9),(k_rc-1))-0.001)),(((k_bp)/2.54)>(_index(_cat('AL',9,'AQ',9),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',9,'AQ',9),(k_rc-1)))) else (0))"),
    (102, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'g', 'Fuera de rango g (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg5', "((((1) if (_or((((k_g)/2.54)<(_index(_cat('AL',10,'AQ',10),(k_rc-1))-0.001)),(((k_g)/2.54)>(_index(_cat('AL',10,'AQ',10),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',10,'AQ',10),(k_rc-1)))) else (0))"),
    (103, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'pfi', 'Fuera de rango pfi (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg6', "((((1) if (_or((((k_pfi)/2.54)<(_index(_cat('AL',11,'AQ',11),(k_rc-1))-0.001)),(((k_pfi)/2.54)>(_index(_cat('AL',11,'AQ',11),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',11,'AQ',11),(k_rc-1)))) else (0))"),
    (104, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'pfo', 'Fuera de rango pfo (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg7', "((((1) if (_or((((k_pfo)/2.54)<(_index(_cat('AL',12,'AQ',12),(k_rc-1))-0.001)),(((k_pfo)/2.54)>(_index(_cat('AL',12,'AQ',12),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',12,'AQ',12),(k_rc-1)))) else (0))"),
    (105, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'pb', 'Fuera de rango pb (1 = sí): valor en pulgadas vs Tabla 6.1', '-', 'k_rg8', "((((1) if (_or((((((k_pb) if (_eq(k_is8,1)) else (0)))/2.54)<(_index(_cat('AL',13,'AQ',13),(k_rc-1))-0.001)),(((((k_pb) if (_eq(k_is8,1)) else (0)))/2.54)>(_index(_cat('AL',13,'AQ',13),k_rc)+0.001)))) else (0))) if (_isnum(_index(_cat('AL',13,'AQ',13),(k_rc-1)))) else (0))"),
    (106, '7. RANGOS ENSAYADOS (AISC 358-16 Tabla 6.1)', 'Σ', 'Parámetros fuera de rango', '-', 'k_rgn', '((((((((k_rg0+k_rg1)+k_rg2)+k_rg3)+k_rg4)+k_rg5)+k_rg6)+k_rg7)+k_rg8)'),
    (109, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Símbolo', 'Descripción', 'Unidad', 'g109', '1'),
]

COMBO = [  # (fila, sección, símbolo, descripción, unidad, expresión); IDX_ = nº de combinación
    (110, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Combo', 'Nombre', '', "(((('Mf sísmico') if (_eq(IDX_,1)) else (''))) if (_eq(k_seis,1)) else ((('') if (_eq(_index(cb_nom,IDX_),'')) else (_index(cb_nom,IDX_)))))"),
    (111, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'activo', 'Combinación con cargas', '-', '((((1) if (_eq(IDX_,1)) else (0))) if (_eq(k_seis,1)) else (((1) if (((abs(_n(_index(cb_M,IDX_)))+abs(_n(_index(cb_V,IDX_))))>0)) else (0))))'),
    (112, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Mu', 'Momento de diseño (sísmico: Mf)', 'kgf·cm', '(((r111*k_Mf)) if (_eq(k_seis,1)) else ((abs(_n(_index(cb_M,IDX_)))*100000)))'),
    (113, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Vu', 'Cortante de diseño (sísmico: Vu por capacidad)', 'kgf', '(((r111*k_Vus)) if (_eq(k_seis,1)) else ((abs(_n(_index(cb_V,IDX_)))*1000)))'),
    (114, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'db,req', '√(2Mu/(π·φn·Fnt·Σhi))', 'mm', '(_sqrt(((2*r112)/((((math.pi*k_phin)*pn_Fnt)*k_sh))))*10)'),
    (115, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Ffu', 'Mu/(d − tbf)', 'kgf', '(r112/((k_d-k_tf)))'),
    (116, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Pernos a tracción sin palanca: Mu/(φn·Mnp)', '-', '(r112/((k_phin*k_Mnp)))'),
    (117, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Dem.', 'Placa: 1.11·φn·Mnp (DG4) | 1.11·Mf (AISC 358)', 'Tonf·m', '((((1.11*r112)) if (_eq(k_seis,1)) else ((((1.11*k_phin)*k_Mnp)*r111)))/100000)'),
    (118, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Flexión de placa (placa gruesa)', '-', '((r117*100000)/k_phiMpl)'),
    (119, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'tp,req', '√(Dem./(φ·Fyp·Yp))', 'mm', '(_sqrt(((r117*100000)/(((k_phiy*pl_Fy)*k_Yp))))*10)'),
    (120, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Extensión 4E — fluencia por corte: (Ffu/2)/φRn', '-', '((((r115/2)/k_Rsy)) if (_eq(k_is4E,1)) else (0))'),
    (121, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Extensión 4E — ruptura por corte: (Ffu/2)/φRn', '-', '((((r115/2)/k_Rsr)) if (_eq(k_is4E,1)) else (0))'),
    (122, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Corte en pernos', '-', '(r113/k_Rvb)'),
    (123, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Aplastamiento en placa', '-', '(r113/k_Rbp)'),
    (124, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Aplastamiento en ala de columna', '-', '(r113/k_Rbc)'),
    (125, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Soldadura ala (filete, solo no sísmico)', '-', '((0) if (_eq(k_seis,1)) else ((r115/k_Rwf)))'),
    (126, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Soldadura alma, zona de tracción', '-', '((r111*k_wtD)/k_wtC)'),
    (127, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Soldadura alma a corte', '-', '(r113/k_Rwv)'),
    (128, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Dem.', 'Ala de columna: 1.11·φn·Mnp | 1.11·Mf', 'Tonf·m', '((((1.11*r112)) if (_eq(k_seis,1)) else ((((1.11*k_phin)*k_Mnp)*r111)))/100000)'),
    (129, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Flexión del ala de columna', '-', '((r128*100000)/k_phiMcf)'),
    (130, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'tcf,req', '√(Dem./(φ·Fyc·Yc))', 'mm', '(_sqrt(((r128*100000)/(((k_phiy*co_Fy)*k_Yc))))*10)'),
    (131, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Fluencia local del alma', '-', "((0) if (_eq(cp_usar,'Sí')) else ((r115/k_Rwy)))"),
    (132, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Crippling del alma', '-', "((0) if (_eq(cp_usar,'Sí')) else ((r115/k_Rwc)))"),
    (133, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Pandeo del alma (solo vigas a ambos lados)', '-', "((0) if (_or(_eq(cp_usar,'Sí'),_eq(dos_lados,'No'))) else ((r115/k_Rwb)))"),
    (134, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Fsu', 'Ffu − mín(φRn ala, fluencia, crippling, pandeo)', 'kgf', "_max(0,(r115-_min(k_Rcfe,k_Rwy,k_Rwc,((k_Rwb) if (_eq(dos_lados,'Sí')) else (1000000000000)))))"),
    (135, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Rigidizadores de continuidad: Fsu/φRn', '-', "(((r134/k_Rcp)) if (_eq(cp_usar,'Sí')) else (0))"),
    (136, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'Vpz', 'Cortante en zona de panel: (Mu + Mu,op)/(d − tbf) ; sísmico 2 lados: 2Mf', 'kgf', "((((r112*((2) if (_eq(dos_lados,'Sí')) else (1)))) if (_eq(k_seis,1)) else ((r112+((((abs(Mu_op)*100000)*r111)) if (_eq(dos_lados,'Sí')) else (0)))))/((k_d-k_tf)))"),
    (137, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'ratio', 'Zona de panel', '-', '(r136/k_Rpz)'),
    (138, '8. VERIFICACIÓN POR COMBINACIÓN (modo sísmico: solo columna 1 = Mf, Vu)', 'máx.', 'Ratio máximo de la combinación', '-', '_max(r116,r118,r120,r121,r122,r123,r124,r125,r126,r127,r129,r131,r132,r133,r135,r137)'),
]

RATIO_COL = 'S'  # columna de ratio de la tabla de verificaciones
DEM_COL, CAP_COL = 'P', 'Q'
CHECKS = [  # (fila, tipo, nombre, referencia, unidad, demanda, capacidad, ratio, combo)
    (11, 'GRUPO', 'VIGA Y PLACA EXTREMA', '', '', None, None, None, None),
    (12, 'CHEQUEO', 'Pernos a tracción (sin efecto palanca)', 'DG4 · AISC 358 §6.8 pasos 3–4', 'Tonf·m', '(_index(_row(112),_match(_max(_row(116)),_row(116),0))/100000)', '((k_phin*k_Mnp)/100000)', '_max(_row(116))', "((_index(_row(110),_match(_max(_row(116)),_row(116),0))) if (_isnum(DIS_S12)) else ('—'))"),
    (13, 'CHEQUEO', 'Flexión de placa extrema (placa gruesa)', 'DG4 · AISC 358 Tabla 6.2', 'Tonf·m', '(_index(_row(117),_match(_max(_row(118)),_row(118),0))/1)', '(k_phiMpl/100000)', '_max(_row(118))', "((_index(_row(110),_match(_max(_row(118)),_row(118),0))) if (_isnum(DIS_S13)) else ('—'))"),
    (14, 'CHEQUEO', 'Extensión 4E — fluencia por corte', 'AISC 358 §6.8 · J4.2(a)', 'Tonf', "(('—') if (_eq(k_is4E,0)) else ((_index(_row(115),_match(_max(_row(120)),_row(120),0))/2000)))", "(('—') if (_eq(k_is4E,0)) else ((k_Rsy/1000)))", "(('N/A') if (_eq(k_is4E,0)) else (_max(_row(120))))", "((_index(_row(110),_match(_max(_row(120)),_row(120),0))) if (_isnum(DIS_S14)) else ('—'))"),
    (15, 'CHEQUEO', 'Extensión 4E — ruptura por corte', 'AISC 358 §6.8 · J4.2(b)', 'Tonf', "(('—') if (_eq(k_is4E,0)) else ((_index(_row(115),_match(_max(_row(121)),_row(121),0))/2000)))", "(('—') if (_eq(k_is4E,0)) else ((k_Rsr/1000)))", "(('N/A') if (_eq(k_is4E,0)) else (_max(_row(121))))", "((_index(_row(110),_match(_max(_row(121)),_row(121),0))) if (_isnum(DIS_S15)) else ('—'))"),
    (16, 'CHEQUEO', 'Rigidizador de placa — espesor mínimo', 'AISC 358 §6.8 (ts ≥ tbw·Fyb/Fys)', 'mm', "(('—') if (_eq(k_is4E,1)) else ((k_tsr*10)))", "(('—') if (_eq(k_is4E,1)) else (st_t))", "(('N/A') if (_eq(k_is4E,1)) else (((k_tsr*10)/st_t)))", "'—'"),
    (17, 'CHEQUEO', 'Rigidizador de placa — pandeo local hst/ts', 'AISC 358 §6.8 (≤ 0.56√(E/Fys))', '-', "(('—') if (_eq(k_is4E,1)) else (k_hts))", "(('—') if (_eq(k_is4E,1)) else (k_htsl))", "(('N/A') if (_eq(k_is4E,1)) else ((k_hts/k_htsl)))", "'—'"),
    (18, 'GRUPO', 'PERNOS — CORTE EN EL LADO DE COMPRESIÓN', '', '', None, None, None, None),
    (19, 'CHEQUEO', 'Corte en pernos', 'AISC 358 §6.8 · J3.6', 'Tonf', '(_index(_row(113),_match(_max(_row(122)),_row(122),0))/1000)', '(k_Rvb/1000)', '_max(_row(122))', "((_index(_row(110),_match(_max(_row(122)),_row(122),0))) if (_isnum(DIS_S19)) else ('—'))"),
    (20, 'CHEQUEO', 'Aplastamiento / desgarre — placa extrema', 'J3.10', 'Tonf', '(_index(_row(113),_match(_max(_row(123)),_row(123),0))/1000)', '(k_Rbp/1000)', '_max(_row(123))', "((_index(_row(110),_match(_max(_row(123)),_row(123),0))) if (_isnum(DIS_S20)) else ('—'))"),
    (21, 'CHEQUEO', 'Aplastamiento / desgarre — ala de columna', 'J3.10', 'Tonf', '(_index(_row(113),_match(_max(_row(124)),_row(124),0))/1000)', '(k_Rbc/1000)', '_max(_row(124))', "((_index(_row(110),_match(_max(_row(124)),_row(124),0))) if (_isnum(DIS_S21)) else ('—'))"),
    (22, 'GRUPO', 'SOLDADURAS VIGA – PLACA', '', '', None, None, None, None),
    (23, 'CHEQUEO', 'Ala de viga – placa (filete)', 'DG4 · J2.4 (sísmico: CJP §6.7.6)', 'Tonf', "(('—') if (_eq(k_seis,1)) else ((_index(_row(115),_match(_max(_row(125)),_row(125),0))/1000)))", "(('—') if (_eq(k_seis,1)) else ((k_Rwf/1000)))", "(('N/A') if (_eq(k_seis,1)) else (_max(_row(125))))", "((_index(_row(110),_match(_max(_row(125)),_row(125),0))) if (_isnum(DIS_S23)) else ('—'))"),
    (24, 'CHEQUEO', 'Alma – zona de tracción (desarrollar Fy del alma)', 'DG4 · J2.4', 'kgf/cm', 'k_wtD', 'k_wtC', '_max(_row(126))', "((_index(_row(110),_match(_max(_row(126)),_row(126),0))) if (_isnum(DIS_S24)) else ('—'))"),
    (25, 'CHEQUEO', 'Alma – corte', 'J2.4', 'Tonf', '(_index(_row(113),_match(_max(_row(127)),_row(127),0))/1000)', '(k_Rwv/1000)', '_max(_row(127))', "((_index(_row(110),_match(_max(_row(127)),_row(127),0))) if (_isnum(DIS_S25)) else ('—'))"),
    (26, 'GRUPO', 'COLUMNA', '', '', None, None, None, None),
    (27, 'CHEQUEO', 'Flexión del ala de columna', 'DG4 · AISC 358 Tablas 6.5/6.6', 'Tonf·m', '(_index(_row(128),_match(_max(_row(129)),_row(129),0))/1)', '(k_phiMcf/100000)', '_max(_row(129))', "((_index(_row(110),_match(_max(_row(129)),_row(129),0))) if (_isnum(DIS_S27)) else ('—'))"),
    (28, 'CHEQUEO', 'Fluencia local del alma', 'DG4 · J10.2', 'Tonf', "(('—') if (_eq(cp_usar,'Sí')) else ((_index(_row(115),_match(_max(_row(131)),_row(131),0))/1000)))", "(('—') if (_eq(cp_usar,'Sí')) else ((k_Rwy/1000)))", "(('N/A') if (_eq(cp_usar,'Sí')) else (_max(_row(131))))", "((_index(_row(110),_match(_max(_row(131)),_row(131),0))) if (_isnum(DIS_S28)) else ('—'))"),
    (29, 'CHEQUEO', 'Aplastamiento del alma (crippling)', 'J10.3', 'Tonf', "(('—') if (_eq(cp_usar,'Sí')) else ((_index(_row(115),_match(_max(_row(132)),_row(132),0))/1000)))", "(('—') if (_eq(cp_usar,'Sí')) else ((k_Rwc/1000)))", "(('N/A') if (_eq(cp_usar,'Sí')) else (_max(_row(132))))", "((_index(_row(110),_match(_max(_row(132)),_row(132),0))) if (_isnum(DIS_S29)) else ('—'))"),
    (30, 'CHEQUEO', 'Pandeo del alma en compresión', 'J10.5', 'Tonf', "(('—') if (_or(_eq(cp_usar,'Sí'),_eq(dos_lados,'No'))) else ((_index(_row(115),_match(_max(_row(133)),_row(133),0))/1000)))", "(('—') if (_or(_eq(cp_usar,'Sí'),_eq(dos_lados,'No'))) else ((k_Rwb/1000)))", "(('N/A') if (_or(_eq(cp_usar,'Sí'),_eq(dos_lados,'No'))) else (_max(_row(133))))", "((_index(_row(110),_match(_max(_row(133)),_row(133),0))) if (_isnum(DIS_S30)) else ('—'))"),
    (31, 'CHEQUEO', 'Rigidizadores de continuidad', 'DG4 · J10.8', 'Tonf', "(('—') if (_eq(cp_usar,'No')) else ((_index(_row(134),_match(_max(_row(135)),_row(135),0))/1000)))", "(('—') if (_eq(cp_usar,'No')) else ((k_Rcp/1000)))", "(('N/A') if (_eq(cp_usar,'No')) else (_max(_row(135))))", "((_index(_row(110),_match(_max(_row(135)),_row(135),0))) if (_isnum(DIS_S31)) else ('—'))"),
    (32, 'CHEQUEO', 'Zona de panel (corte)', 'J10.6(a)', 'Tonf', '(_index(_row(136),_match(_max(_row(137)),_row(137),0))/1000)', '(k_Rpz/1000)', '_max(_row(137))', "((_index(_row(110),_match(_max(_row(137)),_row(137),0))) if (_isnum(DIS_S32)) else ('—'))"),
    (33, 'GRUPO', 'GEOMETRÍA Y DETALLES (requerido / provisto)', '', '', None, None, None, None),
    (34, 'CHEQUEO', 'Ancho de placa bp ≥ bbf', 'AISC 358 §6.8', 'cm', 'k_bf', 'k_bp', '((k_bf)/_max(k_bp,0.001))', "'—'"),
    (35, 'CHEQUEO', 'Holgura de llave: pfi, pfo ≥ db + 12.7 mm', 'DG4', 'cm', '(k_db+1.27)', '_min(k_pfi,k_pfo)', '(((k_db+1.27))/_max(_min(k_pfi,k_pfo),0.001))', "'—'"),
    (36, 'CHEQUEO', 'Borde de ≥ mínimo', 'J3.4', 'cm', 'k_emin', 'k_de', '((k_emin)/_max(k_de,0.001))', "'—'"),
    (37, 'CHEQUEO', 'Borde lateral (bp − g)/2 ≥ mínimo', 'J3.4', 'cm', 'k_emin', '(((k_bp-k_g))/2)', '((k_emin)/_max((((k_bp-k_g))/2),0.001))', "'—'"),
    (38, 'CHEQUEO', 'Gramil g ≥ 2⅔·db', 'J3.3', 'cm', '((8/3)*k_db)', 'k_g', '((((8/3)*k_db))/_max(k_g,0.001))', "'—'"),
    (39, 'CHEQUEO', 'Paso pb ≥ 2⅔·db (8ES)', 'J3.3', 'cm', "(('—') if (_eq(k_is8,0)) else (((8/3)*k_db)))", "(('—') if (_eq(k_is8,0)) else (k_pb))", "(('N/A') if (_eq(k_is8,0)) else (((((8/3)*k_db))/_max(k_pb,0.001))))", "'—'"),
    (40, 'CHEQUEO', 'Filete mínimo ala de viga', 'Tabla J2.4', 'mm', "(('—') if (_eq(k_seis,1)) else (((3) if ((_min(vg_tf_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tf_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tf_mm,pl_tp)<=19)) else (8))))))))", "(('—') if (_eq(k_seis,1)) else (sd_wf))", "(('N/A') if (_eq(k_seis,1)) else (((((3) if ((_min(vg_tf_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tf_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tf_mm,pl_tp)<=19)) else (8)))))))/_max(sd_wf,0.001))))", "'—'"),
    (41, 'CHEQUEO', 'Filete mínimo alma de viga', 'Tabla J2.4', 'mm', '((3) if ((_min(vg_tw_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tw_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tw_mm,pl_tp)<=19)) else (8))))))', 'sd_ww', '((((3) if ((_min(vg_tw_mm,pl_tp)<=6)) else (((5) if ((_min(vg_tw_mm,pl_tp)<=13)) else (((6) if ((_min(vg_tw_mm,pl_tp)<=19)) else (8)))))))/_max(sd_ww,0.001))', "'—'"),
    (42, 'CHEQUEO', 'Rigid. continuidad: b + tcw/2 ≥ bbf/3', 'J10.8', 'cm', "(('—') if (_eq(cp_usar,'No')) else (((k_bf/3)-(k_ctw/2))))", "(('—') if (_eq(cp_usar,'No')) else ((cp_b/10)))", "(('N/A') if (_eq(cp_usar,'No')) else (((((k_bf/3)-(k_ctw/2)))/_max((cp_b/10),0.001))))", "'—'"),
    (43, 'CHEQUEO', 'Rigid. continuidad: t ≥ tbf/2', 'J10.8', 'cm', "(('—') if (_eq(cp_usar,'No')) else ((k_tf/2)))", "(('—') if (_eq(cp_usar,'No')) else ((cp_t/10)))", "(('N/A') if (_eq(cp_usar,'No')) else ((((k_tf/2))/_max((cp_t/10),0.001))))", "'—'"),
    (44, 'CHEQUEO', 'Parámetros dentro de rangos ensayados', 'AISC 358 Tabla 6.1 · DG4', 'de 9', 'k_rgn', "'fuera'", '((0) if (_eq(k_rgn,0)) else (((1.5) if (_eq(k_seis,1)) else (0.95))))', "'—'"),
]
