"""Modelo generado por tools/xl2py.py — NO editar a mano (regenerar desde la hoja de Excel)."""

NCOMBO = 10

DERIVED = [  # (fila, nombre, etiqueta, unidad, expresión)  — fórmulas de la hoja DISEÑO
    (18, 'cu_d_mm', 'Peralte d', 'mm', "((DIS_E18) if (_eq(cu_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(cu_perfil,_cat('A',5,'A',40),0))))"),
    (19, 'cu_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E19) if (_eq(cu_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(cu_perfil,_cat('A',5,'A',40),0))))"),
    (20, 'cu_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E20) if (_eq(cu_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(cu_perfil,_cat('A',5,'A',40),0))))"),
    (21, 'cu_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E21) if (_eq(cu_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(cu_perfil,_cat('A',5,'A',40),0))))"),
    (23, 'cu_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(cu_acero,_cat('G',5,'G',10),0))"),
    (23, 'cu_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(cu_acero,_cat('G',5,'G',10),0))"),
    (26, 'cl_d_mm', 'Peralte d', 'mm', "((DIS_E26) if (_eq(cl_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(cl_perfil,_cat('A',5,'A',40),0))))"),
    (27, 'cl_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E27) if (_eq(cl_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(cl_perfil,_cat('A',5,'A',40),0))))"),
    (28, 'cl_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E28) if (_eq(cl_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(cl_perfil,_cat('A',5,'A',40),0))))"),
    (29, 'cl_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E29) if (_eq(cl_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(cl_perfil,_cat('A',5,'A',40),0))))"),
    (31, 'cl_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(cl_acero,_cat('G',5,'G',10),0))"),
    (31, 'cl_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(cl_acero,_cat('G',5,'G',10),0))"),
    (34, 'pf_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(pf_acero,_cat('G',5,'G',10),0))"),
    (34, 'pf_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(pf_acero,_cat('G',5,'G',10),0))"),
    (37, 'fill_t', 'Relleno en columna superior (auto)', 'mm', '(abs((cl_d_mm-cu_d_mm))/2)'),
    (49, 'pw_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(pw_acero,_cat('G',5,'G',10),0))"),
    (49, 'pw_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(pw_acero,_cat('G',5,'G',10),0))"),
]

GLOBAL = [  # (fila, sección, símbolo, descripción, unidad, nombre, expresión)  — hoja CALCULO
    (5, '0. GEOMETRÍA Y OPCIONES', 'apern.', '1 = placas apernadas', '-', 't_ap', "((1) if (_eq(tipo,'Placas apernadas')) else (0))"),
    (6, '0. GEOMETRÍA Y OPCIONES', 'PJP', '1 = soldado PJP', '-', 't_pjp', "((1) if (_eq(tipo,'Soldado PJP')) else (0))"),
    (7, '0. GEOMETRÍA Y OPCIONES', 'CJP', '1 = soldado CJP', '-', 't_cjp', "((1) if (_eq(tipo,'Soldado CJP')) else (0))"),
    (8, '0. GEOMETRÍA Y OPCIONES', 'fresado', '1 = extremos fresados (apoyo por contacto)', '-', 'k_fr', "((1) if (_eq(fresado,'Sí')) else (0))"),
    (9, '0. GEOMETRÍA Y OPCIONES', '×D2.5', 'Factor de demanda para PJP en diseño sísmico (2.0)', '-', 'k_s2', "((2) if (_and(_eq(_s(sismico)[:int(2)],'Sí'),_eq(t_pjp,1))) else (1))"),
    (10, '0. GEOMETRÍA Y OPCIONES', 'E', 'Módulo de elasticidad', 'kgf/cm²', 'k_E', '2040000'),
    (11, '0. GEOMETRÍA Y OPCIONES', 'du', 'Peralte', 'cm', 'u_d', '(cu_d_mm/10)'),
    (12, '0. GEOMETRÍA Y OPCIONES', 'bfu', 'Ala', 'cm', 'u_bf', '(cu_bf_mm/10)'),
    (13, '0. GEOMETRÍA Y OPCIONES', 'twu', 'Alma', 'cm', 'u_tw', '(cu_tw_mm/10)'),
    (14, '0. GEOMETRÍA Y OPCIONES', 'tfu', 'Ala', 'cm', 'u_tf', '(cu_tf_mm/10)'),
    (15, '0. GEOMETRÍA Y OPCIONES', 'dl', 'Peralte', 'cm', 'l_d', '(cl_d_mm/10)'),
    (16, '0. GEOMETRÍA Y OPCIONES', 'bfl', 'Ala', 'cm', 'l_bf', '(cl_bf_mm/10)'),
    (17, '0. GEOMETRÍA Y OPCIONES', 'twl', 'Alma', 'cm', 'l_tw', '(cl_tw_mm/10)'),
    (18, '0. GEOMETRÍA Y OPCIONES', 'tfl', 'Ala', 'cm', 'l_tf', '(cl_tf_mm/10)'),
    (19, '0. GEOMETRÍA Y OPCIONES', 'Af', 'bf·tf (superior)', 'cm²', 'u_Af', '(u_bf*u_tf)'),
    (20, '0. GEOMETRÍA Y OPCIONES', 'A', 'Área (superior)', 'cm²', 'u_A', '(((2*u_bf)*u_tf)+(((u_d-(2*u_tf)))*u_tw))'),
    (21, '0. GEOMETRÍA Y OPCIONES', 'Aw', 'A − 2Af', 'cm²', 'u_Aw', '(u_A-(2*u_Af))'),
    (22, '0. GEOMETRÍA Y OPCIONES', 'Fy,mín', 'Menor Fy de las columnas', 'kgf/cm²', 'k_Fy', '_min(cu_Fy,cl_Fy)'),
    (23, '0. GEOMETRÍA Y OPCIONES', 'Fu,mín', 'Menor Fu de las columnas', 'kgf/cm²', 'k_Fu', '_min(cu_Fu,cl_Fu)'),
    (24, '0. GEOMETRÍA Y OPCIONES', 'solape', 'Solape de alas para apoyo: mín(du, dl)/2 − máx(du/2 − tfu, dl/2 − tfl)', 'cm', 'k_ov', '_max(0,((_min(u_d,l_d)/2)-_max(((u_d/2)-u_tf),((l_d/2)-l_tf))))'),
    (25, '0. GEOMETRÍA Y OPCIONES', 'Aapoyo', '2·mín(bf)·solape + mín(tw)·(du − 2tfu)', 'cm²', 'k_Ab', '(((2*_min(u_bf,l_bf))*k_ov)+(_min(u_tw,l_tw)*((u_d-(2*u_tf)))))'),
    (26, '0. GEOMETRÍA Y OPCIONES', 'φRn', 'Apoyo por contacto en superficies fresadas: 0.75·1.8·Fy·Aapoyo (J7a)', 'kgf', 'k_Rbe', '(((0.75*1.8)*k_Fy)*k_Ab)'),
    (27, '0. GEOMETRÍA Y OPCIONES', 'SC', '1 = deslizamiento crítico', '-', 'j_sc', "((1) if (_eq(_s(junta)[:int(3)],'Des')) else (0))"),
    (28, '0. GEOMETRÍA Y OPCIONES', 'μ', '0.30 / 0.50', '-', 'j_mu', "((0.5) if (_eq(_s(junta)[-int(5):],'0.50)')) else (0.3))"),
    (30, '1. PLACAS Y PERNOS DE ALA (apernado)', 'db', 'Diámetro pernos de ala', 'in', 'fa_dbi', "_index(_cat('P',5,'P',10),_match(fa_diam,_cat('O',5,'O',10),0))"),
    (31, '1. PLACAS Y PERNOS DE ALA (apernado)', 'db', 'Diámetro pernos de ala', 'cm', 'fa_db', '(fa_dbi*2.54)'),
    (32, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Ab', 'π·db²/4', 'cm²', 'fa_Ab', '((math.pi*(fa_db**2))/4)'),
    (33, '1. PLACAS Y PERNOS DE ALA (apernado)', 'dh', 'Agujero estándar (Tabla J3.3)', 'cm', 'fa_dh', '((((fa_dbi+(1/16))) if ((fa_dbi<1)) else ((fa_dbi+(1/8))))*2.54)'),
    (34, '1. PLACAS Y PERNOS DE ALA (apernado)', 'dh,net', 'dh + 1/16 in (B4.3b)', 'cm', 'fa_dn', '(fa_dh+0.15875)'),
    (35, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'fa_em', "(_index(_cat('Q',5,'Q',10),_match(fa_diam,_cat('O',5,'O',10),0))*2.54)"),
    (36, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Fnv', 'Resistencia a corte', 'kgf/cm²', 'fa_Fnv', "_index(_cat('L',5,'L',8),_match(fa_grado,_cat('K',5,'K',8),0))"),
    (37, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Tb', 'Pretensión mínima (Tabla J3.1)', 'kgf', 'fa_Tb', "((_index(_cat('R',5,'R',10),_match(fa_diam,_cat('O',5,'O',10),0))) if (_eq(_index(_cat('M',5,'M',8),_match(fa_grado,_cat('K',5,'K',8),0)),'A')) else (_index(_cat('S',5,'S',10),_match(fa_diam,_cat('O',5,'O',10),0))))"),
    (38, '1. PLACAS Y PERNOS DE ALA (apernado)', 'n', 'Pernos por ala por lado = 2·filas', '-', 'f_nb', '(2*fa_n)'),
    (39, '1. PLACAS Y PERNOS DE ALA (apernado)', 'fill', 'J5.2: factor por relleno 1 − 0.0154(t − 6) [mm], 6 < t ≤ 19 (aplastamiento)', '-', 'f_fill', '((1) if (_eq(j_sc,1)) else (((1) if ((fill_t<=6)) else ((1-(0.0154*((_min(fill_t,19)-6))))))))'),
    (40, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φrn', 'Por perno: 0.75·Fnv·Ab·fill ; deslizamiento 1.0·μ·1.13·hf·Tb (hf = 1, un relleno)', 'kgf', 'f_rv', '(((((1*j_mu)*1.13)*fa_Tb)) if (_eq(j_sc,1)) else ((((0.75*fa_Fnv)*fa_Ab)*f_fill)))'),
    (41, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φrn,v', 'Corte del perno con reducción por relleno', 'kgf', 'f_rvs', '(((0.75*fa_Fnv)*fa_Ab)*f_fill)'),
    (42, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φrn', 'Aplastamiento por perno en ala de columna superior: 0.75·mín(1.2(Le − dh/2) ; 1.2(s − dh) ; 2.4db)·tf·Fu', 'kgf', 'f_rbc', '(((0.75*_min((1.2*_min(((fa_Lec/10)-(fa_dh/2)),((fa_s/10)-fa_dh))),(2.4*fa_db)))*u_tf)*cu_Fu)'),
    (43, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φrn', 'Aplastamiento por perno en placa', 'kgf', 'f_rbp', '((((0.75*_min((1.2*_min(((fa_Lep/10)-(fa_dh/2)),((fa_s/10)-fa_dh))),(2.4*fa_db)))*pf_t)/10)*pf_Fu)'),
    (44, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Ag', 'b·t de placa', 'cm²', 'p_Ag', '(((pf_b/10)*pf_t)/10)'),
    (45, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φRn', 'Fluencia en tracción 0.90·Fy·Ag', 'kgf', 'p_ty', '((0.9*pf_Fy)*p_Ag)'),
    (46, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φRn', 'Ruptura 0.75·Fu·mín(An ; 0.85Ag)', 'kgf', 'p_tr', '((0.75*pf_Fu)*_min((((((pf_b/10)-(2*fa_dn)))*pf_t)/10),(0.85*p_Ag)))'),
    (47, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φRn', 'Bloque de cortante de placa: mín(bloques exteriores ; central)', 'kgf', 'p_bs', '(0.75*((((_min(((0.6*pf_Fu)*(((2*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*pf_Fy)*2)*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10)))))*pf_t)/10)+(((pf_Fu*_min((2*(((((pf_b-fa_g))/20)-(fa_dn/2)))),((fa_g/10)-fa_dn)))*pf_t)/10))))'),
    (48, '1. PLACAS Y PERNOS DE ALA (apernado)', 'KL/r', '0.65·(gap + 2·Le,col)/(t/√12)', '-', 'p_KLr', '((0.65*(((gap/10)+((2*fa_Lec)/10))))/(((pf_t/10)/_sqrt(12))))'),
    (49, '1. PLACAS Y PERNOS DE ALA (apernado)', 'Fcr', 'KL/r ≤ 25: Fy ; si no Cap. E', 'kgf/cm²', 'p_Fcr', '((pf_Fy) if ((p_KLr<=25)) else (((((0.658**((pf_Fy/((((math.pi**2)*k_E)/(p_KLr**2))))))*pf_Fy)) if (((pf_Fy/((((math.pi**2)*k_E)/(p_KLr**2))))<=2.25)) else ((((0.877*(math.pi**2))*k_E)/(p_KLr**2))))))'),
    (50, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φPn', 'Compresión de placa 0.90·Fcr·Ag (J4.4)', 'kgf', 'p_cb', '((0.9*p_Fcr)*p_Ag)'),
    (51, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φRn', 'Ala de columna superior: ruptura en tracción 0.75·Fu·(bf − 2dh,n)·tf', 'kgf', 'c_tr', '(((0.75*cu_Fu)*((u_bf-(2*fa_dn))))*u_tf)'),
    (52, '1. PLACAS Y PERNOS DE ALA (apernado)', 'φRn', 'Ala de columna superior: bloque de cortante (bloques exteriores)', 'kgf', 'c_bs', '(0.75*(((_min(((0.6*cu_Fu)*(((2*(((fa_Lec/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*cu_Fy)*2)*(((fa_Lec/10)+((((fa_n-1))*fa_s)/10)))))*u_tf)+(((cu_Fu*2)*(((((u_bf-(fa_g/10)))/2)-(fa_dn/2))))*u_tf))))'),
    (54, '2. ALMA (apernado)', 'db', 'Diámetro pernos de alma', 'in', 'wa_dbi', "_index(_cat('P',5,'P',10),_match(wa_diam,_cat('O',5,'O',10),0))"),
    (55, '2. ALMA (apernado)', 'db', 'Diámetro pernos de alma', 'cm', 'wa_db', '(wa_dbi*2.54)'),
    (56, '2. ALMA (apernado)', 'Ab', 'π·db²/4', 'cm²', 'wa_Ab', '((math.pi*(wa_db**2))/4)'),
    (57, '2. ALMA (apernado)', 'dh', 'Agujero estándar (Tabla J3.3)', 'cm', 'wa_dh', '((((wa_dbi+(1/16))) if ((wa_dbi<1)) else ((wa_dbi+(1/8))))*2.54)'),
    (58, '2. ALMA (apernado)', 'dh,net', 'dh + 1/16 in (B4.3b)', 'cm', 'wa_dn', '(wa_dh+0.15875)'),
    (59, '2. ALMA (apernado)', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'wa_em', "(_index(_cat('Q',5,'Q',10),_match(wa_diam,_cat('O',5,'O',10),0))*2.54)"),
    (60, '2. ALMA (apernado)', 'Fnv', 'Resistencia a corte', 'kgf/cm²', 'wa_Fnv', "_index(_cat('L',5,'L',8),_match(wa_grado,_cat('K',5,'K',8),0))"),
    (61, '2. ALMA (apernado)', 'Tb', 'Pretensión mínima (Tabla J3.1)', 'kgf', 'wa_Tb', "((_index(_cat('R',5,'R',10),_match(wa_diam,_cat('O',5,'O',10),0))) if (_eq(_index(_cat('M',5,'M',8),_match(wa_grado,_cat('K',5,'K',8),0)),'A')) else (_index(_cat('S',5,'S',10),_match(wa_diam,_cat('O',5,'O',10),0))))"),
    (62, '2. ALMA (apernado)', 'n', 'Pernos por lado = nr·nc', '-', 'w_n', '(wa_nr*wa_nc)'),
    (63, '2. ALMA (apernado)', 'e', 'gap/2 + Le + (nr − 1)·sv/2 (a lo largo de la columna)', 'cm', 'w_e', '(((gap/20)+(wa_Le/10))+((((wa_nr-1))*wa_sv)/20))'),
    (64, '2. ALMA (apernado)', 'Ip', 'Σx² + Σy²', 'cm²', 'w_Ip', '(((((wa_nr*(((wa_sh/10))**2))*wa_nc)*(((wa_nc**2)-1)))/12)+((((wa_nc*(((wa_sv/10))**2))*wa_nr)*(((wa_nr**2)-1)))/12))'),
    (65, '2. ALMA (apernado)', 'xmáx', 'sh·(nc − 1)/2', 'cm', 'w_xm', '(((wa_sh/10)*((wa_nc-1)))/2)'),
    (66, '2. ALMA (apernado)', 'ymáx', 'sv·(nr − 1)/2', 'cm', 'w_ym', '(((wa_sv/10)*((wa_nr-1)))/2)'),
    (67, '2. ALMA (apernado)', 'φrn', 'Por perno (2 planos)', 'kgf', 'w_rv', '((((((1*j_mu)*1.13)*wa_Tb)*2)) if (_eq(j_sc,1)) else ((((0.75*wa_Fnv)*wa_Ab)*2)))'),
    (68, '2. ALMA (apernado)', 'φrn,v', 'Corte del perno (2 planos)', 'kgf', 'w_rvs', '(((0.75*wa_Fnv)*wa_Ab)*2)'),
    (69, '2. ALMA (apernado)', 'φrn', 'Aplastamiento por perno: mín(alma de columna superior ; 2 placas)', 'kgf', 'w_rb', '((0.75*_min((1.2*_min(((wa_Le/10)-(wa_dh/2)),((wa_sv/10)-wa_dh),((((wa_sh/10)-wa_dh)) if ((wa_nc>1)) else (1000)))),(2.4*wa_db)))*_min((u_tw*cu_Fu),(((2*pw_t)/10)*pw_Fu)))'),
    (70, '2. ALMA (apernado)', 'φVn', 'Placas: fluencia por corte 1.00·0.6·Fy·2·b·t', 'kgf', 'w_vy', '((((((0.6*pw_Fy)*2)*pw_b)/10)*pw_t)/10)'),
    (71, '2. ALMA (apernado)', 'φVn', 'Placas: ruptura por corte 0.75·0.6·Fu·2·(b − nc·dh,n)·t', 'kgf', 'w_vr', '((((((0.75*0.6)*pw_Fu)*2)*(((pw_b/10)-(wa_nc*wa_dn))))*pw_t)/10)'),
    (72, '2. ALMA (apernado)', 'φRn', 'Placas: axial 0.90·Fy·2·b·t', 'kgf', 'w_ay', '((((((0.9*pw_Fy)*2)*pw_b)/10)*pw_t)/10)'),
    (74, '3. SOLDADURAS PJP / CJP — Tabla J2.5', 'FEXX', 'Electrodo', 'kgf/cm²', 's_FEXX', "_index(_cat('V',5,'V',6),_match(sd_elec,_cat('U',5,'U',6),0))"),
    (75, '3. SOLDADURAS PJP / CJP — Tabla J2.5', 'φRn', 'Alas, tracción normal: PJP mín(0.80·0.6·FEXX ; 0.75·Fu)·E·bf ; CJP 0.90·Fy·bf·tf', 'kgf', 's_Rft', '(((((0.9*k_Fy)*u_bf)*u_tf)) if (_eq(t_cjp,1)) else ((((_min(((0.8*0.6)*s_FEXX),(0.75*k_Fu))*E_f)/10)*u_bf)))'),
    (76, '3. SOLDADURAS PJP / CJP — Tabla J2.5', 'φRn', 'Alas, compresión (sin fresar): PJP mín(0.80·0.6·FEXX ; 0.90·Fy)·E·bf ; CJP 0.90·Fy·bf·tf', 'kgf', 's_Rfc', '(((((0.9*k_Fy)*u_bf)*u_tf)) if (_eq(t_cjp,1)) else ((((_min(((0.8*0.6)*s_FEXX),(0.9*k_Fy))*E_f)/10)*u_bf)))'),
    (77, '3. SOLDADURAS PJP / CJP — Tabla J2.5', 'φRn', 'Alma, corte: PJP 0.75·0.6·FEXX·E·(d − 2tf) ; CJP 1.00·0.6·Fy·tw·(d − 2tf)', 'kgf', 's_Rwv', '(((((0.6*k_Fy)*u_tw)*((u_d-(2*u_tf))))) if (_eq(t_cjp,1)) else ((((((0.75*0.6)*s_FEXX)*E_w)/10)*((u_d-(2*u_tf))))))'),
    (78, '3. SOLDADURAS PJP / CJP — Tabla J2.5', 'Emín', 'Garganta mínima PJP (Tabla J2.3) según el ala más delgada', 'mm', 's_Emin', '((3) if ((_min(cu_tf_mm,cl_tf_mm)<=6)) else (((5) if ((_min(cu_tf_mm,cl_tf_mm)<=13)) else (((6) if ((_min(cu_tf_mm,cl_tf_mm)<=19)) else (((8) if ((_min(cu_tf_mm,cl_tf_mm)<=38)) else (10))))))))'),
    (81, '4. VERIFICACIÓN POR COMBINACIÓN', 'Símbolo', 'Descripción', 'Unidad', 'g81', '1'),
]

COMBO = [  # (fila, sección, símbolo, descripción, unidad, expresión); IDX_ = nº de combinación
    (82, '4. VERIFICACIÓN POR COMBINACIÓN', 'Combo', 'Nombre', '', "(('') if (_eq(_index(cb_nom,IDX_),'')) else (_index(cb_nom,IDX_)))"),
    (83, '4. VERIFICACIÓN POR COMBINACIÓN', 'Pu', 'Axial (+ compresión)', 'kgf', '(_n(_index(cb_P,IDX_))*1000)'),
    (84, '4. VERIFICACIÓN POR COMBINACIÓN', 'Mu', '|Momento|', 'kgf·cm', '(abs(_n(_index(cb_M,IDX_)))*100000)'),
    (85, '4. VERIFICACIÓN POR COMBINACIÓN', 'Vu', '|Cortante|', 'kgf', '(abs(_n(_index(cb_V,IDX_)))*1000)'),
    (86, '4. VERIFICACIÓN POR COMBINACIÓN', 'activo', 'Combinación con cargas', '-', '((1) if ((((abs(r83)+r84)+r85)>0)) else (0))'),
    (87, '4. VERIFICACIÓN POR COMBINACIÓN', 'FM', 'Mu/(d − tf)', 'kgf', '(r84/((u_d-u_tf)))'),
    (88, '4. VERIFICACIÓN POR COMBINACIÓN', 'Pf', 'Pu·Af/A (+ compresión)', 'kgf', '((r83*u_Af)/u_A)'),
    (89, '4. VERIFICACIÓN POR COMBINACIÓN', 'T', 'Tracción en el ala: máx(0, FM − Pf)', 'kgf', '_max(0,(r87-r88))'),
    (90, '4. VERIFICACIÓN POR COMBINACIÓN', 'C', 'Compresión en el ala a transmitir por el empalme: 0 si fresado ; máx(0, FM + Pf)', 'kgf', '((0) if (_eq(k_fr,1)) else (_max(0,(r87+r88))))'),
    (91, '4. VERIFICACIÓN POR COMBINACIÓN', 'Fp', 'Fuerza de diseño del ala: máx(T ; C)', 'kgf', '_max(r89,r90)'),
    (92, '4. VERIFICACIÓN POR COMBINACIÓN', 'Pw', 'Axial en el alma a transmitir: tracción, o compresión si no está fresado', 'kgf', '(((((-r83)*u_Aw)/u_A)) if ((r83<0)) else (((0) if (_eq(k_fr,1)) else (((r83*u_Aw)/u_A)))))'),
    (93, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Apoyo por contacto (fresado, Pu > 0)', '-', '(((r83/k_Rbe)) if (_and(_eq(k_fr,1),(r83>0))) else (0))'),
    (94, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de ala: corte / deslizamiento', '-', '((_max((r91/((f_nb*f_rv))),(r91/((f_nb*f_rvs))))) if (_eq(t_ap,1)) else (0))'),
    (95, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de ala: aplastamiento', '-', '(((r91/((f_nb*_min(f_rbc,f_rbp))))) if (_eq(t_ap,1)) else (0))'),
    (96, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placa de ala: fluencia', '-', '(((r89/p_ty)) if (_eq(t_ap,1)) else (0))'),
    (97, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placa de ala: ruptura', '-', '(((r89/p_tr)) if (_eq(t_ap,1)) else (0))'),
    (98, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placa de ala: bloque de cortante', '-', '(((r91/p_bs)) if (_eq(t_ap,1)) else (0))'),
    (99, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placa de ala: compresión (sin fresar)', '-', '(((r90/p_cb)) if (_eq(t_ap,1)) else (0))'),
    (100, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Ala de columna superior: ruptura neta', '-', '(((r89/c_tr)) if (_eq(t_ap,1)) else (0))'),
    (101, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Ala de columna superior: bloque de cortante', '-', '(((r91/c_bs)) if (_eq(t_ap,1)) else (0))'),
    (102, '4. VERIFICACIÓN POR COMBINACIÓN', 'Mw', 'Momento en grupo de alma = Vu·e', 'kgf·cm', '(r85*w_e)'),
    (103, '4. VERIFICACIÓN POR COMBINACIÓN', 'rmáx', 'Perno crítico de alma: √((V/n + M·ymáx/Ip)² + (M·xmáx/Ip + Pw/n)²)', 'kgf', '_sqrt((((((r85/w_n)+((r102*w_ym)/_max(w_Ip,1e-09))))**2)+(((((r102*w_xm)/_max(w_Ip,1e-09))+(r92/w_n)))**2)))'),
    (104, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de alma: corte / deslizamiento', '-', '((_max((r103/w_rv),(r103/w_rvs))) if (_eq(t_ap,1)) else (0))'),
    (105, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de alma: aplastamiento', '-', '(((r103/w_rb)) if (_eq(t_ap,1)) else (0))'),
    (106, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de alma: corte y axial', '-', '((_max((r85/_min(w_vy,w_vr)),(r92/w_ay))) if (_eq(t_ap,1)) else (0))'),
    (107, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Soldadura de alas (×2 si PJP sísmico)', '-', '((0) if (_eq(t_ap,1)) else (_max(((k_s2*r89)/s_Rft),((k_s2*r90)/s_Rfc))))'),
    (108, '4. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Soldadura de alma a corte (×2 si PJP sísmico)', '-', '((0) if (_eq(t_ap,1)) else (((k_s2*r85)/s_Rwv)))'),
    (109, '4. VERIFICACIÓN POR COMBINACIÓN', 'máx.', 'Ratio máximo', '-', '_max(r93,r94,r95,r96,r97,r98,r99,r100,r101,r104,r105,r106,r107,r108)'),
]

RATIO_COL = 'S'  # columna de ratio de la tabla de verificaciones
DEM_COL, CAP_COL = 'P', 'Q'
CHECKS = [  # (fila, tipo, nombre, referencia, unidad, demanda, capacidad, ratio, combo)
    (11, 'GRUPO', 'APOYO Y ALAS', '', '', None, None, None, None),
    (12, 'CHEQUEO', 'Apoyo por contacto (superficies fresadas)', 'J1.4 · J7(a)', 'Tonf', "(('—') if (_eq(k_fr,0)) else ((_index(_row(83),_match(_max(_row(93)),_row(93),0))/1000)))", "(('—') if (_eq(k_fr,0)) else ((k_Rbe/1000)))", "(('N/A') if (_eq(k_fr,0)) else (_max(_row(93))))", "((_index(_row(82),_match(_max(_row(93)),_row(93),0))) if (_isnum(DIS_S12)) else ('—'))"),
    (13, 'CHEQUEO', 'Pernos de ala — corte / deslizamiento (con relleno)', 'J3.6 · J3.8 · J5.2', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(91),_match(_max(_row(94)),_row(94),0))/1000)))", "(('—') if (_eq(t_ap,0)) else (((f_nb*_min(f_rv,f_rvs))/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(94))))", "((_index(_row(82),_match(_max(_row(94)),_row(94),0))) if (_isnum(DIS_S13)) else ('—'))"),
    (14, 'CHEQUEO', 'Pernos de ala — aplastamiento / desgarre', 'J3.10', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(91),_match(_max(_row(95)),_row(95),0))/1000)))", "(('—') if (_eq(t_ap,0)) else (((f_nb*_min(f_rbc,f_rbp))/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(95))))", "((_index(_row(82),_match(_max(_row(95)),_row(95),0))) if (_isnum(DIS_S14)) else ('—'))"),
    (15, 'CHEQUEO', 'Placa de ala — fluencia en tracción', 'J4.1(a)', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(89),_match(_max(_row(96)),_row(96),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((p_ty/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(96))))", "((_index(_row(82),_match(_max(_row(96)),_row(96),0))) if (_isnum(DIS_S15)) else ('—'))"),
    (16, 'CHEQUEO', 'Placa de ala — ruptura en tracción', 'J4.1(b)', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(89),_match(_max(_row(97)),_row(97),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((p_tr/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(97))))", "((_index(_row(82),_match(_max(_row(97)),_row(97),0))) if (_isnum(DIS_S16)) else ('—'))"),
    (17, 'CHEQUEO', 'Placa de ala — bloque de cortante', 'J4.3', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(91),_match(_max(_row(98)),_row(98),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((p_bs/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(98))))", "((_index(_row(82),_match(_max(_row(98)),_row(98),0))) if (_isnum(DIS_S17)) else ('—'))"),
    (18, 'CHEQUEO', 'Placa de ala — compresión (sin fresar)', 'J4.4 / E3', 'Tonf', "(('—') if (_or(_eq(t_ap,0),_eq(k_fr,1))) else ((_index(_row(90),_match(_max(_row(99)),_row(99),0))/1000)))", "(('—') if (_or(_eq(t_ap,0),_eq(k_fr,1))) else ((p_cb/1000)))", "(('N/A') if (_or(_eq(t_ap,0),_eq(k_fr,1))) else (_max(_row(99))))", "((_index(_row(82),_match(_max(_row(99)),_row(99),0))) if (_isnum(DIS_S18)) else ('—'))"),
    (19, 'CHEQUEO', 'Ala de columna superior — ruptura neta', 'J4.1(b)', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(89),_match(_max(_row(100)),_row(100),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((c_tr/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(100))))", "((_index(_row(82),_match(_max(_row(100)),_row(100),0))) if (_isnum(DIS_S19)) else ('—'))"),
    (20, 'CHEQUEO', 'Ala de columna superior — bloque de cortante', 'J4.3', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(91),_match(_max(_row(101)),_row(101),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((c_bs/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(101))))", "((_index(_row(82),_match(_max(_row(101)),_row(101),0))) if (_isnum(DIS_S20)) else ('—'))"),
    (21, 'GRUPO', 'ALMA', '', '', None, None, None, None),
    (22, 'CHEQUEO', 'Pernos de alma — corte / deslizamiento', 'J3.6 · J3.8', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(103),_match(_max(_row(104)),_row(104),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((_min(w_rv,w_rvs)/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(104))))", "((_index(_row(82),_match(_max(_row(104)),_row(104),0))) if (_isnum(DIS_S22)) else ('—'))"),
    (23, 'CHEQUEO', 'Pernos de alma — aplastamiento / desgarre', 'J3.10', 'Tonf', "(('—') if (_eq(t_ap,0)) else ((_index(_row(103),_match(_max(_row(105)),_row(105),0))/1000)))", "(('—') if (_eq(t_ap,0)) else ((w_rb/1000)))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(105))))", "((_index(_row(82),_match(_max(_row(105)),_row(105),0))) if (_isnum(DIS_S23)) else ('—'))"),
    (24, 'CHEQUEO', 'Placas de alma — corte y axial', 'J4.1 · J4.2', '-', "(('—') if (_eq(t_ap,0)) else ((_index(_row(106),_match(_max(_row(106)),_row(106),0))/1)))", "(('—') if (_eq(t_ap,0)) else (1))", "(('N/A') if (_eq(t_ap,0)) else (_max(_row(106))))", "((_index(_row(82),_match(_max(_row(106)),_row(106),0))) if (_isnum(DIS_S24)) else ('—'))"),
    (25, 'GRUPO', 'SOLDADURAS (PJP / CJP)', '', '', None, None, None, None),
    (26, 'CHEQUEO', 'Alas — tracción / compresión', 'Tabla J2.5 · 341 D2.5b', '-', "(('—') if (_eq(t_ap,1)) else ((_index(_row(107),_match(_max(_row(107)),_row(107),0))/1)))", "(('—') if (_eq(t_ap,1)) else (1))", "(('N/A') if (_eq(t_ap,1)) else (_max(_row(107))))", "((_index(_row(82),_match(_max(_row(107)),_row(107),0))) if (_isnum(DIS_S26)) else ('—'))"),
    (27, 'CHEQUEO', 'Alma — corte', 'Tabla J2.5 · 341 D2.5b', 'Tonf', "(('—') if (_eq(t_ap,1)) else ((_index(_row(85),_match(_max(_row(108)),_row(108),0))/1000)))", "(('—') if (_eq(t_ap,1)) else (((s_Rwv/1000)/k_s2)))", "(('N/A') if (_eq(t_ap,1)) else (_max(_row(108))))", "((_index(_row(82),_match(_max(_row(108)),_row(108),0))) if (_isnum(DIS_S27)) else ('—'))"),
    (28, 'CHEQUEO', 'PJP: garganta alas ≥ mínima', 'Tabla J2.3', 'mm', "(('—') if (_eq(t_pjp,0)) else (s_Emin))", "(('—') if (_eq(t_pjp,0)) else (E_f))", "(('N/A') if (_eq(t_pjp,0)) else (((s_Emin)/_max(E_f,1e-09))))", "'—'"),
    (29, 'CHEQUEO', 'PJP: garganta alma ≥ mínima', 'Tabla J2.3', 'mm', "(('—') if (_eq(t_pjp,0)) else (((3) if ((_min(cu_tw_mm,cl_tw_mm)<=6)) else (((5) if ((_min(cu_tw_mm,cl_tw_mm)<=13)) else (6))))))", "(('—') if (_eq(t_pjp,0)) else (E_w))", "(('N/A') if (_eq(t_pjp,0)) else (((((3) if ((_min(cu_tw_mm,cl_tw_mm)<=6)) else (((5) if ((_min(cu_tw_mm,cl_tw_mm)<=13)) else (6)))))/_max(E_w,1e-09))))", "'—'"),
    (30, 'CHEQUEO', 'PJP: garganta ≤ espesor del ala', 'Geometría', 'mm', "(('—') if (_eq(t_pjp,0)) else (E_f))", "(('—') if (_eq(t_pjp,0)) else (_min(cu_tf_mm,cl_tf_mm)))", "(('N/A') if (_eq(t_pjp,0)) else (((E_f)/_max(_min(cu_tf_mm,cl_tf_mm),1e-09))))", "'—'"),
    (31, 'GRUPO', 'REQUISITOS Y DETALLES (requerido / provisto)', '', '', None, None, None, None),
    (32, 'CHEQUEO', 'Ubicación ≥ 1.2 m de la conexión viga-columna', '341 D2.5a', 'mm', "(('—') if (_eq(sismico,'No')) else (1200))", "(('—') if (_eq(sismico,'No')) else (dist_v))", "(('N/A') if (_eq(sismico,'No')) else (((1200)/_max(dist_v,1e-09))))", "'—'"),
    (33, 'CHEQUEO', 'Solape de alas para apoyo directo (si no, placa de tope)', 'Manual Parte 14', 'cm', "(('—') if (_eq(k_fr,0)) else (_max(0,(((l_d-u_d))/2))))", "(('—') if (_eq(k_fr,0)) else (_min(u_tf,l_tf)))", "(('N/A') if (_eq(k_fr,0)) else (((1.5) if ((k_ov<=0)) else ((_max(0,(abs((l_d-u_d))/2))/_max(_min(u_tf,l_tf),1e-09))))))", "'—'"),
    (34, 'CHEQUEO', 'Relleno ≤ 19 mm (J5.2; si no, desarrollar el relleno)', 'J5.2', 'mm', "(('—') if (_eq(t_ap,0)) else (fill_t))", "(('—') if (_eq(t_ap,0)) else (19))", "(('N/A') if (_eq(t_ap,0)) else (((fill_t)/_max(19,1e-09))))", "'—'"),
    (35, 'CHEQUEO', 'Placa de ala ≤ ancho de ala de la columna menor', 'Geometría', 'cm', "(('—') if (_eq(t_ap,0)) else ((pf_b/10)))", "(('—') if (_eq(t_ap,0)) else (_min(u_bf,l_bf)))", "(('N/A') if (_eq(t_ap,0)) else ((((pf_b/10))/_max(_min(u_bf,l_bf),1e-09))))", "'—'"),
    (36, 'CHEQUEO', 'Paso s ≥ 3·db (ala)', 'J3.3', 'cm', "(('—') if (_eq(t_ap,0)) else ((3*fa_db)))", "(('—') if (_eq(t_ap,0)) else ((fa_s/10)))", "(('N/A') if (_eq(t_ap,0)) else ((((3*fa_db))/_max((fa_s/10),1e-09))))", "'—'"),
    (37, 'CHEQUEO', 'Borde en columna ≥ mínimo (ala)', 'J3.4', 'cm', "(('—') if (_eq(t_ap,0)) else (fa_em))", "(('—') if (_eq(t_ap,0)) else ((fa_Lec/10)))", "(('N/A') if (_eq(t_ap,0)) else (((fa_em)/_max((fa_Lec/10),1e-09))))", "'—'"),
    (38, 'CHEQUEO', 'Borde en placa ≥ mínimo (ala)', 'J3.4', 'cm', "(('—') if (_eq(t_ap,0)) else (fa_em))", "(('—') if (_eq(t_ap,0)) else ((fa_Lep/10)))", "(('N/A') if (_eq(t_ap,0)) else (((fa_em)/_max((fa_Lep/10),1e-09))))", "'—'"),
    (39, 'CHEQUEO', 'Borde lateral de placa (b − g)/2', 'J3.4', 'cm', "(('—') if (_eq(t_ap,0)) else (fa_em))", "(('—') if (_eq(t_ap,0)) else ((((pf_b-fa_g))/20)))", "(('N/A') if (_eq(t_ap,0)) else (((fa_em)/_max((((pf_b-fa_g))/20),1e-09))))", "'—'"),
    (40, 'CHEQUEO', 'Gramil deja espacio a la llave junto al alma', 'Geometría', 'cm', "(('—') if (_eq(t_ap,0)) else ((1.5*fa_db)))", "(('—') if (_eq(t_ap,0)) else (((fa_g/20)-(u_tw/2))))", "(('N/A') if (_eq(t_ap,0)) else ((((1.5*fa_db))/_max(((fa_g/20)-(u_tw/2)),1e-09))))", "'—'"),
    (41, 'CHEQUEO', 'Placa de alma cabe entre alas', 'Geometría', 'cm', "(('—') if (_eq(t_ap,0)) else ((pw_b/10)))", "(('—') if (_eq(t_ap,0)) else ((u_d-(2*((u_tf+0.6))))))", "(('N/A') if (_eq(t_ap,0)) else ((((pw_b/10))/_max((u_d-(2*((u_tf+0.6)))),1e-09))))", "'—'"),
    (42, 'CHEQUEO', 'Paso sv ≥ 3·db (alma)', 'J3.3', 'cm', "(('—') if (_eq(t_ap,0)) else ((3*wa_db)))", "(('—') if (_eq(t_ap,0)) else ((wa_sv/10)))", "(('N/A') if (_eq(t_ap,0)) else ((((3*wa_db))/_max((wa_sv/10),1e-09))))", "'—'"),
    (43, 'CHEQUEO', 'Borde en alma / placa ≥ mínimo', 'J3.4', 'cm', "(('—') if (_eq(t_ap,0)) else (wa_em))", "(('—') if (_eq(t_ap,0)) else (_min((wa_Le/10),((((pw_b/10)-((((wa_nc-1))*wa_sh)/10)))/2))))", "(('N/A') if (_eq(t_ap,0)) else (((wa_em)/_max(_min((wa_Le/10),((((pw_b/10)-((((wa_nc-1))*wa_sh)/10)))/2)),1e-09))))", "'—'"),
    (44, 'CHEQUEO', 'Aviso SMF: empalmes de columna AISC 341 E3.6g', '341 E3.6g', '-', "(('—') if ((not _eq(sismico,'Sí (SMF)'))) else (0))", "(('—') if ((not _eq(sismico,'Sí (SMF)'))) else (1))", "(('N/A') if ((not _eq(sismico,'Sí (SMF)'))) else (((0) if (_eq(t_cjp,1)) else (0.95))))", "'—'"),
]
