"""Modelo generado por tools/xl2py.py — NO editar a mano (regenerar desde la hoja de Excel)."""

NCOMBO = 10

DERIVED = [  # (fila, nombre, etiqueta, unidad, expresión)  — fórmulas de la hoja DISEÑO
    (12, 'vg_d_mm', 'Peralte d', 'mm', "((DIS_E12) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (13, 'vg_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E13) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (14, 'vg_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E14) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (15, 'vg_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E15) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (17, 'vg_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(vg_acero,_cat('G',5,'G',10),0))"),
    (17, 'vg_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(vg_acero,_cat('G',5,'G',10),0))"),
    (25, 'pf_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(pf_acero,_cat('G',5,'G',10),0))"),
    (25, 'pf_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(pf_acero,_cat('G',5,'G',10),0))"),
    (41, 'pw_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(pw_acero,_cat('G',5,'G',10),0))"),
    (41, 'pw_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(pw_acero,_cat('G',5,'G',10),0))"),
]

GLOBAL = [  # (fila, sección, símbolo, descripción, unidad, nombre, expresión)  — hoja CALCULO
    (5, '0. GEOMETRÍA', 'd', 'Peralte', 'cm', 'b_d', '(vg_d_mm/10)'),
    (6, '0. GEOMETRÍA', 'bf', 'Ala', 'cm', 'b_bf', '(vg_bf_mm/10)'),
    (7, '0. GEOMETRÍA', 'tw', 'Alma', 'cm', 'b_tw', '(vg_tw_mm/10)'),
    (8, '0. GEOMETRÍA', 'tf', 'Ala', 'cm', 'b_tf', '(vg_tf_mm/10)'),
    (9, '0. GEOMETRÍA', 'k', 'tf + filete', 'cm', 'b_k', '(b_tf+(vg_kw/10))'),
    (10, '0. GEOMETRÍA', 'Ix', '[bf·d³ − (bf − tw)(d − 2tf)³]/12', 'cm⁴', 'b_Ix', '((((b_bf*(b_d**3))-(((b_bf-b_tw))*(((b_d-(2*b_tf)))**3))))/12)'),
    (11, '0. GEOMETRÍA', 'Sx', 'Ix/(d/2)', 'cm³', 'b_Sx', '(b_Ix/((b_d/2)))'),
    (12, '0. GEOMETRÍA', 'Iw', 'tw·(d − 2tf)³/12', 'cm⁴', 'b_Iw', '((b_tw*(((b_d-(2*b_tf)))**3))/12)'),
    (13, '0. GEOMETRÍA', 'gap', 'Holgura', 'cm', 'k_gap', '(gap/10)'),
    (14, '0. GEOMETRÍA', 'E', 'Módulo de elasticidad', 'kgf/cm²', 'k_E', '2040000'),
    (15, '0. GEOMETRÍA', 'SC', '1 = deslizamiento crítico', '-', 'j_sc', "((1) if (_eq(_s(junta)[:int(3)],'Des')) else (0))"),
    (16, '0. GEOMETRÍA', 'μ', '0.30 clase A ; 0.50 clase B', '-', 'j_mu', "((0.5) if (_eq(_s(junta)[-int(5):],'0.50)')) else (0.3))"),
    (17, '0. GEOMETRÍA', 'int.', '1 = placas interiores', '-', 'j_in', "((1) if (_eq(pf_in,'Sí')) else (0))"),
    (19, '1. PERNOS Y PLACAS DE ALA', 'db', 'Diámetro pernos de ala', 'in', 'fa_dbi', "_index(_cat('P',5,'P',10),_match(fa_diam,_cat('O',5,'O',10),0))"),
    (20, '1. PERNOS Y PLACAS DE ALA', 'db', 'Diámetro pernos de ala', 'cm', 'fa_db', '(fa_dbi*2.54)'),
    (21, '1. PERNOS Y PLACAS DE ALA', 'Ab', 'π·db²/4', 'cm²', 'fa_Ab', '((math.pi*(fa_db**2))/4)'),
    (22, '1. PERNOS Y PLACAS DE ALA', 'dh', 'Agujero estándar (Tabla J3.3)', 'cm', 'fa_dh', '((((fa_dbi+(1/16))) if ((fa_dbi<1)) else ((fa_dbi+(1/8))))*2.54)'),
    (23, '1. PERNOS Y PLACAS DE ALA', 'dh,net', 'dh + 1/16 in (B4.3b)', 'cm', 'fa_dn', '(fa_dh+0.15875)'),
    (24, '1. PERNOS Y PLACAS DE ALA', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'fa_em', "(_index(_cat('Q',5,'Q',10),_match(fa_diam,_cat('O',5,'O',10),0))*2.54)"),
    (25, '1. PERNOS Y PLACAS DE ALA', 'Fnv', 'Resistencia a corte', 'kgf/cm²', 'fa_Fnv', "_index(_cat('L',5,'L',8),_match(fa_grado,_cat('K',5,'K',8),0))"),
    (26, '1. PERNOS Y PLACAS DE ALA', 'Tb', 'Pretensión mínima (Tabla J3.1)', 'kgf', 'fa_Tb', "((_index(_cat('R',5,'R',10),_match(fa_diam,_cat('O',5,'O',10),0))) if (_eq(_index(_cat('M',5,'M',8),_match(fa_grado,_cat('K',5,'K',8),0)),'A')) else (_index(_cat('S',5,'S',10),_match(fa_diam,_cat('O',5,'O',10),0))))"),
    (27, '1. PERNOS Y PLACAS DE ALA', 'n', 'Pernos por ala por lado = 2·filas', '-', 'f_nb', '(2*fa_n)'),
    (28, '1. PERNOS Y PLACAS DE ALA', 'ns', 'Planos de corte', '-', 'f_ns', '(1+j_in)'),
    (29, '1. PERNOS Y PLACAS DE ALA', 'φrn', 'Por perno: aplastamiento 0.75·Fnv·Ab·ns ; deslizamiento 1.0·μ·1.13·Tb·ns', 'kgf', 'f_rv', '((((((1*j_mu)*1.13)*fa_Tb)*f_ns)) if (_eq(j_sc,1)) else ((((0.75*fa_Fnv)*fa_Ab)*f_ns)))'),
    (30, '1. PERNOS Y PLACAS DE ALA', 'φrn,v', 'Corte del perno (se verifica también en juntas de deslizamiento crítico)', 'kgf', 'f_rvs', '(((0.75*fa_Fnv)*fa_Ab)*f_ns)'),
    (31, '1. PERNOS Y PLACAS DE ALA', 'Lc,ala', 'mín(Le,viga − dh/2 ; s − dh)', 'cm', 'f_Lcb', '_min(((fa_Leb/10)-(fa_dh/2)),((fa_s/10)-fa_dh))'),
    (32, '1. PERNOS Y PLACAS DE ALA', 'Lc,placa', 'mín(Le,placa − dh/2 ; s − dh)', 'cm', 'f_Lcp', '_min(((fa_Lep/10)-(fa_dh/2)),((fa_s/10)-fa_dh))'),
    (33, '1. PERNOS Y PLACAS DE ALA', 'φrn', 'Aplastamiento por perno en el ala: 0.75·mín(1.2Lc ; 2.4db)·tf·Fu', 'kgf', 'f_rbb', '(((0.75*_min((1.2*f_Lcb),(2.4*fa_db)))*b_tf)*vg_Fu)'),
    (34, '1. PERNOS Y PLACAS DE ALA', 'φrn', 'Aplastamiento por perno en placas (exterior + interior)', 'kgf', 'f_rbp', '((((0.75*_min((1.2*f_Lcp),(2.4*fa_db)))*((pf_to+(j_in*pf_ti))))/10)*pf_Fu)'),
    (35, '1. PERNOS Y PLACAS DE ALA', 'Ag', 'bo·to + 2·bi·ti', 'cm²', 'p_Ag', '((((pf_bo/10)*pf_to)/10)+(((((j_in*2)*pf_bi)/10)*pf_ti)/10))'),
    (36, '1. PERNOS Y PLACAS DE ALA', 'An', 'mín([bo − 2dh,n]·to + 2[bi − dh,n]·ti ; 0.85Ag)', 'cm²', 'p_An', '_min(((((((pf_bo/10)-(2*fa_dn)))*pf_to)/10)+((((j_in*2)*(((pf_bi/10)-fa_dn)))*pf_ti)/10)),(0.85*p_Ag))'),
    (37, '1. PERNOS Y PLACAS DE ALA', 'φRn', 'Fluencia en tracción 0.90·Fy·Ag', 'kgf', 'p_ty', '((0.9*pf_Fy)*p_Ag)'),
    (38, '1. PERNOS Y PLACAS DE ALA', 'φRn', 'Ruptura en tracción 0.75·Fu·An (J4.1)', 'kgf', 'p_tr', '((0.75*pf_Fu)*p_An)'),
    (39, '1. PERNOS Y PLACAS DE ALA', 'φRn', 'Bloque de cortante de placas: mín(bloques exteriores ; central) exterior + interiores (J4.3)', 'kgf', 'p_bs', '(_min((0.75*((((_min(((0.6*pf_Fu)*(((2*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*pf_Fy)*2)*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10)))))*pf_to)/10)+((((pf_Fu*2)*((((((pf_bo/10)-(fa_g/10)))/2)-(fa_dn/2))))*pf_to)/10)))),(0.75*((((_min(((0.6*pf_Fu)*(((2*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*pf_Fy)*2)*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10)))))*pf_to)/10)+(((pf_Fu*(((fa_g/10)-fa_dn)))*pf_to)/10)))))+((j_in*0.75)*((((_min(((0.6*pf_Fu)*(((2*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*pf_Fy)*2)*(((fa_Lep/10)+((((fa_n-1))*fa_s)/10)))))*pf_ti)/10)+((((pf_Fu*2)*(((((b_bf-(fa_g/10)))/2)-(fa_dn/2))))*pf_ti)/10)))))'),
    (40, '1. PERNOS Y PLACAS DE ALA', 'KL/r', '0.65·(gap + 2·Le,viga)/(t,mín/√12)', '-', 'p_KLr', '((0.65*((k_gap+((2*fa_Leb)/10))))/(((((_min(pf_to,pf_ti)) if (_eq(j_in,1)) else (pf_to))/10)/_sqrt(12))))'),
    (41, '1. PERNOS Y PLACAS DE ALA', 'Fcr', 'KL/r ≤ 25: Fy ; si no Cap. E', 'kgf/cm²', 'p_Fcr', '((pf_Fy) if ((p_KLr<=25)) else (((((0.658**((pf_Fy/((((math.pi**2)*k_E)/(p_KLr**2))))))*pf_Fy)) if (((pf_Fy/((((math.pi**2)*k_E)/(p_KLr**2))))<=2.25)) else ((((0.877*(math.pi**2))*k_E)/(p_KLr**2))))))'),
    (42, '1. PERNOS Y PLACAS DE ALA', 'φPn', 'Compresión de placas 0.90·Fcr·Ag (J4.4)', 'kgf', 'p_cb', '((0.9*p_Fcr)*p_Ag)'),
    (43, '1. PERNOS Y PLACAS DE ALA', 'φRn', 'Bloque de cortante del ala de viga (bloques exteriores)', 'kgf', 'b_bs', '(0.75*(((_min(((0.6*vg_Fu)*(((2*(((fa_Leb/10)+((((fa_n-1))*fa_s)/10))))-((2*((fa_n-0.5)))*fa_dn)))),(((0.6*vg_Fy)*2)*(((fa_Leb/10)+((((fa_n-1))*fa_s)/10)))))*b_tf)+(((vg_Fu*2)*(((((b_bf-(fa_g/10)))/2)-(fa_dn/2))))*b_tf))))'),
    (44, '1. PERNOS Y PLACAS DE ALA', 'Yt', 'F13.1: 1.0 si Fy/Fu ≤ 0.8 ; 1.1', '-', 'b_Yt', '((1) if (((vg_Fy/vg_Fu)<=0.8)) else (1.1))'),
    (45, '1. PERNOS Y PLACAS DE ALA', 'Afn', '(bf − 2dh,n)·tf', 'cm²', 'b_Afn', '(((b_bf-(2*fa_dn)))*b_tf)'),
    (46, '1. PERNOS Y PLACAS DE ALA', 'aplica', '1 si Fu·Afn < Yt·Fy·Afg (F13.1 limita Mn)', '-', 'b_F13', '((1) if (((vg_Fu*b_Afn)<(((b_Yt*vg_Fy)*b_bf)*b_tf))) else (0))'),
    (47, '1. PERNOS Y PLACAS DE ALA', 'φMn', '0.90·Fu·Afn/Afg·Sx (F13.1)', 'kgf·cm', 'b_MnF', '((((0.9*vg_Fu)*b_Afn)/((b_bf*b_tf)))*b_Sx)'),
    (49, '2. PERNOS Y PLACAS DE ALMA', 'db', 'Diámetro pernos de alma', 'in', 'wa_dbi', "_index(_cat('P',5,'P',10),_match(wa_diam,_cat('O',5,'O',10),0))"),
    (50, '2. PERNOS Y PLACAS DE ALMA', 'db', 'Diámetro pernos de alma', 'cm', 'wa_db', '(wa_dbi*2.54)'),
    (51, '2. PERNOS Y PLACAS DE ALMA', 'Ab', 'π·db²/4', 'cm²', 'wa_Ab', '((math.pi*(wa_db**2))/4)'),
    (52, '2. PERNOS Y PLACAS DE ALMA', 'dh', 'Agujero estándar (Tabla J3.3)', 'cm', 'wa_dh', '((((wa_dbi+(1/16))) if ((wa_dbi<1)) else ((wa_dbi+(1/8))))*2.54)'),
    (53, '2. PERNOS Y PLACAS DE ALMA', 'dh,net', 'dh + 1/16 in (B4.3b)', 'cm', 'wa_dn', '(wa_dh+0.15875)'),
    (54, '2. PERNOS Y PLACAS DE ALMA', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'wa_em', "(_index(_cat('Q',5,'Q',10),_match(wa_diam,_cat('O',5,'O',10),0))*2.54)"),
    (55, '2. PERNOS Y PLACAS DE ALMA', 'Fnv', 'Resistencia a corte', 'kgf/cm²', 'wa_Fnv', "_index(_cat('L',5,'L',8),_match(wa_grado,_cat('K',5,'K',8),0))"),
    (56, '2. PERNOS Y PLACAS DE ALMA', 'Tb', 'Pretensión mínima (Tabla J3.1)', 'kgf', 'wa_Tb', "((_index(_cat('R',5,'R',10),_match(wa_diam,_cat('O',5,'O',10),0))) if (_eq(_index(_cat('M',5,'M',8),_match(wa_grado,_cat('K',5,'K',8),0)),'A')) else (_index(_cat('S',5,'S',10),_match(wa_diam,_cat('O',5,'O',10),0))))"),
    (57, '2. PERNOS Y PLACAS DE ALMA', 'n', 'Pernos por lado = nr·nc', '-', 'w_n', '(wa_nr*wa_nc)'),
    (58, '2. PERNOS Y PLACAS DE ALMA', 'e', 'gap/2 + Le,viga + (nc − 1)·sh/2', 'cm', 'w_e', '(((k_gap/2)+(wa_Leb/10))+(((((wa_nc-1))*wa_sh)/10)/2))'),
    (59, '2. PERNOS Y PLACAS DE ALMA', 'Ip', 'Σx² + Σy²', 'cm²', 'w_Ip', '(((((wa_nr*(((wa_sh/10))**2))*wa_nc)*(((wa_nc**2)-1)))/12)+((((wa_nc*(((wa_sv/10))**2))*wa_nr)*(((wa_nr**2)-1)))/12))'),
    (60, '2. PERNOS Y PLACAS DE ALMA', 'xmáx', 'sh·(nc − 1)/2', 'cm', 'w_xm', '(((wa_sh/10)*((wa_nc-1)))/2)'),
    (61, '2. PERNOS Y PLACAS DE ALMA', 'ymáx', 'sv·(nr − 1)/2', 'cm', 'w_ym', '(((wa_sv/10)*((wa_nr-1)))/2)'),
    (62, '2. PERNOS Y PLACAS DE ALMA', 'φrn', 'Por perno (2 planos): 0.75·Fnv·Ab·2 ; deslizamiento 1.0·μ·1.13·Tb·2', 'kgf', 'w_rv', '((((((1*j_mu)*1.13)*wa_Tb)*2)) if (_eq(j_sc,1)) else ((((0.75*wa_Fnv)*wa_Ab)*2)))'),
    (63, '2. PERNOS Y PLACAS DE ALMA', 'φrn,v', 'Corte del perno (2 planos)', 'kgf', 'w_rvs', '(((0.75*wa_Fnv)*wa_Ab)*2)'),
    (64, '2. PERNOS Y PLACAS DE ALMA', 'Lc,alma', 'mín(Le,viga − dh/2 ; sv − dh ; sh − dh)', 'cm', 'w_Lcw', '_min(((wa_Leb/10)-(wa_dh/2)),((wa_sv/10)-wa_dh),((((wa_sh/10)-wa_dh)) if ((wa_nc>1)) else (1000)))'),
    (65, '2. PERNOS Y PLACAS DE ALMA', 'Lc,placa', 'mín(borde horiz. − dh/2 ; borde vert. − dh/2 ; pasos − dh)', 'cm', 'w_Lcp', '_min(((wa_Lep/10)-(wa_dh/2)),(((((pw_h/10)-((((wa_nr-1))*wa_sv)/10)))/2)-(wa_dh/2)),((wa_sv/10)-wa_dh),((((wa_sh/10)-wa_dh)) if ((wa_nc>1)) else (1000)))'),
    (66, '2. PERNOS Y PLACAS DE ALMA', 'φrn', 'Aplastamiento por perno en el alma', 'kgf', 'w_rbw', '(((0.75*_min((1.2*w_Lcw),(2.4*wa_db)))*b_tw)*vg_Fu)'),
    (67, '2. PERNOS Y PLACAS DE ALMA', 'φrn', 'Aplastamiento por perno en las 2 placas', 'kgf', 'w_rbp', '(((((0.75*_min((1.2*w_Lcp),(2.4*wa_db)))*2)*pw_t)/10)*pw_Fu)'),
    (68, '2. PERNOS Y PLACAS DE ALMA', 'φVn', 'Placas: fluencia por corte 1.00·0.6·Fy·2·hp·t', 'kgf', 'w_vy', '((((((0.6*pw_Fy)*2)*pw_h)/10)*pw_t)/10)'),
    (69, '2. PERNOS Y PLACAS DE ALMA', 'φVn', 'Placas: ruptura por corte 0.75·0.6·Fu·2·(hp − nr·dh,n)·t', 'kgf', 'w_vr', '((((((0.75*0.6)*pw_Fu)*2)*(((pw_h/10)-(wa_nr*wa_dn))))*pw_t)/10)'),
    (70, '2. PERNOS Y PLACAS DE ALMA', 'φMn', 'Placas: 0.90·Fy·2·t·hp²/4', 'kgf·cm', 'w_Mn', '((((((0.9*pw_Fy)*2)*pw_t)/10)*(((pw_h/10))**2))/4)'),
    (71, '2. PERNOS Y PLACAS DE ALMA', 'φRn', 'Bloque de cortante de placas de alma (2), J4.3', 'kgf', 'w_bs', '((2*0.75)*((((_min(((0.6*pw_Fu)*((((((((pw_h/10)-((((wa_nr-1))*wa_sv)/10)))/2)+((((wa_nr-1))*wa_sv)/10)))-(((wa_nr-0.5))*wa_dn)))),((0.6*pw_Fy)*((((((pw_h/10)-((((wa_nr-1))*wa_sv)/10)))/2)+((((wa_nr-1))*wa_sv)/10)))))*pw_t)/10)+(((pw_Fu*((((wa_Lep/10)+((((wa_nc-1))*wa_sh)/10))-(((wa_nc-0.5))*wa_dn))))*pw_t)/10))))'),
    (72, '2. PERNOS Y PLACAS DE ALMA', 'φVn', 'Alma de viga: ruptura por corte en la línea de pernos 0.75·0.6·Fu·tw·(d − nr·dh,n)', 'kgf', 'w_bvr', '((((0.75*0.6)*vg_Fu)*b_tw)*((b_d-(wa_nr*wa_dn))))'),
    (75, '3. VERIFICACIÓN POR COMBINACIÓN', 'Símbolo', 'Descripción', 'Unidad', 'g75', '1'),
]

COMBO = [  # (fila, sección, símbolo, descripción, unidad, expresión); IDX_ = nº de combinación
    (76, '3. VERIFICACIÓN POR COMBINACIÓN', 'Combo', 'Nombre', '', "(('') if (_eq(_index(cb_nom,IDX_),'')) else (_index(cb_nom,IDX_)))"),
    (77, '3. VERIFICACIÓN POR COMBINACIÓN', 'Mu', '|Momento|', 'kgf·cm', '(abs(_n(_index(cb_M,IDX_)))*100000)'),
    (78, '3. VERIFICACIÓN POR COMBINACIÓN', 'Vu', '|Cortante|', 'kgf', '(abs(_n(_index(cb_V,IDX_)))*1000)'),
    (79, '3. VERIFICACIÓN POR COMBINACIÓN', 'activo', 'Combinación con cargas', '-', '((1) if (((r77+r78)>0)) else (0))'),
    (80, '3. VERIFICACIÓN POR COMBINACIÓN', 'Mw', 'Momento en el alma', 'kgf·cm', "((((r77*b_Iw)/b_Ix)) if (_eq(_s(dist_M)[:int(2)],'Sí')) else (0))"),
    (81, '3. VERIFICACIÓN POR COMBINACIÓN', 'Ff', '(Mu − Mw)/(d − tf)', 'kgf', '(((r77-r80))/((b_d-b_tf)))'),
    (82, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de ala: corte o deslizamiento', '-', '_max((r81/((f_nb*f_rv))),(r81/((f_nb*f_rvs))))'),
    (83, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de ala: aplastamiento (ala y placas)', '-', '(r81/((f_nb*_min(f_rbb,f_rbp))))'),
    (84, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de ala: fluencia', '-', '(r81/p_ty)'),
    (85, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de ala: ruptura', '-', '(r81/p_tr)'),
    (86, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de ala: bloque de cortante', '-', '(r81/p_bs)'),
    (87, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de ala: compresión', '-', '(r81/p_cb)'),
    (88, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Ala de viga: bloque de cortante', '-', '(r81/b_bs)'),
    (89, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Viga: F13.1 (agujeros en el ala en tracción)', '-', '(((r77/b_MnF)) if (_eq(b_F13,1)) else (0))'),
    (90, '3. VERIFICACIÓN POR COMBINACIÓN', 'Mt', 'Momento en el grupo de alma = Vu·e + Mw', 'kgf·cm', '((r78*w_e)+r80)'),
    (91, '3. VERIFICACIÓN POR COMBINACIÓN', 'rmáx', 'Perno crítico de alma (elástico)', 'kgf', '_sqrt((((((r90*w_ym)/_max(w_Ip,1e-09)))**2)+((((r78/w_n)+((r90*w_xm)/_max(w_Ip,1e-09))))**2)))'),
    (92, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de alma: corte o deslizamiento', '-', '_max((r91/w_rv),(r91/w_rvs))'),
    (93, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Pernos de alma: aplastamiento', '-', '(r91/_min(w_rbw,w_rbp))'),
    (94, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de alma: fluencia y ruptura por corte', '-', '(r78/_min(w_vy,w_vr))'),
    (95, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de alma: (V/φVn)² + (M/φMn)²', '-', '((((r78/w_vy))**2)+(((r90/w_Mn))**2))'),
    (96, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Placas de alma: bloque de cortante', '-', '(r78/w_bs)'),
    (97, '3. VERIFICACIÓN POR COMBINACIÓN', 'ratio', 'Alma de viga: ruptura por corte', '-', '(r78/w_bvr)'),
    (98, '3. VERIFICACIÓN POR COMBINACIÓN', 'máx.', 'Ratio máximo', '-', '_max(r82,r83,r84,r85,r86,r87,r88,r89,r92,r93,r94,r95,r96,r97)'),
]

RATIO_COL = 'S'  # columna de ratio de la tabla de verificaciones
DEM_COL, CAP_COL = 'P', 'Q'
CHECKS = [  # (fila, tipo, nombre, referencia, unidad, demanda, capacidad, ratio, combo)
    (11, 'GRUPO', 'ALAS', '', '', None, None, None, None),
    (12, 'CHEQUEO', 'Pernos de ala — corte / deslizamiento', 'J3.6 / J3.8', 'Tonf', '(_index(_row(81),_match(_max(_row(82)),_row(82),0))/1000)', '((f_nb*_min(f_rv,f_rvs))/1000)', '_max(_row(82))', "((_index(_row(76),_match(_max(_row(82)),_row(82),0))) if (_isnum(DIS_S12)) else ('—'))"),
    (13, 'CHEQUEO', 'Pernos de ala — aplastamiento / desgarre', 'J3.10', 'Tonf', '(_index(_row(81),_match(_max(_row(83)),_row(83),0))/1000)', '((f_nb*_min(f_rbb,f_rbp))/1000)', '_max(_row(83))', "((_index(_row(76),_match(_max(_row(83)),_row(83),0))) if (_isnum(DIS_S13)) else ('—'))"),
    (14, 'CHEQUEO', 'Placas de ala — fluencia en tracción', 'J4.1(a)', 'Tonf', '(_index(_row(81),_match(_max(_row(84)),_row(84),0))/1000)', '(p_ty/1000)', '_max(_row(84))', "((_index(_row(76),_match(_max(_row(84)),_row(84),0))) if (_isnum(DIS_S14)) else ('—'))"),
    (15, 'CHEQUEO', 'Placas de ala — ruptura en tracción', 'J4.1(b)', 'Tonf', '(_index(_row(81),_match(_max(_row(85)),_row(85),0))/1000)', '(p_tr/1000)', '_max(_row(85))', "((_index(_row(76),_match(_max(_row(85)),_row(85),0))) if (_isnum(DIS_S15)) else ('—'))"),
    (16, 'CHEQUEO', 'Placas de ala — bloque de cortante', 'J4.3', 'Tonf', '(_index(_row(81),_match(_max(_row(86)),_row(86),0))/1000)', '(p_bs/1000)', '_max(_row(86))', "((_index(_row(76),_match(_max(_row(86)),_row(86),0))) if (_isnum(DIS_S16)) else ('—'))"),
    (17, 'CHEQUEO', 'Placas de ala — compresión', 'J4.4 / E3', 'Tonf', '(_index(_row(81),_match(_max(_row(87)),_row(87),0))/1000)', '(p_cb/1000)', '_max(_row(87))', "((_index(_row(76),_match(_max(_row(87)),_row(87),0))) if (_isnum(DIS_S17)) else ('—'))"),
    (18, 'CHEQUEO', 'Ala de viga — bloque de cortante', 'J4.3', 'Tonf', '(_index(_row(81),_match(_max(_row(88)),_row(88),0))/1000)', '(b_bs/1000)', '_max(_row(88))', "((_index(_row(76),_match(_max(_row(88)),_row(88),0))) if (_isnum(DIS_S18)) else ('—'))"),
    (19, 'CHEQUEO', 'Viga — agujeros en el ala en tracción', 'F13.1', 'Tonf·m', "(('—') if (_eq(b_F13,0)) else ((_index(_row(77),_match(_max(_row(89)),_row(89),0))/100000)))", "(('—') if (_eq(b_F13,0)) else ((b_MnF/100000)))", "(('N/A') if (_eq(b_F13,0)) else (_max(_row(89))))", "((_index(_row(76),_match(_max(_row(89)),_row(89),0))) if (_isnum(DIS_S19)) else ('—'))"),
    (20, 'GRUPO', 'ALMA', '', '', None, None, None, None),
    (21, 'CHEQUEO', 'Pernos de alma — corte / deslizamiento (perno crítico)', 'J3.6 / J3.8', 'Tonf', '(_index(_row(91),_match(_max(_row(92)),_row(92),0))/1000)', '(_min(w_rv,w_rvs)/1000)', '_max(_row(92))', "((_index(_row(76),_match(_max(_row(92)),_row(92),0))) if (_isnum(DIS_S21)) else ('—'))"),
    (22, 'CHEQUEO', 'Pernos de alma — aplastamiento / desgarre', 'J3.10', 'Tonf', '(_index(_row(91),_match(_max(_row(93)),_row(93),0))/1000)', '(_min(w_rbw,w_rbp)/1000)', '_max(_row(93))', "((_index(_row(76),_match(_max(_row(93)),_row(93),0))) if (_isnum(DIS_S22)) else ('—'))"),
    (23, 'CHEQUEO', 'Placas de alma — corte', 'J4.2', 'Tonf', '(_index(_row(78),_match(_max(_row(94)),_row(94),0))/1000)', '(_min(w_vy,w_vr)/1000)', '_max(_row(94))', "((_index(_row(76),_match(_max(_row(94)),_row(94),0))) if (_isnum(DIS_S23)) else ('—'))"),
    (24, 'CHEQUEO', 'Placas de alma — corte + flexión', 'Manual Ec. 10-5', '-', '(_index(_row(95),_match(_max(_row(95)),_row(95),0))/1)', '1', '_max(_row(95))', "((_index(_row(76),_match(_max(_row(95)),_row(95),0))) if (_isnum(DIS_S24)) else ('—'))"),
    (25, 'CHEQUEO', 'Placas de alma — bloque de cortante', 'J4.3', 'Tonf', '(_index(_row(78),_match(_max(_row(96)),_row(96),0))/1000)', '(w_bs/1000)', '_max(_row(96))', "((_index(_row(76),_match(_max(_row(96)),_row(96),0))) if (_isnum(DIS_S25)) else ('—'))"),
    (26, 'CHEQUEO', 'Alma de viga — ruptura por corte', 'J4.2(b)', 'Tonf', '(_index(_row(78),_match(_max(_row(97)),_row(97),0))/1000)', '(w_bvr/1000)', '_max(_row(97))', "((_index(_row(76),_match(_max(_row(97)),_row(97),0))) if (_isnum(DIS_S26)) else ('—'))"),
    (27, 'GRUPO', 'DETALLES (requerido / provisto)', '', '', None, None, None, None),
    (28, 'CHEQUEO', 'Paso de ala s ≥ 3·db', 'J3.3', 'cm', '(3*fa_db)', '(fa_s/10)', '(((3*fa_db))/_max((fa_s/10),1e-09))', "'—'"),
    (29, 'CHEQUEO', 'Borde en ala de viga ≥ mínimo', 'J3.4', 'cm', 'fa_em', '(fa_Leb/10)', '((fa_em)/_max((fa_Leb/10),1e-09))', "'—'"),
    (30, 'CHEQUEO', 'Borde en placa de ala ≥ mínimo', 'J3.4', 'cm', 'fa_em', '(fa_Lep/10)', '((fa_em)/_max((fa_Lep/10),1e-09))', "'—'"),
    (31, 'CHEQUEO', 'Borde lateral placa exterior (bo − g)/2', 'J3.4', 'cm', 'fa_em', '(((pf_bo-fa_g))/20)', '((fa_em)/_max((((pf_bo-fa_g))/20),1e-09))', "'—'"),
    (32, 'CHEQUEO', 'Borde lateral ala de viga (bf − g)/2', 'J3.4', 'cm', 'fa_em', '(((b_bf-(fa_g/10)))/2)', '((fa_em)/_max((((b_bf-(fa_g/10)))/2),1e-09))', "'—'"),
    (33, 'CHEQUEO', 'Placa interior cabe junto al alma: bi ≤ (bf − tw)/2 − filete', 'Geometría', 'cm', "(('—') if (_eq(j_in,0)) else ((pf_bi/10)))", "(('—') if (_eq(j_in,0)) else (((((b_bf-b_tw))/2)-(vg_kw/10))))", "(('N/A') if (_eq(j_in,0)) else ((((pf_bi/10))/_max(((((b_bf-b_tw))/2)-(vg_kw/10)),1e-09))))", "'—'"),
    (34, 'CHEQUEO', 'Gramil deja espacio a la llave junto al alma: g/2 − tw/2 ≥ 1.5·db', 'Geometría', 'cm', '(1.5*fa_db)', '((fa_g/20)-(b_tw/2))', '(((1.5*fa_db))/_max(((fa_g/20)-(b_tw/2)),1e-09))', "'—'"),
    (35, 'CHEQUEO', 'Placa de alma cabe entre alas / placas interiores', 'Geometría', 'cm', '(pw_h/10)', '((b_d-(2*(((b_tf+(pf_ti/10))) if (_eq(j_in,1)) else (b_k))))-1)', '(((pw_h/10))/_max(((b_d-(2*(((b_tf+(pf_ti/10))) if (_eq(j_in,1)) else (b_k))))-1),1e-09))', "'—'"),
    (36, 'CHEQUEO', 'Paso de alma sv ≥ 3·db', 'J3.3', 'cm', '(3*wa_db)', '(wa_sv/10)', '(((3*wa_db))/_max((wa_sv/10),1e-09))', "'—'"),
    (37, 'CHEQUEO', 'Borde en alma de viga ≥ mínimo', 'J3.4', 'cm', 'wa_em', '(wa_Leb/10)', '((wa_em)/_max((wa_Leb/10),1e-09))', "'—'"),
    (38, 'CHEQUEO', 'Borde horizontal placa de alma ≥ mínimo', 'J3.4', 'cm', 'wa_em', '(wa_Lep/10)', '((wa_em)/_max((wa_Lep/10),1e-09))', "'—'"),
    (39, 'CHEQUEO', 'Borde vertical placa de alma ≥ mínimo', 'J3.4', 'cm', 'wa_em', '((((pw_h/10)-((((wa_nr-1))*wa_sv)/10)))/2)', '((wa_em)/_max(((((pw_h/10)-((((wa_nr-1))*wa_sv)/10)))/2),1e-09))', "'—'"),
]
