"""Modelo generado por tools/xl2py.py — NO editar a mano (regenerar desde la hoja de Excel)."""

NCOMBO = 0

DERIVED = [  # (fila, nombre, etiqueta, unidad, expresión)  — fórmulas de la hoja DISEÑO
    (16, 'vg_d_mm', 'Peralte d', 'mm', "((DIS_E16) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (17, 'vg_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E17) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (18, 'vg_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E18) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (19, 'vg_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E19) if (_eq(vg_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(vg_perfil,_cat('A',5,'A',40),0))))"),
    (21, 'vg_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(vg_acero,_cat('G',5,'G',10),0))"),
    (21, 'vg_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(vg_acero,_cat('G',5,'G',10),0))"),
    (29, 'vp_d_mm', 'Peralte d', 'mm', "((DIS_E29) if (_eq(vp_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('B',5,'B',40),_match(vp_perfil,_cat('A',5,'A',40),0))))"),
    (30, 'vp_bf_mm', 'Ancho de ala bf', 'mm', "((DIS_E30) if (_eq(vp_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('C',5,'C',40),_match(vp_perfil,_cat('A',5,'A',40),0))))"),
    (31, 'vp_tw_mm', 'Espesor de alma tw', 'mm', "((DIS_E31) if (_eq(vp_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('D',5,'D',40),_match(vp_perfil,_cat('A',5,'A',40),0))))"),
    (32, 'vp_tf_mm', 'Espesor de ala tf', 'mm', "((DIS_E32) if (_eq(vp_perfil,'ARMADO (flejes soldados)')) else (_index(_cat('E',5,'E',40),_match(vp_perfil,_cat('A',5,'A',40),0))))"),
    (34, 'vp_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(vp_acero,_cat('G',5,'G',10),0))"),
    (34, 'vp_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(vp_acero,_cat('G',5,'G',10),0))"),
    (45, 'pl_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(pl_acero,_cat('G',5,'G',10),0))"),
    (45, 'pl_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(pl_acero,_cat('G',5,'G',10),0))"),
    (53, 'an_Fy', 'Fy / Fu', 'kgf/cm²', "_index(_cat('H',5,'H',10),_match(an_acero,_cat('G',5,'G',10),0))"),
    (53, 'an_Fu', 'Fy / Fu', 'kgf/cm²', "_index(_cat('I',5,'I',10),_match(an_acero,_cat('G',5,'G',10),0))"),
]

GLOBAL = [  # (fila, sección, símbolo, descripción, unidad, nombre, expresión)  — hoja CALCULO
    (5, '0. TIPO, GEOMETRÍA Y MATERIALES', 'conv.', '1 = placa simple convencional', '-', 't_sp', "((1) if (_eq(tipo,'Placa simple convencional')) else (0))"),
    (6, '0. TIPO, GEOMETRÍA Y MATERIALES', 'ext.', '1 = placa simple extendida', '-', 't_se', "((1) if (_eq(tipo,'Placa simple extendida')) else (0))"),
    (7, '0. TIPO, GEOMETRÍA Y MATERIALES', '2L', '1 = doble ángulo', '-', 't_da', "((1) if (_eq(tipo,'Doble ángulo apernado')) else (0))"),
    (8, '0. TIPO, GEOMETRÍA Y MATERIALES', 'placa', '1 = placa simple (conv. o ext.)', '-', 't_pl', '(t_sp+t_se)'),
    (9, '0. TIPO, GEOMETRÍA Y MATERIALES', 'E', 'Módulo de elasticidad', 'kgf/cm²', 'k_E', '2040000'),
    (10, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Ru', 'Reacción factorada', 'kgf', 'k_R', '(Ru*1000)'),
    (11, '0. TIPO, GEOMETRÍA Y MATERIALES', 'd', 'd (cm)', 'cm', 'b_d', '(vg_d_mm/10)'),
    (12, '0. TIPO, GEOMETRÍA Y MATERIALES', 'bf', 'bf (cm)', 'cm', 'b_bf', '(vg_bf_mm/10)'),
    (13, '0. TIPO, GEOMETRÍA Y MATERIALES', 'tw', 'tw (cm)', 'cm', 'b_tw', '(vg_tw_mm/10)'),
    (14, '0. TIPO, GEOMETRÍA Y MATERIALES', 'tf', 'tf (cm)', 'cm', 'b_tf', '(vg_tf_mm/10)'),
    (15, '0. TIPO, GEOMETRÍA Y MATERIALES', 'dg', 'dg (cm)', 'cm', 'g_d', '(vp_d_mm/10)'),
    (16, '0. TIPO, GEOMETRÍA Y MATERIALES', 'bfg', 'bfg (cm)', 'cm', 'g_bf', '(vp_bf_mm/10)'),
    (17, '0. TIPO, GEOMETRÍA Y MATERIALES', 'twg', 'twg (cm)', 'cm', 'g_tw', '(vp_tw_mm/10)'),
    (18, '0. TIPO, GEOMETRÍA Y MATERIALES', 'tfg', 'tfg (cm)', 'cm', 'g_tf', '(vp_tf_mm/10)'),
    (19, '0. TIPO, GEOMETRÍA Y MATERIALES', 'k', 'tf + filete (viga soportada)', 'cm', 'b_k', '(b_tf+(vg_kw/10))'),
    (20, '0. TIPO, GEOMETRÍA Y MATERIALES', 'dct', 'Destaje superior', 'cm', 'c_top', "((0) if (_eq(destaje,'Sin destaje')) else ((cope_dc/10)))"),
    (21, '0. TIPO, GEOMETRÍA Y MATERIALES', 'dcb', 'Destaje inferior (destaje doble)', 'cm', 'c_bot', "(((cope_dc/10)) if (_eq(destaje,'Destaje doble (sup. = inf.)')) else (0))"),
    (22, '0. TIPO, GEOMETRÍA Y MATERIALES', 'c', 'Longitud del destaje', 'cm', 'c_c', "((0) if (_eq(destaje,'Sin destaje')) else ((cope_c/10)))"),
    (23, '0. TIPO, GEOMETRÍA Y MATERIALES', 'ho', 'Peralte remanente d − dct − dcb', 'cm', 'b_ho', '((b_d-c_top)-c_bot)'),
    (24, '0. TIPO, GEOMETRÍA Y MATERIALES', 'db', 'Diámetro', 'in', 'a_dbi', "_index(_cat('O',5,'O',9),_match(pn_diam,_cat('N',5,'N',9),0))"),
    (25, '0. TIPO, GEOMETRÍA Y MATERIALES', 'db', 'Diámetro', 'cm', 'a_db', '(a_dbi*2.54)'),
    (26, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Ab', 'π·db²/4', 'cm²', 'a_Ab', '((math.pi*(a_db**2))/4)'),
    (27, '0. TIPO, GEOMETRÍA Y MATERIALES', 'dh', 'Agujero estándar (Tabla J3.3)', 'cm', 'a_dh', '((((a_dbi+(1/16))) if ((a_dbi<1)) else ((a_dbi+(1/8))))*2.54)'),
    (28, '0. TIPO, GEOMETRÍA Y MATERIALES', 'dh,net', 'dh + 1/16 in (B4.3b)', 'cm', 'a_dn', '(a_dh+0.15875)'),
    (29, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Lslot', 'Longitud de ranura corta SSL (Tabla J3.3), si aplica', 'cm', 'a_sl', "((a_dh) if (_eq(agujero,'STD')) else (((((a_dbi+0.25)) if ((a_dbi<1)) else ((((a_dbi+(5/16))) if ((a_dbi<1.1)) else ((a_dbi+(3/8))))))*2.54)))"),
    (30, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Le,min', 'Borde mínimo (Tabla J3.4)', 'cm', 'a_emin', "(_index(_cat('P',5,'P',9),_match(pn_diam,_cat('N',5,'N',9),0))*2.54)"),
    (31, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Fnv', 'Resistencia nominal a corte del perno', 'kgf/cm²', 'a_Fnv', "_index(_cat('L',5,'L',9),_match(pn_grado,_cat('K',5,'K',9),0))"),
    (32, '0. TIPO, GEOMETRÍA Y MATERIALES', 's', 'Paso vertical', 'cm', 'a_s', '(pn_s/10)'),
    (33, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Lev', 'Borde vertical en placa / ángulo', 'cm', 'e_Lev', '(pn_Lev/10)'),
    (34, '0. TIPO, GEOMETRÍA Y MATERIALES', 'L', 'Largo de placa / ángulo = (n−1)s + 2Lev', 'cm', 'e_L', '((((n_b-1))*a_s)+(2*e_Lev))'),
    (35, '0. TIPO, GEOMETRÍA Y MATERIALES', 'ztop', 'Profundidad del borde superior de la placa/ángulo desde el tope de la viga', 'cm', 'e_top', '((pn_top/10)-e_Lev)'),
    (36, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Lev,b', 'Primer perno a borde superior del alma (destaje) ; sin destaje: no gobierna', 'cm', 'b_Lev', '((((pn_top/10)-c_top)) if ((c_top>0)) else (1000))'),
    (37, '0. TIPO, GEOMETRÍA Y MATERIALES', 't', 'Espesor del elemento (placa o ángulo)', 'cm', 'e_t', '(((pl_tp) if (_eq(t_pl,1)) else (an_t))/10)'),
    (38, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Fy,e', 'Fy del elemento', 'kgf/cm²', 'e_Fy', '((pl_Fy) if (_eq(t_pl,1)) else (an_Fy))'),
    (39, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Fu,e', 'Fu del elemento', 'kgf/cm²', 'e_Fu', '((pl_Fu) if (_eq(t_pl,1)) else (an_Fu))'),
    (40, '0. TIPO, GEOMETRÍA Y MATERIALES', 'xb', 'Alma de viga principal → línea de pernos de la viga (a | gramil lado viga)', 'cm', 'e_xb', '(((pl_a) if (_eq(t_pl,1)) else (an_gb))/10)'),
    (41, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Leh,e', 'Línea de pernos → borde del elemento', 'cm', 'e_Leh', '(((pl_Leh/10)) if (_eq(t_pl,1)) else ((((an_lb-an_gb))/10)))'),
    (42, '0. TIPO, GEOMETRÍA Y MATERIALES', 'Leh,b', 'Línea de pernos → extremo de la viga = xb − holgura', 'cm', 'b_Leh', '(e_xb-(setback/10))'),
    (44, '1. PERNOS — GRUPO LADO VIGA', 'e', 'Excentricidad: conv. Tabla 10-9 (SSLT o n ≤ 5: a/2 ; STD y n ≥ 6: a) ; ext.: a ; 2L: 0', 'cm', 'p_e', "(((((e_xb/2)) if (_or((not _eq(agujero,'STD')),(n_b<=5))) else (e_xb))) if (_eq(t_sp,1)) else (((e_xb) if (_eq(t_se,1)) else (0))))"),
    (45, '1. PERNOS — GRUPO LADO VIGA', 'Σy²', 's²·n(n²−1)/12', 'cm²', 'p_Sy2', '((((a_s**2)*n_b)*(((n_b**2)-1)))/12)'),
    (46, '1. PERNOS — GRUPO LADO VIGA', 'ymáx', 's(n−1)/2', 'cm', 'p_ym', '((a_s*((n_b-1)))/2)'),
    (47, '1. PERNOS — GRUPO LADO VIGA', 'rmáx', 'Fuerza en el perno crítico (elástico): Ru·√(1/n² + (e·ymáx/Σy²)²)', 'kgf', 'p_r', '(k_R*_sqrt(((1/(n_b**2))+((((p_e*p_ym)/_max(p_Sy2,1e-09)))**2))))'),
    (48, '1. PERNOS — GRUPO LADO VIGA', 'planos', 'Planos de corte lado viga (2 en doble ángulo)', '-', 'p_nsh', '((2) if (_eq(t_da,1)) else (1))'),
    (49, '1. PERNOS — GRUPO LADO VIGA', 'φrn,v', 'Corte por perno: 0.75·Fnv·Ab·planos (J3.6)', 'kgf', 'p_rv', '(((0.75*a_Fnv)*a_Ab)*p_nsh)'),
    (50, '1. PERNOS — GRUPO LADO VIGA', 'Lc,alma', 'Mínimo Lc en el alma: destaje, extremo (si hay excentricidad) y s − dh', 'cm', 'p_Lcw', '_min((b_Lev-(a_dh/2)),(((b_Leh-(a_dh/2))) if ((p_e>0)) else (1000)),(a_s-a_dh))'),
    (51, '1. PERNOS — GRUPO LADO VIGA', 'Lc,elem', 'Mínimo Lc en el elemento: borde inferior, borde horizontal (si hay excentricidad) y s − dh', 'cm', 'p_Lce', '_min((e_Lev-(a_dh/2)),(((e_Leh-(a_sl/2))) if ((p_e>0)) else (1000)),(a_s-a_dh))'),
    (52, '1. PERNOS — GRUPO LADO VIGA', 'φrn,alma', 'Aplastamiento/desgarre por perno en el alma: 0.75·mín(1.2Lc ; 2.4db)·tw·Fu', 'kgf', 'p_rbw', '(((0.75*_min((1.2*p_Lcw),(2.4*a_db)))*b_tw)*vg_Fu)'),
    (53, '1. PERNOS — GRUPO LADO VIGA', 'φrn,elem', 'Aplastamiento/desgarre por perno en el elemento (×2 en doble ángulo)', 'kgf', 'p_rbe', '((((0.75*_min((1.2*p_Lce),(2.4*a_db)))*e_t)*e_Fu)*((2) if (_eq(t_da,1)) else (1)))'),
    (55, '2. DOBLE ÁNGULO — LADO SOPORTE', 'φRn', '2n pernos a corte simple: 0.75·Fnv·Ab·2n', 'kgf', 'q_rv', '((((0.75*a_Fnv)*a_Ab)*2)*n_b)'),
    (56, '2. DOBLE ÁNGULO — LADO SOPORTE', 'φRn', 'Aplastamiento/desgarre en alas de soporte: 2·0.75·[mín(1.2(Lev−dh/2);2.4db) + (n−1)mín(1.2(s−dh);2.4db)]·t·Fu', 'kgf', 'q_rba', '(((((2*0.75)*((_min((1.2*((e_Lev-(a_dh/2)))),(2.4*a_db))+(((n_b-1))*_min((1.2*((a_s-a_dh))),(2.4*a_db))))))*an_t)/10)*an_Fu)'),
    (57, '2. DOBLE ÁNGULO — LADO SOPORTE', 'φRn', 'Aplastamiento en alma de viga principal: 2 líneas · n · 0.75·mín(1.2(s−dh);2.4db)·twg·Fu', 'kgf', 'q_rbg', '(((((2*n_b)*0.75)*_min((1.2*((a_s-a_dh))),(2.4*a_db)))*g_tw)*vp_Fu)'),
    (59, '3. ELEMENTO (PLACA O ÁNGULOS) — J4', 'nº', 'Número de elementos (2 en doble ángulo)', '-', 'm_n', '((2) if (_eq(t_da,1)) else (1))'),
    (60, '3. ELEMENTO (PLACA O ÁNGULOS) — J4', 'φRn', 'Fluencia por corte: 1.00·0.6·Fy·L·t·nº (J4.2a)', 'kgf', 'm_vy', '(((((1*0.6)*e_Fy)*e_L)*e_t)*m_n)'),
    (61, '3. ELEMENTO (PLACA O ÁNGULOS) — J4', 'φRn', 'Ruptura por corte: 0.75·0.6·Fu·(L − n·dh,net)·t·nº (J4.2b)', 'kgf', 'm_vr', '(((((0.75*0.6)*e_Fu)*((e_L-(n_b*a_dn))))*e_t)*m_n)'),
    (62, '3. ELEMENTO (PLACA O ÁNGULOS) — J4', 'φRn', 'Bloque de cortante del elemento, lado viga (J4.3, Ubs = 1)', 'kgf', 'm_bs', '((m_n*0.75)*((_min(((0.6*e_Fu)*((((((e_Lev)+(((n_b-1))*a_s)))*e_t)-((((n_b-0.5))*a_dn)*e_t)))),(((0.6*e_Fy)*(((e_Lev)+(((n_b-1))*a_s))))*e_t))+((e_Fu*(((e_Leh)-(0.5*(((a_sl+0.15875)) if (_eq(t_pl,1)) else (a_dn))))))*e_t))))'),
    (63, '3. ELEMENTO (PLACA O ÁNGULOS) — J4', 'φRn', 'Bloque de cortante de alas en el soporte (2L)', 'kgf', 'm_bso', '((2*0.75)*((_min(((0.6*an_Fu)*(((((((e_Lev)+(((n_b-1))*a_s)))*an_t)/10)-(((((n_b-0.5))*a_dn)*an_t)/10)))),((((0.6*an_Fy)*(((e_Lev)+(((n_b-1))*a_s))))*an_t)/10))+(((an_Fu*((((((an_ls-an_gs))/10))-(0.5*a_dn))))*an_t)/10))))'),
    (65, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'Mu', 'Ru·a', 'kgf·cm', 'x_Mu', '(k_R*e_xb)'),
    (66, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'φVn', '1.00·0.6·Fy·L·tp', 'kgf', 'x_Vc', '((((0.6*pl_Fy)*e_L)*pl_tp)/10)'),
    (67, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'φMn', '0.90·Fy·Zx, Zx = tp·L²/4', 'kgf·cm', 'x_Mc', '(((((0.9*pl_Fy)*pl_tp)/10)*(e_L**2))/4)'),
    (68, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'ratio', 'Interacción (Vr/Vc)² + (Mr/Mc)² ≤ 1 (Manual Ec. 10-5)', '-', 'x_int', '((((k_R/x_Vc))**2)+(((x_Mu/x_Mc))**2))'),
    (69, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'Znet', 'tp·L²/4 − tp·dh,net·s·ENT(n²/4)', 'cm³', 'x_Zn', '((pl_tp/10)*((((e_L**2)/4)-((a_dn*a_s)*math.floor(((n_b**2)/4))))))'),
    (70, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'φMn', 'Ruptura por flexión: 0.75·Fu·Znet', 'kgf·cm', 'x_Mr', '((0.75*pl_Fu)*x_Zn)'),
    (71, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'λ', 'Pandeo de placa (Parte 9, método Q): L·√Fy/(10·tp·√(475 + 280(L/a)²)) [Fy en ksi]', '-', 'x_lam', '((e_L*_sqrt((pl_Fy/70.307)))/((((10*pl_tp)/10)*_sqrt((475+(280*(((e_L/e_xb))**2)))))))'),
    (72, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'Q', 'λ ≤ 0.7: 1 ; ≤ 1.41: 1.34 − 0.486λ ; si no 1.30/λ²', '-', 'x_Q', '((1) if ((x_lam<=0.7)) else ((((1.34-(0.486*x_lam))) if ((x_lam<=1.41)) else ((1.3/(x_lam**2))))))'),
    (73, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'φMn', '0.90·Q·Fy·S, S = tp·L²/6', 'kgf·cm', 'x_Mb', '((((((0.9*x_Q)*pl_Fy)*pl_tp)/10)*(e_L**2))/6)'),
    (74, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'Mmáx', "(Fnv/0.90)·Ab·C', C' = Σy²/ymáx (elástico)", 'kgf·cm', 'x_Mmax', '((((a_Fnv/0.9)*a_Ab)*p_Sy2)/_max(p_ym,1e-09))'),
    (75, '4. PLACA SIMPLE EXTENDIDA — Manual Parte 10', 'tmáx', '6·Mmáx/(Fy·L²) (Manual Ec. 10-3)', 'cm', 'x_tmax', '((6*x_Mmax)/((pl_Fy*(e_L**2))))'),
    (77, '5. SOLDADURA Y VIGA PRINCIPAL (placa simple)', 'FEXX', 'Electrodo', 'kgf/cm²', 'w_FEXX', "_index(_cat('S',5,'S',6),_match(sd_elec,_cat('R',5,'R',6),0))"),
    (78, '5. SOLDADURA Y VIGA PRINCIPAL (placa simple)', 'φRn', 'Filetes (2): 0.75·0.6·FEXX·0.707·w·2L (J2.4)', 'kgf', 'w_R', '(((((((0.75*0.6)*w_FEXX)*0.707)*pl_w)/10)*2)*e_L)'),
    (79, '5. SOLDADURA Y VIGA PRINCIPAL (placa simple)', 'tmín', 'Alma de viga principal para desarrollar cada filete: 0.707·w·FEXX/Fu (Ec. 9-2); ×2 con placa opuesta (Ec. 9-3)', 'cm', 'w_tmin', '(((((0.707*pl_w)/10)*w_FEXX)/vp_Fu)*((2) if ((Ru_op>0)) else (1)))'),
    (81, '6. VIGA SOPORTADA — Manual Parte 9', 'φRn', 'Fluencia por corte del alma en ho: 1.00·0.6·Fy·ho·tw', 'kgf', 'v_vy', '(((0.6*vg_Fy)*b_ho)*b_tw)'),
    (82, '6. VIGA SOPORTADA — Manual Parte 9', 'φRn', 'Ruptura por corte del alma: 0.75·0.6·Fu·(ho − n·dh,net)·tw', 'kgf', 'v_vr', '((((0.75*0.6)*vg_Fu)*((b_ho-(n_b*a_dn))))*b_tw)'),
    (83, '6. VIGA SOPORTADA — Manual Parte 9', 'φRn', 'Bloque de cortante del alma con destaje superior (J4.3, Ubs = 1)', 'kgf', 'v_bs', '((1*0.75)*((_min(((0.6*vg_Fu)*((((((b_Lev)+(((n_b-1))*a_s)))*b_tw)-((((n_b-0.5))*a_dn)*b_tw)))),(((0.6*vg_Fy)*(((b_Lev)+(((n_b-1))*a_s))))*b_tw))+((vg_Fu*(((b_Leh)-(0.5*a_dn))))*b_tw))))'),
    (84, '6. VIGA SOPORTADA — Manual Parte 9', 'ȳ', 'Destaje sup.: centroide de la T (ala inf. + alma) medido desde la fibra inferior', 'cm', 'v_yb', '(((((b_bf*(b_tf**2))/2)+((b_tw*((b_ho-b_tf)))*((b_tf+(((b_ho-b_tf))/2))))))/(((b_bf*b_tf)+(b_tw*((b_ho-b_tf))))))'),
    (85, '6. VIGA SOPORTADA — Manual Parte 9', 'I', 'Inercia de la T', 'cm⁴', 'v_I', '(((((b_bf*(b_tf**3))/12)+((b_bf*b_tf)*(((v_yb-(b_tf/2)))**2)))+((b_tw*(((b_ho-b_tf))**3))/12))+((b_tw*((b_ho-b_tf)))*((((b_tf+(((b_ho-b_tf))/2))-v_yb))**2)))'),
    (86, '6. VIGA SOPORTADA — Manual Parte 9', 'Snet', 'Destaje sup.: I/(ho − ȳ) ; doble: tw·ho²/6', 'cm³', 'v_S', "((((b_tw*(b_ho**2))/6)) if (_eq(destaje,'Destaje doble (sup. = inf.)')) else ((v_I/((b_ho-v_yb)))))"),
    (87, '6. VIGA SOPORTADA — Manual Parte 9', 'f', 'Destaje sup.: c/d ≤ 1 → 2c/d ; si no 1 + c/d', '-', 'v_f', '((((2*c_c)/b_d)) if (((c_c/b_d)<=1)) else ((1+(c_c/b_d))))'),
    (88, '6. VIGA SOPORTADA — Manual Parte 9', 'k', 'Destaje sup.: c/ho ≤ 1 → 2.2(ho/c)^1.65 ; si no 2.2·ho/c', '-', 'v_k', '((0) if (_eq(c_c,0)) else ((((2.2*(((b_ho/c_c))**1.65))) if (((c_c/b_ho)<=1)) else (((2.2*b_ho)/c_c)))))'),
    (89, '6. VIGA SOPORTADA — Manual Parte 9', 'fd', 'Destaje doble: 3.5 − 7.5·dc/d', '-', 'v_fd', '(3.5-((7.5*c_top)/b_d))'),
    (90, '6. VIGA SOPORTADA — Manual Parte 9', 'Fcr', 'Sup.: 26 210·(tw/ho)²·f·k [ksi] ≤ Fy ; doble: 0.62·π·E·tw²·fd/(c·ho) ≤ Fy', 'kgf/cm²', 'v_Fcr', "((vg_Fy) if (_eq(c_c,0)) else (_min(vg_Fy,(((((((0.62*math.pi)*k_E)*(b_tw**2))*v_fd)/((c_c*b_ho)))) if (_eq(destaje,'Destaje doble (sup. = inf.)')) else (((((26210*70.307)*(((b_tw/b_ho))**2))*v_f)*v_k))))))"),
    (91, '6. VIGA SOPORTADA — Manual Parte 9', 'Mu', 'Ru·(c + holgura) en la cara del destaje', 'kgf·cm', 'v_Mu', '(k_R*((c_c+(setback/10))))'),
    (92, '6. VIGA SOPORTADA — Manual Parte 9', 'φMn', '0.90·Fcr·Snet', 'kgf·cm', 'v_Mn', '((0.9*v_Fcr)*v_S)'),
]

COMBO = [  # (fila, sección, símbolo, descripción, unidad, expresión); IDX_ = nº de combinación
]

RATIO_COL = 'R'  # columna de ratio de la tabla de verificaciones
DEM_COL, CAP_COL = 'P', 'Q'
CHECKS = [  # (fila, tipo, nombre, referencia, unidad, demanda, capacidad, ratio, combo)
    (11, 'GRUPO', 'PERNOS — LADO VIGA', '', '', None, None, None, None),
    (12, 'CHEQUEO', 'Corte en pernos (perno crítico)', 'J3.6 · grupo excéntrico elástico', 'Tonf', '(p_r/1000)', '(p_rv/1000)', '(((p_r/1000))/_max((p_rv/1000),1e-09))', "'—'"),
    (13, 'CHEQUEO', 'Aplastamiento / desgarre — alma de viga', 'J3.10', 'Tonf', '(p_r/1000)', '(p_rbw/1000)', '(((p_r/1000))/_max((p_rbw/1000),1e-09))', "'—'"),
    (14, 'CHEQUEO', 'Aplastamiento / desgarre — placa o ángulos', 'J3.10', 'Tonf', '(p_r/1000)', '(p_rbe/1000)', '(((p_r/1000))/_max((p_rbe/1000),1e-09))', "'—'"),
    (15, 'GRUPO', 'DOBLE ÁNGULO — LADO SOPORTE', '', '', None, None, None, None),
    (16, 'CHEQUEO', 'Corte en pernos (2n, corte simple)', 'J3.6', 'Tonf', "(('—') if (_eq(t_da,0)) else ((k_R/1000)))", "(('—') if (_eq(t_da,0)) else ((q_rv/1000)))", "(('N/A') if (_eq(t_da,0)) else ((((k_R/1000))/_max((q_rv/1000),1e-09))))", "'—'"),
    (17, 'CHEQUEO', 'Aplastamiento / desgarre — alas de ángulo', 'J3.10', 'Tonf', "(('—') if (_eq(t_da,0)) else ((k_R/1000)))", "(('—') if (_eq(t_da,0)) else ((q_rba/1000)))", "(('N/A') if (_eq(t_da,0)) else ((((k_R/1000))/_max((q_rba/1000),1e-09))))", "'—'"),
    (18, 'CHEQUEO', 'Aplastamiento — alma de viga principal', 'J3.10', 'Tonf', "(('—') if (_eq(t_da,0)) else ((((k_R+(Ru_op*1000)))/1000)))", "(('—') if (_eq(t_da,0)) else ((q_rbg/1000)))", "(('N/A') if (_eq(t_da,0)) else ((((((k_R+(Ru_op*1000)))/1000))/_max((q_rbg/1000),1e-09))))", "'—'"),
    (19, 'CHEQUEO', 'Bloque de cortante — alas en el soporte', 'J4.3', 'Tonf', "(('—') if (_eq(t_da,0)) else ((k_R/1000)))", "(('—') if (_eq(t_da,0)) else ((m_bso/1000)))", "(('N/A') if (_eq(t_da,0)) else ((((k_R/1000))/_max((m_bso/1000),1e-09))))", "'—'"),
    (20, 'GRUPO', 'PLACA / ÁNGULOS', '', '', None, None, None, None),
    (21, 'CHEQUEO', 'Fluencia por corte', 'J4.2(a)', 'Tonf', '(k_R/1000)', '(m_vy/1000)', '(((k_R/1000))/_max((m_vy/1000),1e-09))', "'—'"),
    (22, 'CHEQUEO', 'Ruptura por corte', 'J4.2(b)', 'Tonf', '(k_R/1000)', '(m_vr/1000)', '(((k_R/1000))/_max((m_vr/1000),1e-09))', "'—'"),
    (23, 'CHEQUEO', 'Bloque de cortante (lado viga)', 'J4.3', 'Tonf', '(k_R/1000)', '(m_bs/1000)', '(((k_R/1000))/_max((m_bs/1000),1e-09))', "'—'"),
    (24, 'CHEQUEO', 'Placa extendida — corte + flexión', 'Manual Ec. 10-5', '-', "(('—') if (_eq(t_se,0)) else (x_int))", "(('—') if (_eq(t_se,0)) else (1))", "(('N/A') if (_eq(t_se,0)) else (((x_int)/_max(1,1e-09))))", "'—'"),
    (25, 'CHEQUEO', 'Placa extendida — ruptura por flexión', 'Manual Parte 10', 'Tonf·m', "(('—') if (_eq(t_se,0)) else ((x_Mu/100000)))", "(('—') if (_eq(t_se,0)) else ((x_Mr/100000)))", "(('N/A') if (_eq(t_se,0)) else ((((x_Mu/100000))/_max((x_Mr/100000),1e-09))))", "'—'"),
    (26, 'CHEQUEO', 'Placa extendida — pandeo', 'Manual Parte 9 (método Q)', 'Tonf·m', "(('—') if (_eq(t_se,0)) else ((x_Mu/100000)))", "(('—') if (_eq(t_se,0)) else ((x_Mb/100000)))", "(('N/A') if (_eq(t_se,0)) else ((((x_Mu/100000))/_max((x_Mb/100000),1e-09))))", "'—'"),
    (27, 'GRUPO', 'SOLDADURA Y VIGA PRINCIPAL (placa simple)', '', '', None, None, None, None),
    (28, 'CHEQUEO', 'Resistencia de filetes placa – alma', 'J2.4', 'Tonf', "(('—') if (_eq(t_pl,0)) else ((k_R/1000)))", "(('—') if (_eq(t_pl,0)) else ((w_R/1000)))", "(('N/A') if (_eq(t_pl,0)) else ((((k_R/1000))/_max((w_R/1000),1e-09))))", "'—'"),
    (29, 'CHEQUEO', 'Filete ≥ 5/8·tp (ductilidad)', 'Manual Parte 10', 'mm', "(('—') if (_eq(t_pl,0)) else ((0.625*pl_tp)))", "(('—') if (_eq(t_pl,0)) else (pl_w))", "(('N/A') if (_eq(t_pl,0)) else ((((0.625*pl_tp))/_max(pl_w,1e-09))))", "'—'"),
    (30, 'CHEQUEO', 'Alma de viga principal: t ≥ tmín para los filetes', 'Manual Ec. 9-2/9-3', 'mm', "(('—') if (_eq(t_pl,0)) else ((w_tmin*10)))", "(('—') if (_eq(t_pl,0)) else (vp_tw_mm))", "(('N/A') if (_eq(t_pl,0)) else ((((w_tmin*10))/_max(vp_tw_mm,1e-09))))", "'—'"),
    (31, 'GRUPO', 'VIGA SOPORTADA (Manual Parte 9)', '', '', None, None, None, None),
    (32, 'CHEQUEO', 'Fluencia por corte del alma (ho)', 'J4.2(a)', 'Tonf', '(k_R/1000)', '(v_vy/1000)', '(((k_R/1000))/_max((v_vy/1000),1e-09))', "'—'"),
    (33, 'CHEQUEO', 'Ruptura por corte del alma', 'J4.2(b)', 'Tonf', '(k_R/1000)', '(v_vr/1000)', '(((k_R/1000))/_max((v_vr/1000),1e-09))', "'—'"),
    (34, 'CHEQUEO', 'Bloque de cortante del alma (con destaje)', 'J4.3', 'Tonf', "(('—') if (_eq(c_c,0)) else ((k_R/1000)))", "(('—') if (_eq(c_c,0)) else ((v_bs/1000)))", "(('N/A') if (_eq(c_c,0)) else ((((k_R/1000))/_max((v_bs/1000),1e-09))))", "'—'"),
    (35, 'CHEQUEO', 'Pandeo local por flexión en el destaje', 'Manual Parte 9', 'Tonf·m', "(('—') if (_eq(c_c,0)) else ((v_Mu/100000)))", "(('—') if (_eq(c_c,0)) else ((v_Mn/100000)))", "(('N/A') if (_eq(c_c,0)) else ((((v_Mu/100000))/_max((v_Mn/100000),1e-09))))", "'—'"),
    (36, 'GRUPO', 'LÍMITES Y DETALLES (requerido / provisto)', '', '', None, None, None, None),
    (37, 'CHEQUEO', 'Convencional: a ≤ 3.5 in (89 mm)', 'Manual Tabla 10-9', 'mm', "(('—') if (_eq(t_sp,0)) else (pl_a))", "(('—') if (_eq(t_sp,0)) else (88.9))", "(('N/A') if (_eq(t_sp,0)) else ((pl_a/88.9)))", "'—'"),
    (38, 'CHEQUEO', 'Placa simple: 2 ≤ n ≤ 12', 'Manual Parte 10', 'pernos', "(('—') if (_eq(t_pl,0)) else (n_b))", "(('—') if (_eq(t_pl,0)) else (12))", "(('N/A') if (_eq(t_pl,0)) else (_max((n_b/12),(2/n_b))))", "'—'"),
    (39, 'CHEQUEO', 'Convencional: mín(tp ; tw) ≤ tmáx', 'Manual Tabla 10-9', 'mm', "(('—') if (_eq(t_sp,0)) else (_min(pl_tp,vg_tw_mm)))", "(('—') if (_eq(t_sp,0)) else (((((a_dbi/2)+(((1/16)) if (_or((not _eq(agujero,'STD')),(n_b<=5))) else (((-1)/16)))))*25.4)))", "(('N/A') if (_eq(t_sp,0)) else (((_min(pl_tp,vg_tw_mm))/_max(((((a_dbi/2)+(((1/16)) if (_or((not _eq(agujero,'STD')),(n_b<=5))) else (((-1)/16)))))*25.4),1e-09))))", "'—'"),
    (40, 'CHEQUEO', 'Extendida: tp ≤ tmáx', 'Manual Ec. 10-3', 'mm', "(('—') if (_eq(t_se,0)) else (pl_tp))", "(('—') if (_eq(t_se,0)) else ((x_tmax*10)))", "(('N/A') if (_eq(t_se,0)) else (((pl_tp)/_max((x_tmax*10),1e-09))))", "'—'"),
    (41, 'CHEQUEO', 'Leh en placa ≥ 2·db', 'Manual Parte 10', 'cm', "(('—') if (_eq(t_pl,0)) else ((2*a_db)))", "(('—') if (_eq(t_pl,0)) else (e_Leh))", "(('N/A') if (_eq(t_pl,0)) else ((((2*a_db))/_max(e_Leh,1e-09))))", "'—'"),
    (42, 'CHEQUEO', 'Leh en alma de viga ≥ 2·db', 'Manual Parte 10', 'cm', "(('—') if (_eq(t_pl,0)) else ((2*a_db)))", "(('—') if (_eq(t_pl,0)) else (b_Leh))", "(('N/A') if (_eq(t_pl,0)) else ((((2*a_db))/_max(b_Leh,1e-09))))", "'—'"),
    (43, 'CHEQUEO', 'Leh en alma de viga ≥ borde mínimo', 'J3.4', 'cm', "(('—') if (_eq(t_pl,1)) else (a_emin))", "(('—') if (_eq(t_pl,1)) else (b_Leh))", "(('N/A') if (_eq(t_pl,1)) else (((a_emin)/_max(b_Leh,1e-09))))", "'—'"),
    (44, 'CHEQUEO', 'Leh en ángulos ≥ borde mínimo', 'J3.4', 'cm', "(('—') if (_eq(t_da,0)) else (a_emin))", "(('—') if (_eq(t_da,0)) else (_min(e_Leh,(((an_ls-an_gs))/10))))", "(('N/A') if (_eq(t_da,0)) else (((a_emin)/_max(_min(e_Leh,(((an_ls-an_gs))/10)),1e-09))))", "'—'"),
    (45, 'CHEQUEO', 'Borde vertical Lev (elemento)', 'J3.4', 'cm', 'a_emin', 'e_Lev', '((a_emin)/_max(e_Lev,1e-09))', "'—'"),
    (46, 'CHEQUEO', 'Borde vertical en alma (a destaje)', 'J3.4', 'cm', "(('—') if (_eq(c_c,0)) else (a_emin))", "(('—') if (_eq(c_c,0)) else (b_Lev))", "(('N/A') if (_eq(c_c,0)) else (((a_emin)/_max(b_Lev,1e-09))))", "'—'"),
    (47, 'CHEQUEO', 'Paso s ≥ 3·db', 'J3.3 (preferido)', 'cm', '(3*a_db)', 'a_s', '(((3*a_db))/_max(a_s,1e-09))', "'—'"),
    (48, 'CHEQUEO', 'Elemento dentro del alma libre', 'Geometría', 'cm', '((c_top) if ((c_top>0)) else (b_k))', 'e_top', '_max((((c_top) if ((c_top>0)) else (b_k))/_max(e_top,1e-09)),(((e_top+e_L))/((b_d-((c_bot) if ((c_bot>0)) else (b_k))))))', "'—'"),
    (49, 'CHEQUEO', 'Doble ángulo: L ≥ T/2 (estabilidad)', 'Manual Parte 10', 'cm', "(('—') if (_eq(t_da,0)) else ((((b_d-(2*b_k)))/2)))", "(('—') if (_eq(t_da,0)) else (e_L))", "(('N/A') if (_eq(t_da,0)) else ((((((b_d-(2*b_k)))/2))/_max(e_L,1e-09))))", "'—'"),
    (50, 'CHEQUEO', 'Destaje: c ≤ 2d', 'Manual Parte 9', 'cm', "(('—') if (_eq(c_c,0)) else (c_c))", "(('—') if (_eq(c_c,0)) else ((2*b_d)))", "(('N/A') if (_eq(c_c,0)) else (((c_c)/_max((2*b_d),1e-09))))", "'—'"),
    (51, 'CHEQUEO', 'Destaje: dc ≤ d/2 (sup.) | 0.2d (doble)', 'Manual Parte 9', 'cm', "(('—') if (_eq(c_c,0)) else (c_top))", "(('—') if (_eq(c_c,0)) else ((((0.2) if (_eq(destaje,'Destaje doble (sup. = inf.)')) else (0.5))*b_d)))", "(('N/A') if (_eq(c_c,0)) else (((c_top)/_max((((0.2) if (_eq(destaje,'Destaje doble (sup. = inf.)')) else (0.5))*b_d),1e-09))))", "'—'"),
    (52, 'CHEQUEO', 'Gramil ángulo lado soporte vs. alma de viga', 'Geometría (llave)', 'cm', "(('—') if (_eq(t_da,0)) else ((a_db*1.5)))", "(('—') if (_eq(t_da,0)) else (((an_gs/10)-(b_tw/2))))", "(('N/A') if (_eq(t_da,0)) else ((((a_db*1.5))/_max((an_gs/10),1e-09))))", "'—'"),
    (53, 'CHEQUEO', 'Holgura viga – soporte ≥ 0', 'Geometría', 'mm', '0', 'setback', '((0) if ((setback>=0)) else (1.5))', "'—'"),
]
